clementine-player/Clementine

- src/dbus/metatypes.h
- src/internet/podcasts/podcastepisode.cpp
- src/internet/podcasts/podcastservice.cpp
This fixer scripts are really ugly, but I use them and it's pain to move the commits out of the way for each pr
Formatting in src/dbus, I just couldn't help myself
mtime was broken after change in PodcastDeleter that set an invalid listened date after deleting episode.
> Adding some fixer scripts in dist, formating is src/dbus and fix for mtime in podcasts

- ext/libclementine-tagreader/tagreader.cpp
- src/ui/edittagdialog.cpp
- tests/song_test.cpp
> Fix album artist for FLAC/OGG files (with vorbis comments)

- src/core/player.cpp
- src/core/player.h
- src/ui/behavioursettingspage.cpp
- src/ui/behavioursettingspage.ui
- src/ui/mainwindow.cpp
Hey guys, @corco requested in #4638 that the previous button restarted the song if it were pressed, like the iPod behavior, so I added that option in Clementine's behavior page. I kept the 2 seconds mentioned by him as I don't own an iPod myself.
> Added iPod-like behavior to previous button (closes #4638)

- src/widgets/nowplayingwidget.cpp
- src/widgets/nowplayingwidget.h
This is simply another option in the Now Playing widget's drop-down box, which says "Large album cover (no details)". It shows the album cover alone, without the song information, for those who prefer this clean look.
> Add Now Playing widget option: No Song Details

- src/internet/subsonic/subsonicservice.cpp
If the subsonic server is empty the "fetching Subsonic library" doesn't stop because we don't emit the scan is finished.
> Emit scanfinished when the library is empty

- src/internet/podcasts/podcastdeleter.cpp
- src/internet/podcasts/podcastdownloader.cpp
A small patch to allow me to debug autodeleter and use PodcastDownload::Queued for a first step of a download
> Small fixes for podcasts

- src/transcoder/transcodedialog.cpp
Replace an obscure line in the transcode dialog with its more readable counterpart. Cf the [corresponding place](https://github.com/clementine-player/Clementine/blob/master/src/ripper/ripper.cpp#L136) in the CD ripper.
> Increase the readability of a line in the transcodedialog

- src/internet/core/cloudfileservice.cpp
- src/internet/core/cloudfileservice.h
- src/internet/seafile/seafileservice.cpp
- src/internet/seafile/seafileservice.h
- src/internet/seafile/seafilesettingspage.cpp
Just added informations via the taskmanager because the build of the Seafile index could be pretty long if the library have many directories
Now Clementine waits the previous index build if the user wants to change the library, it's cleaner.
Finally ReadTagsFinished ignore replies of a previous indexing which was cancelled. It's not the best solution since the tagreaders still download informations about the tracks but I didn't find a better one.
> Try to make Seafile implementation more robust

- src/ripper/ripcddialog.cpp
- src/transcoder/transcodedialog.cpp
- src/transcoder/transcodedialog.h
The transcoder currently produces incorrect paths when specifying a destination directory on Windows.
This implementation fixes this by using QFileInfo to obtain system-independent file information.
Fixes #4579.
> Construct filenames with correct paths on all platforms

- README.md
I think Clementine needs this section to help people (and us) when they want to open an issue.
> Add "opening issue" to the README

- src/networkremote/networkremote.cpp
- src/networkremote/remoteclient.cpp
Memory leak happened when Android-Remote tries to reconnect to Clementine. This is the cause of the problem mentioned in issue #4737.
> Fix memory leak in networkremote.

- data/data.qrc
- data/schema/schema-49.sql
- ext/libclementine-tagreader/tagreader.cpp
- ext/libclementine-tagreader/tagreadermessages.proto
- src/CMakeLists.txt
- src/core/database.cpp
- src/core/metatypes.cpp
- src/core/mpris1.cpp
- src/core/organiseformat.cpp
- src/core/song.cpp
- src/core/song.h
- src/songinfo/songinfofetcher.cpp
- src/songinfo/songinfoview.cpp
- src/songinfo/taglyricsinfoprovider.cpp
- src/songinfo/taglyricsinfoprovider.h
- src/ui/mainwindow.cpp
- src/ui/organisedialog.cpp
- src/widgets/osd.cpp
The requested pull request to issue 4783 (https://github.com/clementine-player/Clementine/issues/4783).
-Added schema to the database to store it
-Added readers/writers for ID tags
-Added readers/writers for the database to the song class
-Added the taglyricsinfoprovider to show the lyrics in songinfo
Remaining bug:
The taglyricsinfoprovider does not trigger the display of the CollapsibleInfoPane on the InfoResultReady-Signal.
Although taglyricsinfoprovider as Q_OBJECT inherits from SongInfoProvider and is added to SongInfoView.fetcher_ .
Any ideas/tips on this are appreciated. Anything else works.
> Added support to read/display the ID tag lyrics in MP3 files:

- src/playlist/playlist.cpp
I absolutely love how the queued items are not removed, however I find it odd (and counter-intuitive) that the currently playing track is also removed.
I would personally consider the currently playing item to be "in the queue", so I don't think the modified function loses its meaning. It's also only called in one place, so there is no risk of any regressions.
> Do not remove currently playing track when repopulating a dynamic playlist

- src/globalsearch/spotifysearchprovider.cpp
Currently, Spotify results are problematic for two reasons, which are both demonstrated in this screenshot of the results for a single New Pornographers album:
Firstly, they are not assigned an album artist, so albums with different artists per track that should have a single album artist and therefore show up as one album when sorting by Album Artist are split up into two.  In this case, track 8 (Born With a Sound) features Amber Webber, so even though I am grouping by Album Artist, the album is split up between two artists.  When you add the album under The New Pornographers to your playlist, it is missing track 8, since that is filed under "The New Pornographers, Amber Webber".  My proposed solution here is to choose a "majority artist" by tallying up which artist shows up most often, …
> Improve handling of Spotify Top Tracks and compilations

- data/schema/device-schema.sql
Connecting and scanning of a new device failed due to the missing lyrics
field. This fixes it.
> Add lyrics field to device databases.

- src/musicbrainz/chromaprinter.cpp
- src/musicbrainz/chromaprinter.h
Fixes among other things the "GLib-CRITICAL **: Source ID XXX was not found" error.
And some cleanup for GStreamer was missing (when creating fingerprints for many (<400 tracks) Clementine did SegFault with some GStreamer errors.)
Tested with
* broken mp3s
* short (<30sec) tracks
* many (>1000) tracks
performance/computation time is about the same
> Simplification and cleanup fixes for chromaprint fingerprint creation.

- ext/libclementine-tagreader/tagreader.cpp
Try to be more coherent when we set the album artist tag with vorbis comments. 
Fix an issue when the "ALBUMARTIST" tag was already set and modified with Clementine.
> Fix setting album artist tag for FLAC files if it already exists

- src/playlist/playlistview.cpp
Currently we just scroll to the current index of the last playlist in the new one. This makes no sense and leads to the scrollbars acting like they are "linked" together. This is frustrating when switching between long and short playlists.
This change scrolls to the last played track in each playlist on transition.
> Scroll to last played track when switching playlists

- src/ui/albumcoverchoicecontroller.cpp
When showing the album cover from the now playing widget, the cover is scaled to fit the screen. However if the screen is made up of 2 or more monitors of different resolutions, it will always be scaled to the largest one.
This change ensures that the cover is scaled to the size of the monitor Clementine's main window is on, or the primary if indeterminate.
> Scale cover art to the current monitor, not the entire virtual screen

- src/globalsearch/globalsearchmodel.cpp
- src/library/librarymodel.cpp
- src/library/librarymodel.h
When grouping by disc in the library, the discs are currently sorted in lexical order, e.g  1 10 100 2 22 3, which is quite irritating for albums with a large number of discs.
This pr changes this so that the discs are sorted numerically.
> Sort discs  numerically when using Group by disc

- src/core/player.cpp
Regression from #4866 
I don't know why this line was removed. It is required to tell the playlist manager to stop the glow on the playing track once it has stopped. Without it, the track will always show as playing, and the moodbars stop working.
Adding it back in doesn't seem to break the stop after every track feature from my testing.
> Fix playlist not deselecting playing track when stopping

- src/ui/mainwindow.cpp
When we want to save the state, Clementine always play the music when we open it even if it was paused at the shutdown.
This is because the `pause()` is skipped because the current pipeline is still not in playing state: we have to wait.
> Fix save state when the song was paused

- src/widgets/nowplayingwidget.cpp
Introduced in #4416, clicking the cover will show the large art. In Windows, it seems that the click release event that triggers this is also associated with the right mouse button, so the art comes up when you bring up the context menu. This just checks if it was the left button released.
> Fix context menu for the NowPlayingWidget in Windows

- ext/libclementine-tagreader/tagreader.cpp
- ext/libclementine-tagreader/tagreader.h
- src/ui/edittagdialog.cpp
- src/ui/edittagdialog.ui
- src/widgets/nowplayingwidget.cpp
- Fixed decoding of non-ASCII lyric texts
- Lyrics can now be viewed/edited in the metadata-editor
Squashed commit of the following:
commit bab7a1d07af3bc53034e3883d352ae6d4dd33e2a
Author: Martin Babutzka <martin.babutzka@online.de>
Date:   Sun Jun 7 01:51:31 2015 +0200
Added capability to SAVE lyrics frames to mp3 files in tagreader.
Improved scaling properties of edittags dialog.
commit 4bd71a2d6a4479a664bf8b5b3ead05c23c86e15d
Author: Martin Babutzka <martin.babutzka@online.de>
Date:   Sat Jun 6 23:33:22 2015 +0200
Updated lyrics tag buddy to lyrics
commit 2ceb8967f67e76a0f78b25a7a128c4429a93bcd9
Author: Martin Babutzka <martin.babutzka@online.de>
Date:   Sun May 17 18:52:33 2015 +0200
Add lyrics field to tag editor
commit 04b65e33a83e449055659a72a283954311a12fb7
Author: Martin Babutzka …
> Improvements to the ID3-tag lyrics capabilities

- src/musicbrainz/musicbrainzclient.cpp
- tests/musicbrainzclient_test.cpp
Apparently, we have forgotten to parse the year from MusicBrainz when we read a disc.
> Parse the year of a disc from musicbrainz.

- ext/clementine-spotifyblob/spotifyclient.cpp
- ext/libclementine-common/core/logging.cpp
- ext/libclementine-common/core/logging.h
I adapted the spotify codes to qt5 (just some ascii things).
The second part is more complicated since I don't understand why it didn't work (and why I didn't notice compilations failed with the new system of logging in the last qt5 PR). 
I had these kind of errors:
CMakeFiles/clementine-tagreader.dir/tagreaderworker.cpp.o: in function « logging::CreateLoggerFatal() »:
tagreaderworker.cpp:(.text+0x0): multiple definitions of « logging::CreateLoggerFatal() »
CMakeFiles/clementine-tagreader.dir/main.cpp.o:main.cpp:(.text+0x0): defined here
It seems the *qLog* macro defined a new function each time it was called (replacing itself with `QDebug CreateLoggerFatal() { return qCreateLogger(Fatal); }` instead of `return qCreateLogger(Fatal);`.
I moved the definitions of the functions in the *.cpp* …
> [Qt5] Fix compilation error and adapt spotify part to Qt5

- src/ripper/ripcddialog.cpp
- src/ripper/ripcddialog.ui
Make the CD ripper dialog use the same naming scheme for replacement
strings as the organise dialog.
> [Ripper] Use consistent names for replacement strings

- src/analyzers/blockanalyzer.cpp
As it stands, the block analyzer just chops off columns to the right if the window is too small and always internally runs off 256 columns. Since the analyzer is bounded to 256 columns, this qMax bound is totally pointless.
It also makes the demo asymmetrical which trips up my OCD whenever Clementine is idling...
> Bound the Block Analyzer's column count

- data/data.qrc
- data/schema/device-schema.sql
- data/schema/jamendo.sql
- data/schema/schema-50.sql
- ext/libclementine-tagreader/tagreader.cpp
- ext/libclementine-tagreader/tagreadermessages.proto
- src/core/database.cpp
- src/core/organiseformat.cpp
- src/core/song.cpp
- src/core/song.h
- src/globalsearch/globalsearchmodel.cpp
- src/globalsearch/globalsearchview.cpp
- src/library/groupbydialog.cpp
- src/library/groupbydialog.ui
- src/library/librarymodel.cpp
- src/library/librarymodel.h
- src/playlist/playlist.cpp
- src/playlist/playlist.h
- src/playlist/playlistfilter.cpp
- src/playlist/playlistview.cpp
- src/smartplaylists/searchterm.cpp
- src/smartplaylists/searchterm.h
- src/ui/organisedialog.cpp
A song may have a tag with the year of the release of the disc it was ripped from and a tag containing the year of the first release of the disc. 
See "date" and "originaldate": https://picard.musicbrainz.org/docs/tags/
This PR adds support for showing the original year on the playlist and adds "Original year" and "Original year - Album" to the library grouping options.
So far, there is only support for this tag on ID3v2 and Ogg files.
> Add support for original year tags

- src/library/library.cpp
I hadn't realized that a full rescan would be requiered on existing libraries.
> Add full rescan reason for original year tag support.

- src/analyzers/boomanalyzer.cpp
- src/analyzers/boomanalyzer.h
- src/analyzers/turbine.cpp
Boom and Turbine remain small fixed-size analyzers with a few issues with regards to colours.
This update attempts to remedy these issues.
Changes:
-Both analyzers now resize to fit the size of their container, and scale to the lower frequencies if in a small window
-The colour now does not change as the main window gains/loses focus
-The peak bars now use a colour which is actually visible (I didn't even know they existed before!)
> Update Boom and Turbine analyzers

- src/analyzers/analyzerbase.cpp
- src/analyzers/analyzerbase.h
- src/analyzers/analyzercontainer.cpp
- src/analyzers/analyzercontainer.h
- src/analyzers/baranalyzer.cpp
- src/analyzers/baranalyzer.h
- src/analyzers/blockanalyzer.cpp
- src/analyzers/blockanalyzer.h
- src/analyzers/boomanalyzer.cpp
- src/analyzers/boomanalyzer.h
- src/analyzers/fht.cpp
- src/analyzers/fht.h
- src/analyzers/nyancatanalyzer.cpp
- src/analyzers/rainbowdashanalyzer.cpp
- src/analyzers/rainbowdashanalyzer.h
- src/analyzers/sonogram.cpp
- src/analyzers/sonogram.h
- src/analyzers/turbine.cpp
(Well, except Nyanalyzer and Rainbow dash because they are already colourful enough.)
I have added functionality for any 2D analyzer to change any part of its colour palatte with the frequency content of the music, in the same way that Moodbars do.
I find this gives the analyzer a sort of "third dimension".
This is built into Analyzer::Base, so all analyzers can use it and override it as they please. I have thus added support for Block, Boom, Turbine, Sonogram, and Bar, however Boom and Block seem to look the best in my opinion. This is of course all optional and is toggled by a checkbox in the context menu for the analyzer, disabled by default. I have not been able to measure any increase in CPU activity with this enabled, even at 60fps. I am by no means an expert on colour theory, so …
> Add "Psychedelic Colour" mode to all analyzers

- ext/libclementine-common/core/logging.cpp
- ext/libclementine-common/core/logging.h
- src/smartplaylists/searchtermwidget.cpp
Keep in mind the line where the macro is called and we log to print it.
> [Qt5] Fix log messages (lines and classname)

- src/core/player.cpp
- src/playlist/playlistview.cpp
- src/playlist/playlistview.h
- src/ui/mainwindow.cpp
- src/widgets/trackslider.cpp
- src/widgets/trackslider.h
- src/widgets/tracksliderslider.cpp
- src/widgets/tracksliderslider.h
Seeking using arrow keys behaved differently depending on which widget received the keypress event.
It may be a good idea to define a constant with the number of seconds to seek instead of using a hardcoded 1.
> Make seeking with keys behaviour consistent.

- src/core/song.cpp
This was reverted in 1f97406171eb82027fd2bec73514e497f3df7eee, but like I commented there, MutableTrack::setAlbumArtist is supported by the latest version of liblastfm, as well as all versions since at least 1.0.0, released Jun 11, 2012.
My guess is that @hatstand was using an old version of liblastfm.
Issue: #4354
Original PR: #4363
> Send album artist to Last.fm

- src/widgets/osdpretty.cpp
Fixes #1218
Windows uses the primary monitor as the origin for coordinates, so any monitor to the left or above the primary uses negative coordinates. This would cause the OSD to always be displayed on the primary as the negative values would be set to 0.
> Fix Pretty OSD positioning on Windows

- src/engines/gstenginepipeline.cpp
Relates to #4935.
Gstreamer was failing to link the pipeline if a 32bit pipe could not be established.
We should just let gst autonegotiate the bit depth of the pipeline, which it does with mono disabled anyways.
I've tested with a Windows system that failed before, and it now works correctly with this change.
> Fix mono playback on certain configurations

- CMakeLists.txt
- src/main.cpp
- src/songinfo/echonestbiographies.cpp
- src/songinfo/echonestimages.cpp
- src/songinfo/echonestsimilarartists.cpp
- src/songinfo/echonesttags.cpp
- src/songinfo/songkickconcerts.cpp
Unfortunately I didn't find a more elegant solution.
Closes https://github.com/clementine-player/Clementine/issues/4941
> Fix echonest qt5 compilation issues with different GNU/Linux distributions

- src/analyzers/sonogram.cpp
- src/analyzers/sonogram.h
Fixes #755
All the other analysers stop, including nyan and rainbow, so sonogram should too.
> Sonogram should stop scrolling when paused

- src/engines/gstengine.cpp
- src/engines/gstengine.h
- src/engines/gstenginepipeline.cpp
- src/engines/gstenginepipeline.h
- src/ui/playbacksettingspage.cpp
- src/ui/playbacksettingspage.ui
This is meant to be a feature, but it also triages #4189, #4748, #4613?
This change provides the ability to set a fixed pipeline sample rate as an alternate to automatically negotiating it (the default). This can be useful on systems with sound cards that work at a fixed rate, as well as it can triage issues where changing tracks hangs due to a problem with gstreamer's caps negotiation.
I've noticed myself that when transitioning between tracks with different sample rates on Windows, the pipeline will always hang on starting the next song. This seems to be gstreamer not negotiating the downstream caps for sample rate. In fact if you disable "exclusive mode" on your sound card in Windows, the pipeline cannot start at all without a set sample rate. I don't want to say this is *the* …
> Add sample rate selection

- data/lyrics/ultimate_providers.xml
- tools/ultimate_lyrics_parser/sites.js
It seems that letras.mus.br is now always enconded in utf-8. For example, see: http://letras.mus.br/winamp.php?musica=non%C3%B4&artista=nara+le%C3%A3o+_+nelson+rufino
Therefore I switched the encodings to utf-8, fixing Issue #4091.
> Fixed #4091 - Reverted letras.mus.br to utf-8

- src/playlist/playlist.cpp
When sorting the playlist by album, it also sorts by disc number and track number. That way multi-disk albums get their proper playing order.
This was requested in isues #2315 and #2317.
> Playlist sort by album considers disc and track numbers

- src/ui/mainwindow.cpp
- src/widgets/trackslider.cpp
Removed two extra lines from ui/mainwindow.cpp which actually causes the blinking.
The additional condition in widgets/trackslider.cpp is for preventing initially displaying the
"0:00:00" text on the "remaining time" label when you start to play streams without known duration
from the "Stop" player's state.
Closes #4990.
> Fix time labels blinking when playing streams without known duration

- src/analyzers/analyzercontainer.cpp
Clementine crashes when you try to toggle psychedelic colors with analyzer disabled.
> Add condition against nullptr dereferencing to AnalyzerContainer::TogglePsychedelicColors()

- src/ui/behavioursettingspage.cpp
This is a very small change that should fix the unexpectedly changed default settings as pointed out [in the prior pull request](https://github.com/clementine-player/Clementine/pull/4991#issuecomment-136908074).
> Fixed default settings for double clicking a playlist

- src/library/libraryview.cpp
library view sorts the library and display the contents in alphabetical order (bold letter/number followed by a line) . the line cannot be themed as it is hard-coded "QPen line_pen(opt.palette.color(QPalette::Dark))". Here i try to remove the line, align the letter to right and give the letter a highlight using QRect. this way it looks better and is completely themable ...
check the screenshots.. (should work for all platforms)
> clean up library view

- src/widgets/sliderwidget.cpp
This modification makes the volume percentage text color match general text color.
> volume text color palette

- src/songinfo/songinfotextview.cpp
- src/songinfo/ultimatelyricslyric.cpp
- src/songinfo/ultimatelyricsprovider.cpp
This changes the way we try to intelligently convert `\n` to `<p>` in song/artist info views (see [discussion](https://github.com/clementine-player/Clementine/commit/c35ba55e750a0824bd3f32da8c22b4c380dfffbd#commitcomment-13451549)):
Two or more newlines are converted to `<p>`, a single newline is converted to `<br>`.
Also an indexing error is fixed that cut the last character of the extracted content.
> Fixes for songinfo/lyrics

- src/ripper/ripcddialog.cpp
- src/ripper/ripper.cpp
- src/ripper/ripper.h
The duration in seconds is computed using integer division which should be close enough.
> Show track durations in the CD ripper dialog.

- src/playlist/playlistsequence.cpp
before 
(some indicators are even worse)
after
> Remove arrow indicators from mainwindow repeat & shuffle QToolButtons

- src/ui/mainwindow.cpp
PR #5081 created a regression where the mainwindow will always start on the primary monitor regardless of which one it was closed on when maximized. This restores previous functionality.
> Respawn mainwindow on correct monitor

- src/playlist/playlist.cpp
Fixes #5031
Attempt to set the song after the deleted tracks as the current so that they will play next rather than the beginning of the playlist.
> Set next track as current when removing tracks

- src/core/network.cpp
Add calls to the base class constructor in two classes so that the `parent` argument gets passed along.
> Add missing calls to base class constructor

- src/CMakeLists.txt
- src/internet/subsonic/subsonicdynamicplaylist.cpp
- src/internet/subsonic/subsonicdynamicplaylist.h
- src/internet/subsonic/subsonicservice.cpp
- src/internet/subsonic/subsonicservice.h
- src/smartplaylists/generator.cpp
Notes:
- These playlists allow access to the subsonic feature of pulling new, frequently played, and so on albums.
- See: http://www.subsonic.org/pages/api.jsp#getAlbumList for the subsonic description
- The subsonic api is inherently album oriented.  Therefore at the moment the "count" argument for GenerateMore is used as the number of albums to pull, which hopefully isn't a problem.
- Could be made more efficient by multi-threading the fetch of the songs for each album
> Add "Smart Playlists" for subsonic

- src/internet/subsonic/subsonicdynamicplaylist.cpp
- src/internet/subsonic/subsonicservice.cpp
- src/internet/subsonic/subsonicservice.h
- Ampache recently added support for returning playcounts, if the client
reports that it knows it's talking to an ampache server:
https://github.com/ampache/ampache/commit/1aaf01ae98de9fb92e3d46e2e94497830ac9740b
- This checks the type attribute on the ping request to see if
Clementine is talking to an Ampache server, and if so, it adds
ampache=1 to getAlbum requests, and uses the returned playcounts.
> Add ampache=1 to getAlbum for playcounts

- src/playlist/playlist.cpp
- src/playlist/playlist.h
- src/playlist/playlistmanager.cpp
- src/ui/mainwindow.cpp
- src/ui/trackselectiondialog.cpp
- src/ui/trackselectiondialog.h
Closes https://github.com/clementine-player/Clementine/issues/5133
When the auto tagger fails for a song I made the choice (suggested in the issue) to display the error in a popup because people generally don't have/read the logs.
> Add error message if editing tag from playlist fails

- src/core/song.cpp
This should fix https://github.com/clementine-player/Clementine/issues/5086
> Reload playcount from tagreader only if it is set

- src/moodbar/moodbarproxystyle.cpp
- src/moodbar/moodbarproxystyle.h
Partial revertion for commit "3f79fa5c651f23e48faf1af6ca56dbff9e5660ab" because of
https://github.com/clementine-player/Clementine/issues/4770
> Avoiding usage of pixelMetric because it breaks on non-Oxygen styling

- src/widgets/favoritewidget.cpp
- src/widgets/favoritewidget.h
* Use the star icon in its native size (16 px × 16 px) instead of unnecessarily scaling it down by 1 px
* Center the star icon vertically
> Improve the star icon of `favoritewidget`

- src/widgets/fileview.cpp
When selecting a file from the file browser, pressing Enter now has the same effect than double-clicking it. (#5178)
> Enable Enter key shortcut in file view

- src/playlist/playlistview.cpp
When the mainwindow redraws the playlist and the window is not focused, the text colour for the currently playing track changes (usually white to black on the default palette) which is wrong and has poor contrast. This usually happens when changing tracks with keyboard shortcuts, or when the Score column updates at the scrobble point.
> Fix incorrect highlight colour in playlist when the window is inactive

- src/internet/digitally/digitallyimportedservicebase.cpp
- src/internet/digitally/digitallyimportedservicebase.h
- src/internet/digitally/digitallyimportedsettingspage.cpp
- src/internet/digitally/digitallyimportedurlhandler.cpp
Digitally Imported stopped public streaming on 3rdparty clients to non premium users.
https://diradio.uservoice.com/forums/183400-digitally-imported-feedback/suggestions/11272656-restore-3rd-party-clients
Unfortunately I don't have a premium account so I can not test if this PR don't break premium access.
> Disable digitally imported for free user (premium account required)

- src/transcoder/transcoder.cpp
Fixes #5203.
Btw, I tried removing the block completely in the hope that it wouldn't be needed anymore. Unfortunately it didn't work.
> Use mp4mux instead of ffmux_mp4 when transcoding to aac

- src/internet/core/internetview.cpp
- src/internet/core/internetview.h
- src/library/libraryview.cpp
- src/widgets/autoexpandingtreeview.cpp
- src/widgets/autoexpandingtreeview.h
Changes made by this PR:
- Fixed issue #4485
- Fixed misbehavior when you double click after a single/double click on a song item in library or internet views
- Made "AutoExpandingTreeView" animated by default
- Added ability to collapse current branch in "AutoExpandingTreeView" by pressing "Left" key on items under its root
> Resolve some issues related to "AutoExpandingTreeView" 

- src/library/librarywatcher.cpp
This closes issue #5151.  Two unicode strings need to be normalized before being compared.
> Fix issue in checking existence of media files pointed by CUE files

- src/internet/podcasts/podcastparser.cpp
There was a pull request back in September to implement something like this that never got merged: https://github.com/clementine-player/Clementine/pull/5036
I was toying with the qt5 branch today, and realized that importing / exporting podcasts with gpodder was kind of completely broken.
This is both a fix for gpodder not conforming to OPML standards and a general best practice. According to the spec, title is an optional attribute but if there is a title we should be... titling our podcasts based off of it, since text can be user modifiable in exporters. This is an amendment to jbroadus' work since we should be using title attributes in priority over text anyway, and this fixes both the empty title and description as title problems.
I'm also[ pushing changes to mygpo to fix their OPML …
> OPML imports should prefer title to text attributes for podcast names

- src/widgets/equalizerslider.cpp
- src/widgets/equalizerslider.h
- src/widgets/equalizerslider.ui
Display the selected gain (in dB) under each equalizer bar. (#3157)
> Add gain label to EqualizerSlider

- src/ui/edittagdialog.cpp
- src/ui/edittagdialog.h
A fix for old tag values getting erased (instead of overwritten) in the edit tag dialog when fetching tags with MusicBrainz.
Replacement for pull request #5131 ; issue #3355 is still fixed.
[Maybe the `textEdited` signal can be connected instead of `textChanged` but I didn't want to break anything else. Specially for the next stable release.]
> Fix bug in edit tag dialog when fetching (2)

- src/moodbar/moodbarproxystyle.cpp
When switching playback from an item for which the moodbar is not
displayed (e.g. an internet stream), to an item for which it is
displayed (e.g. a local mp3 file), Clementine sometimes crashes.
This happens because the slider_opt->maximum and slider_opt->minimum
have the value 0 (their default value), and the difference is used as a
divisor.  This gives a division by 0, and a SIGFPE.
This problem has been fixed in commit af42cce.  However, when a9f9b0e
reverted 3f79fa5, a little to much was reverted and we lost what af42cce
did.  This patch re-introduces the fix.
Fixes #5261
> moodbar: check QSlider max/min before using them in division

- dist/clementine.desktop
- src/core/commandlineoptions.cpp
- src/core/commandlineoptions.h
- src/ui/mainwindow.cpp
As suggested in #5304 I have added support for the command-line flag `-q, --stop-after-current` and added this option to the Unity launcher icon.
I have no previous experience with C/C++, so I might have made some rookie mistakes. However, this change seemed pretty straight-forward, the code compiles without errors and everything seems to work as intended.
> "Stop after current" as command-line option

- src/internet/subsonic/subsonicservice.cpp
- src/internet/subsonic/subsonicservice.h
Fixes the following compiler error:
/home/alex/builds/clementine-git/src/Clementine/src/internet/subsonic/subsonicservice.cpp:62:28: error: ‘const int SubsonicService::kCoverArtSize’ is not a static data member of ‘class SubsonicService’
const int SubsonicService::kCoverArtSize = 1024;
^
/home/alex/builds/clementine-git/src/Clementine/src/internet/subsonic/subsonicservice.cpp: In member function ‘void SubsonicLibraryScanner::GetAlbumCover(const QString&)’:
/home/alex/builds/clementine-git/src/Clementine/src/internet/subsonic/subsonicservice.cpp:593:44: error: ‘kCoverArtSize’ was not declared in this scope
url.addQueryItem("size", QString::number(kCoverArtSize));
^
> Fixed compile error for the subsonic module.

- src/core/mpris2.cpp
- src/core/mpris2.h
- src/playlist/playlist.cpp
Clementine does not send the correct signal about the changed properties such as CanGoNext, CanGoPrevious, CanSeek and may cause programs that listen to those changes use the wrong information. 
To check the corect signals are send one can use:
`dbus-monitor --session --monitor "type='signal',interface=org.freedesktop.DBus.Properties,member=PropertiesChanged,path=/org/mpris/MediaPlayer2"`
> Fix mpris dbus notifications

- src/ui/mainwindow.cpp
Fixes #5312.
To be able to populate the sources list `GlobalSearch` requires `InternetModel` to be initialised before. The issue #5312 started happening since the commit f2daa772c1090e866cacb7fce68a9240ffe3e766.
> Move global search settings loading later in "MainWindow" initialisation

- data/lyrics/ultimate_providers.xml
AZLyrics breaks old rule - the site always returns:
```html
<div class="hidden">Visit www.azlyrics.com for these lyrics.</div>
```
> Update AZLyrics parsing rule

- src/core/commandlineoptions.cpp
- src/core/commandlineoptions.h
- src/main.cpp
- src/playlist/playlist.cpp
- src/playlist/playlist.h
- src/ui/mainwindow.cpp
- src/ui/mainwindow.h
This fixes at least two problems of unwanted behaviour when starting clementine with commandline parameters which contradict with other settings (restoring playback status and doubleclick behaviour).
Hope everything is clear, as always I'll explain more if needed.
> Fix playlist behaviour

- src/library/librarywatcher.cpp
Should solve issue #3584. I am currently testing it out on my large hard drive that contain music and many other things (that slows down the crawling)
> Don't scan directories with .nomedia or .nomusic files

- src/core/song.cpp
When playing a stream with no metadata the main window's title is set to an empty string. This is inconvenient because it can cause the minimized window to be shown as "Untitled Window" in the desktop's taskbar. (I have observed it in XFCE).
This modification makes the stream's URL to be set as the title. That is not only useful, but consistent with the current behavior for local files: when lacking a title, their path is displayed.
> Fix "Untitled Window" when playing a stream with no metadata

- src/internet/subsonic/subsonicservice.cpp
Some query parameters are being overwritten by the query therefore silently failing (auth error)
> Fixing a couple of issues with subsonic in the qt5 port

- dist/CMakeLists.txt
- dist/clementine.spec.in
protocol files are stored in `/usr/share/kservices5` PATH in Plasma 5
> QT5: Fix DESTINATION path for protocol files

- src/ui/behavioursettingspage.cpp
- src/ui/behavioursettingspage.ui
- src/ui/qtsystemtrayicon.cpp
- src/ui/qtsystemtrayicon.h
This fixes #4918 
Also adds setting for old behavior. I've also found support for Ctrl and Shoft modifiers in source code, but they do not work on Linux (maybe on other OS's too)
> Scrolling over tray icon support

- src/engines/gstenginepipeline.cpp
In the new version of gstreamer, alsasink now supports floating samples, so it seems to be bypassing audioconvert. If the sound card does not support float samples, the pipeline will not link.
Integer samples make downmixing work correctly on all the sound cards I tested with ALSA.
> Fix pipeline with direct output to ALSA

- src/ui/mainwindow.cpp
- src/ui/mainwindow.h
Always switch to the library tab when clicking on 'Show in library' in the playlist context menu. This was proposed in the comments of #4107.
> Switch to the library tab when using the 'Show in library' feature

- src/songinfo/spotifyimages.cpp
This prevents a segfault when no artist images are received from spotify.
> Cope with empty spotify image responses

- src/widgets/fileview.cpp
- src/widgets/fileviewlist.cpp
- src/widgets/fileviewlist.h
Allows navigating back and forward through the navigation history in the Files view using not only the UI buttons, but Back and Forward mouse buttons as well.
The switch is constructed this way so that folder selection wouldn't get lost after changing directory using the mouse buttons.
Could you please review it?
> Back/Forward mouse buttons support (closes #4809)

- dist/clementine.desktop
fix the desktop-file-validate (part of [desktop-file-utils](https://freedesktop.org/wiki/Software/desktop-file-utils/)) complains about the clementine.desktop:
```
dist/clementine.desktop: warning: key "OnlyShowIn" in group "Desktop Action Play" is deprecated
dist/clementine.desktop: warning: key "OnlyShowIn" in group "Desktop Action Pause" is deprecated
dist/clementine.desktop: warning: key "OnlyShowIn" in group "Desktop Action Stop" is deprecated
dist/clementine.desktop: warning: key "OnlyShowIn" in group "Desktop Action StopAfterCurrent" is deprecated
dist/clementine.desktop: warning: key "OnlyShowIn" in group "Desktop Action Previous" is deprecated
dist/clementine.desktop: warning: key "OnlyShowIn" in group "Desktop Action Next" is deprecated
```
Some info why it is deprecated may be …
> Remove OnlyShowIn=Unity from clementine.desktop's action sections

- src/ui/edittagdialog.ui
Change the layout in `edittagdialog.ui` to correct #5437 .
Now the minimum height is 600px. Also, the last two labels (*Lyrics* and *Comment*) are properly aligned.
> Restructure edittagdialog layout (corrects #5437)

- src/playlist/playlist.cpp
This makes sorting by `filename` (path) return the expected result.
For example:
* /Music/a.mp3
* /Music/c.mp3
* /Music/Brooklyn/b.mp3
* /Music/Brooklyn/z.mp3
* /Music/Charlie/a.mp3
* /Music/Charlie/e.mp3
* /Music/Brooklyn/X/l.mp3
> Ignore case in path comparison (#5445)

- src/library/librarymodel.cpp
The library model should not try to permanently cache the ```no_cover_icon``` since the art might load next time it is viewed.
> Fix caching of missing album covers

- src/playlist/playlist.cpp
List with playback order should be resorted too after sorting playlist view. It will prevent misunderstanding with playback order.
> Update playlist virtual order after sorting (#5436)

- src/library/libraryfilterwidget.cpp
Hi, this is a popular sorting method for those of us who have albums with multiple artists featured. Sorting this way places all the songs in one album, rather than splitting it into 5 albums due to featured artists.
I would argue that having this as a standard option rather than an custom option is something warranted. Right now it looks as though the standard options were chosen because they were all different from one another. Looking at it like that you might disagree with this change at first, but I think it is important have have heavily used things easy to access. :smile: 
As far as naming it "Album artist/Album"... I don't care about the how it is named.
Thank for taking the time to read this
> added popular libraryfiltergroup filter: Album artist/Album

- ext/libclementine-tagreader/tagreader.cpp
- src/songinfo/taglyricsinfoprovider.cpp
This adds support for displaying lyrics from a Vorbis comment in the same way Clementine displays lyrics from ID3v2 tags.
> Add support for displaying lyrics from a Vorbis comment

- ext/libclementine-tagreader/tagreader.cpp
Taglib version 1.9.1-2.4 on debian
> Fix undefined symbol error conversion from std::string to TagLib::String

- src/internet/subsonic/subsonicdynamicplaylist.cpp
According to the documentation, the endpoint is `getAlbumList`, not
`GetAlbumList`. This typo makes the complete feature not working at
all.
Source: http://www.subsonic.org/pages/api.jsp#getAlbumList
> Fix Subsonic endpoint

- src/internet/podcasts/podcastbackend.cpp
This is strange, on the master branch without this patch everything is okay and the podcasts are not forgotten. 
But this causes issues on the Qt5 branch.
> Fix podcast episodes forgotten

- src/engines/gstenginepipeline.cpp
Remove the current restriction to convert the audio to 32 bits. That allows the audiosink to autonegotiate a bit depth value with the decoder, choosing a value that is supported by the hardware.
> Let the audio sink autonegotiate the bit depth. (Fixes #5533)

- src/playlist/playlistmanager.cpp
If using an interface with a file-picker which does not add the suggested file extension automatically (like GTK+ on Ubuntu/Debian), it is possible to enter an invalid file extension (or no extension at all!). This will result in nothing getting saved.
This change just uses the default extension in the event an invalid one is entered.
Related to #2115, since they both stem from the fact that there is no support for certain native file dialogs in Qt.
> Save playlist with default extension on dialogs which do not enforce extensions

- tests/mock_networkaccessmanager.h
> Fix a typo in a header guard

- 3rdparty/qsqlite/clementinesqlcachedresult.h
Q_SQL_EXPORT is defined in qt5/include/QtSql/qsql.h:
```
#ifndef QT_STATIC
#else
#endif
```
qsqlite is static library.
Clementine/3rdparty/qsqlite/CMakeLists.txt:
```
add_library(qsqlite STATIC
${SQLITE-SOURCES}
${SQLITE-SOURCES-MOC}
${SQLITE-WIN32-RESOURCES}
)
```
log: https://gist.github.com/pavelvat/e683a7106b6eca6971d752ad37d52030
> fix Windows build qsqlite

- ext/libclementine-tagreader/tagreader.cpp
- src/internet/core/cloudfileservice.cpp
- src/internet/seafile/seafilesettingspage.cpp
CloudFileService and TagReader classes use
QString::endWith() method for checking file type.
This method is CaseSensitive by default.
> Use CaseInsensitive file type checking #5499

- ext/clementine-spotifyblob/spotifyclient.cpp
Some Spotify playlists never load (libspotify/spotify server bug I guess). This is a workaround in order that Clementine does not stuck on unloaded playlists.
Fixes https://github.com/clementine-player/Clementine/issues/5574
> Workaround to spotify loading playlist issue

- src/widgets/osd_mac.mm
Currently, Clementine notifications pile up on macOS. This clears all notifications before creating a new one, matching the behavior of iTunes.
It appears that this API was [introduced in 10.9](https://developer.apple.com/library/content/releasenotes/Foundation/RN-Foundation-older-but-post-10.8/index.html), so I've got a guard around it.
> macOS: Clear stale native notifications on 10.9+.

- src/core/mergedproxymodel.cpp
- src/devices/giolister.cpp
- src/library/groupbydialog.cpp
This PR simply adds missing `<functional>` includes everywhere `std::placeholders` are used (previously reported in issue #4279, see also [cppreference](http://en.cppreference.com/w/cpp/utility/functional/placeholders)).
This is required to build Clementine on the current gcc 7.0 trunk.
> Add missing <functional> includes

- src/moodbar/moodbarproxystyle.cpp
[This calculation](https://github.com/clementine-player/Clementine/blob/e5ab3e786f9adde12cec3cc90cfe8c1cc6b06320/src/moodbar/moodbarproxystyle.cpp#L278) in `MoodbarProxyStyle` could overflow in certain scenarios. This could cause the progress slider arrow to stop being displayed after a while when the moodbar is enabled (as described in  issue #5638).
> Fix overflow in MoodbarProxyStyle

- src/ui/albumcovermanager.cpp
- src/ui/albumcovermanager.ui
* nocover icon was previously loaded and used with the default size
(24x24), causing the list item without a cover in the QListWidget to be
shorter in height with respect to the others. Now the icon is
initialized to 120x120, which is the default size of the list elements.
* Added some padding between "Fetch Missing Cover" and "Export
Covers" buttons.
> Small improvements to Cover Manager

- src/core/song.cpp
- src/core/song.h
- src/library/librarybackend.cpp
- src/library/librarybackend.h
- src/ui/albumcoverchoicecontroller.cpp
- src/ui/albumcovermanager.cpp
- src/ui/albumcovermanager.h
- src/ui/albumcovermanager.ui
- src/widgets/nowplayingwidget.cpp
As mentioned in #5623, currently the cover manager and search only take into account an album `artist` field.
These changes make it so that the `effective_albumartist` field is used instead, which is defined as: `albumartist_.isEmpty() ? artist_ : albumartist_`.
Also, the cover manager now shows a list of artists composed by all names that appear in some album as either:
* a) `albumartist`, or
* b) `artist` when `albumartist` is empty.
> Prioritize album artist in cover search and manager

- src/ui/albumcovermanager.cpp
- src/ui/albumcovermanager.h
Replace pointer with reference. Avoid calling `toString()` twice.
> Refactor AlbumCoverManager::EffectiveAlbumArtistName()

- src/ui/albumcoverchoicecontroller.cpp
- src/ui/albumcovermanager.cpp
Starting from 82f0d261fa8039af4d90761abc2384bdcb74af96, we started searching covers using the tuple `(effective_albumartist, effective_album)`. That tuple was also used to save the image in cache, but that is not consistent with the rest of the code.
In order to not introduce more changes than necessary, we keep using the previous convention of caching images with the tuple `(artist, album)`.
> Roll back to the cache naming conventions for covers

- src/core/song.cpp
Using artist and album as a means for comparing and hashing albums will lead to situations where an track on the same album but having different artist fields (most commonly occurring on songs with features) will not register as being part of the same album
> Uses effective fields for album hashing and comparison

- src/analyzers/analyzerbase.cpp
- src/analyzers/analyzerbase.h
- src/analyzers/baranalyzer.cpp
- src/analyzers/blockanalyzer.cpp
- src/analyzers/blockanalyzer.h
- src/analyzers/boomanalyzer.cpp
- src/analyzers/fht.cpp
- src/analyzers/fht.h
- src/analyzers/rainbowanalyzer.cpp
- src/analyzers/sonogram.cpp
- src/analyzers/turbine.cpp
These changes make the oldish `FHT` class code to use newer, safer structures. 
This avoids a potential buffer overrun [here](https://github.com/clementine-player/Clementine/compare/master...santigl:fht-refactor?expand=1#diff-1b0025c3a227af0f536329d279c4a2eeL92), where the `scope` size can be smaller than `fht_->size()`.
Because the code is too "convoluted" I didn't modify the algorithms, so pointers are still being passed as arguments.
Along modifications to the different analyzers to adopt those changes I made a few refactorings in their code as well, improving readability and making vector members use the `QVector` type everywhere it was possible.
> Refactor FHT class (fixes buffer overrun)

- src/playlist/playlistmanager.cpp
- src/playlist/playlistmanager.h
This fixes the bug described in #5460 for Windows and also avoids the same problem in other systems (for example: Unix-based ones and forward slashes).
> Remove non-allowed characters in playlist filename when saving

- src/core/metatypes.cpp
This fixes the following warnings that were shown multiple times during exit:
> DEBUG WorkerPool<HandlerType>:176      Closing worker socket 
WARN  unknown                          QObject::connect: Cannot queue arguments of type '**QAbstractSocket::SocketState**' 
WARN  unknown                          **(Make sure 'QAbstractSocket::SocketState' is registered using qRegisterMetaType().)**
> Register QAbstractSocket::SocketState meta type

- src/analyzers/analyzerbase.cpp
- src/analyzers/blockanalyzer.cpp
- src/ui/albumcoverchoicecontroller.cpp
> QColor::fromRgb: RGB parameters out of range 
> Couldn't load icon "find"
> QPainter::begin: Paint device returned engine == 0, type: 2
> Fix some warnings shown on start-up

- src/internet/spotify/spotifyservice.cpp
- src/internet/spotify/spotifyservice.h
My development team for a Software Engineering class discovered that Clementine crashes when searching in Spotify under the Internet tab. A bug report specifying the details of the issue can be found [`here`](https://github.com/Team-NullPointer/Clementine/issues/12). We realized it was a null pointer issue in spotifyservice.cpp, and the bug was fixed with the commits below (in this fix, the search_ pointer was initialized, as previously it was not). I hope you consider including this fix to prevent Clementine from crashing when searching under the Internet tab for Spotify songs. Thank you.
> Request to merge a fix for a crash during searching under Internet Tab

- src/ui/mainwindow.cpp
Hello, my team for a Software Development class has figured out a possible fix to issue #5550. It seems that there has been a possible overlap of key functions between [mainwindow.cpp](https://github.com/clementine-player/Clementine/blob/c7b8aacad8179ea2a7fe3857833a8c01c70104da/src/ui/mainwindow.cpp#L2859-L2864) and [playlistview.cpp](https://github.com/clementine-player/Clementine/blob/e5ab3e786f9adde12cec3cc90cfe8c1cc6b06320/src/playlist/playlistview.cpp#L621-L626). By getting rid of the left and right key functions in mainwindow.cpp, the left, right, and down keys are now used solely for browsing through the library hierarchy when the library is in focus; when the playlist is in focus, the left and right keys properly seek, and the up key starts the song over from the beginning as …
> Request to merge a fix to "Seek instead of navigation with arrow keys #5550".

- src/analyzers/analyzerbase.cpp
6c9bc43bbb0b23a1fd8801e2075cef44cc3aae8b broke psychedelic mode because somehow a `QList.reserve()` turned into a `QVector.resize()` which are definitely not equivalent.
There were also bounds added to stop the code spewing errors because of this, but they are not needed now since it's not broken anymore.
> Fix psychedelic mode on analysers

- src/core/player.cpp
Hello, our team again as been able to find a possible solution to a bug, this time to issue #793. By adding this call into the if statement, this allows a reshuffle to happen after the playlist ends so that when the playlist starts again, it will already have a new set location to go to. In order to make sure this did not create any additional bugs, a few checks were made:
- Turning off shuffle album mode to make sure that songs were not starting at random points in the playlist.
- Playlist works with one song (Playlist will end, and song will play again)
- Playlist works with two songs (Playlist will end, and will start with the other song that wasn't played.)
I hope you will consider this into Clementine, thank you for your time.
> This fixes "First track always the same in shuffle #793".

- src/internet/soundcloud/soundcloudservice.cpp
SoundCloud search limit it set to 100. Pagination may be added soon. (see SoundCloud HTTP api: https://developers.soundcloud.com/docs/api/guide#pagination)
> SoundCloud service simple search limit is set. (Issue: #5529)

- src/playlist/playlistcontainer.cpp
- src/playlist/playlistview.cpp
Continuation of "Seek instead of navigation with arrow keys" #5550, now allows up arrow key to soley be used in browing the library's folder hierarchy, instead of restarting the song over when the library is in focus. Works as usual when playlist is in focus (song gets started over).
> Continuation of "Seek instead of navigation with arrow keys" #5550, now allows up arrow key.

- src/core/globalshortcuts.cpp
- src/core/globalshortcuts.h
- src/playlist/playlistmanager.cpp
- src/playlist/playlistmanager.h
- src/ui/mainwindow.cpp
The title says it. It's a new shortcut (no default set) for removing the current playing song from the playlist.
Usage:
Clementine runs in the background, a horrible song starts playing - oh no! never want to hear it again -, you press *your favourite shortcut* to remove it from the playlist and *your second favourite shortcut* to start the next() song.
> New shortcut: remove current playing song from playlist

- data/lyrics/ultimate_providers.xml
Some time ago lyrics.wikia seemed to update their website, so the lyrics were getting a lot of extra data in them, such as links to itunes, amazon, etc. This commit fixes the parsing to just take the lyrics.
Before:
After:
> Update lyrics.wikia parsing

- src/smartplaylists/querysearchpage.ui
The outmost QWidget had vsizetype="Fixed", changed that to "Preferred" made the
preview window take up a small amount of resize. This made it possible to resize
the window a little at least.
There should be opportunity for more flexibility here by allowing the searchterm scrollbox to resize. But I don't know enough of QT to figure out how to do that.
In some small manner this addresses #3892.
> Make the initial SmartPlaylistQuerySearchPage vertically resizeable

- src/core/commandlineoptions.cpp
American english "percent" used for reasons it is used elsewhere.
If brevity is the aim, "Lower volume 4%" and "Add 4% volume" would do.
> Spelling: "%" → "percent" for consistency

- src/ui/equalizer.cpp
https://en.wikipedia.org/wiki/Hip_hop Though inconsistent, this never uses "HipHop". While that could be perceived as the name of the equalizer, "Hip Hop" is at least consistent with the other EQs.
> Spelling: Hip Hop

- src/playlist/playlistview.cpp
With some iconsets (like Papirus for example) `availableSizes().last()` returns gigantic icons making playlist look like this:
This small patch fixes the problem.
> Fix oversized currenttrack icon in playlistview

- src/covers/currentartloader.cpp
No more black background in MPRIS clients. Maybe there's more elegant way to to this check?
> Prevent thumbnailing nocover icon for MPRIS

- src/core/player.cpp
- src/ui/behavioursettingspage.cpp
- src/ui/behavioursettingspage.ui
The checkbox is in General->Behavior. It is unchecked by default.
When checked, Clementine will not try to play the next song whenever it fails to play a song. This is useful for users like me who have their music library on a Windows or linux share, or on the internet which means sometimes the library is down and I cannot access it. When this happens, Clementine will try to play all the songs in my huge library while spamming error messages. The only way to stop it is to close the program.
> Add settings option to stop playback if song fails to play (Don't play next song)

- src/engines/gstengine.cpp
When the network connection changes while playing an HTTP stream, I always get the "Server does not support seeking." error from GStreamer.
It seems like GStreamer tries to seek on reconnect, which fails, an propagates the error to Clementine which in turn ceases playback with
the error message handed through from GStreamer, even though there is now a perfectly fine network connection again.
An easy way to reproduce this is switching from a wired to a wireless connection or the other way round.
As a workaround, try to reload the stream when this error occurs.
I'm not sure if this is the correct way to handle this problem, but as I'm experiencing this problem quite frequently (I seem to have a rather flaky connection here) it's very annoying so I was looking for quick hack to fix it.
> Attempt to reload stream on "Server does not support seeking." error

- src/core/utilities.cpp
Always show the number of hours in the playlist summary text for playlists exceeding 1 day even if  the hour happens to be zero.
Before:
After:
> Always include the hours in the playlist summary text for long playlists

- src/ui/mainwindow.cpp
When the playlist double-click behavior is set to add songs to the queue, the playback of the queue also starts if no song is currently playing. To play the queue from the current playlist, we must set the active playlist to the current one before starting the playback.
Fixes #5714.
> Ensure that the correct playlist is played

- src/networkremote/networkremote.cpp
fixed issue #5868: IPs were not recognized as private when Qt translates ipv4 to ipv6
As a result, the Network Remote would disconnect whenever the option to "Only allow connections from the local network" was selected.
Added translated IPs to NetworkRemote::IpIsPrivate
> fixed issue #5868: IpIsPrivate returns false when IPv4 are translated to IPv6

- src/internet/podcasts/podcastparser.cpp
If the type attribute is missing from the enclosure element, we should try looking at the URL to see if it is an audio file.
> Add additional check when enclosure type is missing

- src/playlist/playlistcontainer.cpp
- src/playlist/playlistcontainer.h
- src/ui/appearancesettingspage.cpp
- src/ui/appearancesettingspage.ui
- src/ui/mainwindow.cpp
Gives the user the option of a cleaner looking interface if the filter toolbar isn't used.
I've tried to follow existing coding style to the best of my knowledge.
PS: This is my first ever pull request so be kind :)
> Add appearance option to hide playlist filter toolbar

- CMakeLists.txt
Fixes https://github.com/clementine-player/Clementine/issues/5945
> Drop obsolete Qt5WebKit dep from CMakeLists.txt

- src/ui/mainwindow.cpp
- src/widgets/fancytabwidget.cpp
- src/widgets/fancytabwidget.h
This is a rewrite of the sidebar widget. The old sidebar widget was written by Nokia 10 years ago and was a hand made hardcoded mess of widgets trying to emulate a QTabWidget. 
This commit completely replaces it with a widget of the same name (FancyTabWidget) but is a much simpler subclass of the standard QTabWidget allowing for a 50% code reduction.
There is still some manual draw code copied over to get the exact same look of the previous widget but this is not strictly necessary and can be later refactored with simpler drawControl code based on styling preferences or if a pixel perfect match of the Nokia version is not necessary.
Benefits:
- Easier to maintain (50% code reduction)
- Easier to understand (standard QTabWidget mechanics)
- Built-in support for re-arranging and closing …
> Replace Nokia based FancyTabWidget with standard QTabWidget

- src/playlist/playlistlistcontainer.cpp
- src/playlist/playlistlistcontainer.h
- src/playlist/playlistlistcontainer.ui
- src/playlist/playlistlistmodel.cpp
- src/playlist/playlistlistmodel.h
This allows power users who keep 100s of playlists to easily find a playlist either by searching for directory name, playlist name or a song artist/title a playlist might contain
This commit also adds track "$artist - $title" items to each playlist tree node
> Add search filter to playlist list page

- src/smartplaylists/searchterm.cpp
- src/smartplaylists/searchterm.h
- src/smartplaylists/searchtermwidget.cpp
- src/smartplaylists/searchtermwidget.ui
This adds two new operators "empty" and "not empty" to the smart playlist search terms, fixing #2617.
Disclaimer: I am completely inexperienced with regards to native app development and Qt. I have basic knowledge of C++.
A few notes:
- This pull request does not address the culprit that search terms cannot be empty. In general, it should be allowed to use empty value to create queries like *Album equals `$EMPTYSTRING`*. However, some internal logic depends on the behavior of considering empty fields as empty. In particular, starting the smart playlist dialog will crash if empty search terms are considered valid (i.e. changing [this line](https://github.com/clementine-player/Clementine/blob/e5ab3e786f9adde12cec3cc90cfe8c1cc6b06320/src/smartplaylists/searchterm.cpp#L146) to `return true;`) …
> Smart Playlists: Add empty/not empty operators

- src/smartplaylists/searchtermwidget.cpp
This pull request resolves the requirement that operators in `SearchTermWidget` stay in the same order for the functionality to work.
Currently, the logic checks for *position inside of a combobox* instead of checking for the actual operator that should be targetted.
> Determine operator enum instead of comparing with magic numbers

- ext/clementine-spotifyblob/main.cpp
- src/main.cpp
Renaming the application does not really make sense, but keeping it in qLog info to identify it in debug output.
> Remove "-qt5" suffix from ApplicationName and OrganizationName

- src/widgets/tracksliderpopup.cpp
- src/widgets/tracksliderpopup.h
- src/widgets/tracksliderslider.cpp
- src/widgets/tracksliderslider.h
The previous behavior exited on leaving TrackSliderSlider, which causes the popup to flicker, as it is shown and hidden rapidly, at least for me (on Debian unstable).
> Hide TrackSliderPopup on exit from popup instead of from TrackSliderSlider

- src/widgets/tracksliderslider.cpp
The previous fix introduces a regression on some platforms which did not generate a leaveEvent when the TrackSliderPopup was displayed. The previous fix is reverted and logic is introduced to identify bonafide mouse motion out of the TrackSliderSlider.
Sorry about the noise on this. I only have two systems to check this on, but since this patch is much simpler than my first one, I expect it is less likely to cause a regression.
> Hide TrackSliderPopup on appropriate leaveEvent

- src/covers/amazoncoverprovider.cpp
Fix bug where the http request is not sending anything else than the signature.
The associate key currently in the code is not working for me, but maybe it's specific to my IP region or the key has been banned by amazon, however the code now works if I replace it with my own key.
"<?xml version=\"1.0\"?>\n<ItemSearchErrorResponse xmlns=\"http://ecs.amazonaws.com/doc/2009-11-01/\"><Error><Code>AWS.InvalidAssociate</Code><Message>Your AKIAIQH26RVM6UZ4WA6Q is not registered as an Amazon Associate. Please register as an associate at https://affiliate-program.amazon.com/assoc_credentials/home.</Message></Error><RequestID>31069391-03f4-427e-8521-95c16fd9690c</RequestID></ItemSearchErrorResponse>"
> Fix bug in fetching album covers from Amazon

- src/library/librarybackend.cpp
- src/ui/albumcovermanager.cpp
After fetching covers in covermanager, it does not sucessfully update art_manual in the DB because it is trying to update using albumartist instead of artist, even if the string is empty. You can see this if you go in cover manager and fetch missing covers, close it and go back, they still have nocover.
> Fix bug in covermanager not saving album cover to DB.

- src/devices/cddasongloader.cpp
- src/engines/gstenginepipeline.cpp
QUrl() does not accept a single number as the host, it translates it to 0.0.0.1.
This is a simple workaround instead of replacing QUrl with QString or QVariant.
The first commit fixes it by adding a single character after the tracknumber, ie: cdda://1a for track number one. This URL will still work with gstreamer and can be played. The second commit removes the added "a" from the URL, just in case it would break in another version of gstreamer.
> Workaround for broken CD playback in Qt5

- src/internet/digitally/digitallyimportedclient.cpp
Clementine no longer loads channels list from DI.FM services. The issue is caused by obsolete api.v2.audioaddict.com domain usage. api.audioaddict.com should be used instead.
> Fix channels loading for DI.fm services after API domain changes

- src/ui/mainwindow.cpp
There's no difference between close() and hide() if WA_DeleteOnClose is not set, so if we're going to hide the window we might as well accept the event.
Ignoring the event may interrupt shutdowns since it signals that the application doesn't want to close the window, at least this happens on Plasma 5.11 when Clementine is not minimized to tray.
> Accept closeEvent() for mainwindow when closing to tray

- src/core/mimedata.h
- src/library/libraryview.cpp
- src/library/libraryview.h
- src/playlist/playlist.cpp
- src/playlist/playlist.h
- src/playlist/playlistundocommands.cpp
- src/playlist/playlistundocommands.h
- src/playlist/queue.cpp
- src/playlist/queue.h
- src/playlist/songloaderinserter.cpp
- src/playlist/songloaderinserter.h
- src/smartplaylists/generatorinserter.cpp
- src/smartplaylists/generatorinserter.h
- src/ui/mainwindow.cpp
- src/ui/mainwindow.h
Adds a feature similar to what is seen in other music apps like Google Play Music, where you can select one or more songs from either the library or playlist and insert them at the top of the queue to be played immediately after the current track ends.
> Add Play Next Option to Queue

- 3rdparty/qtiocompressor/CMakeLists.txt
- 3rdparty/qtsingleapplication/CMakeLists.txt
- 3rdparty/qxt/CMakeLists.txt
- ext/libclementine-common/CMakeLists.txt
- gst/moodbar/CMakeLists.txt
- tests/CMakeLists.txt
One usage of the macro remains in the bundled libmygpo-qt5. This should
be updated once the pending upstream fix was merged. qtsingleapplication
is already fixed upstream.
> Fix cmake with Qt 5.11_beta3 (dropping qt5_use_modules)

- src/playlist/playlistcontainer.cpp
- src/playlist/playlistview.cpp
- src/playlist/playlistview.h
- src/ui/mainwindow.cpp
- src/ui/mainwindow.h
Any access, read or write, via QSettings requires locking `Clementine.conf`. On some devices, this can be slow. Moreover, it also increases power use and wear on devices such as SSDs.
To improve the situation, defer QSettings updates until program close for window resize, current playlist tab, and playlist geometry, i.e. `PlaylistView::SaveGeometry`.
Also, limit `PlaylistView::LoadGeometry` to once per program run.
I'm running this on my machine right now. Before, trying to just hold down Control-Tab caused Clementine's display to hang with very high disk IO. Now it moves smoothly. Similarly, resizing the window is now smooth, whereas before it hung similarly.
> Limit both QSettings reads and writes

- src/widgets/stretchheaderview.cpp
`column_widths_` is managed elsewhere. Resetting it on model change makes tab-switching slow, and---if a vertical scroll bar becomes visible or hidden---can be triggered in unexpected situations, leading to
visible column information loss.
I'm running this. New playlists create fine, changing tabs works fine (and its fast with "Stretch columns to fit window"). A fresh install seems to work fine, too.
> Do not reset column_widths_ on model change

- src/engines/gstengine.cpp
- src/engines/gstenginepipeline.cpp
Let's the user see the error message what failed instead of Clementine crashing.
Also don't do gst_object_unref unless bin is set.
This fixes GStreamer-CRITICAL gst_object_unref: assertion 'object != NULL' failed
Fixes #5753
> Fix crash when uridecodebin fails.

- src/engines/gstenginepipeline.cpp
Setting device on windows is currently broken, possible because of newer version of gstreamer.
This is tested on Windows 10 with gstreamer 1.14.0
Also tested on Qt5 branch.
> Fix setting device on windows

- src/networkremote/incomingdataparser.cpp
- src/networkremote/incomingdataparser.h
- src/playlist/playlistmanager.cpp
- src/playlist/playlistmanager.h
Currently, clicking on songs in playlists via remote control will result in direct playback. With this changes, the behavioral settings are taken into account. Therefore, the selected song will either be played directly or added to Queue, depending on user setup (using parameter "doubleclick_playlist_addmode"). For reading parameters, a ReloadSettings() hook has been added, too.
This makes the remote control app behave more like the local GUI without changing anything within the remote protocol. Unfortunately, it is currently not possible to display the queued elements within the remote app without changing the protocol.
> Song selection via remote app respecting behavioral settings

- src/engines/gstengine.cpp
- src/ui/playbacksettingspage.cpp
Currently there is a bug in the Playback Settings. It does successfully save the selected value for output device when you close the settings, but it does not load it if it is set to a plain sink without a device.
This is because in PlaybackSettingsPage::Load() it's comparing a invalid QVariant value to a the loaded device which is a empty string (details.device_property_value == device) which does not match.
- Load device setting as a QVariant instead of a QString.
- Set empty string for sinks with default devices and auto sink (optional)
The output device setting is now loaded. Tested on Linux. Also tested on the Qt 5 branch. On Windows this was not broken before, since there are no sinks without devices, but I've also tested to cross build and run on windows just to make sure it still …
> Fix loading output/device setting in Playback Settings

- ext/libclementine-remote/remotecontrolmessages.proto
- ext/libclementine-tagreader/CMakeLists.txt
- ext/libclementine-tagreader/gmereader.cpp
- ext/libclementine-tagreader/gmereader.h
- ext/libclementine-tagreader/tagreader.cpp
- ext/libclementine-tagreader/tagreadermessages.proto
- src/core/song.cpp
- src/core/song.h
- src/widgets/fileview.cpp
Solving issue #5866 and in progress of #2284 , I've added playback of SPC (SNES emulated) music files and also support reading tag data from the SPC ID6 format.  
The SPC format is an emulated SNES song format that is supported by GStreamer, so much of the complicated backend work was already completed. For the time being, since TagLib does not recognize SPC's internal tagging format, the reading of tagging information is handled in a GMEReader namespace added to libclementine-tagreader. In order to maintain parity with other playback systems (such as foobar and winamp), additional tagging information is sometimes stored within an ApeTag suffix to the SPC file data.
The code has been documented wherever necessary, and the groundwork for adding more game song emulation formats has been …
> Implemented SPC File Playback and Tag Reading Functionality

- dist/format.py
- src/core/player.h
- src/playlist/queue.cpp
- src/playlist/queue.h
- src/playlist/queuemanager.cpp
- src/playlist/queuemanager.ui
- src/ui/albumcoverchoicecontroller.cpp
- src/ui/albumcoverchoicecontroller.h
- src/widgets/nowplayingwidget.cpp
Queue is now calculating duration which is displayed in queue manger. Closes #6056.
Also closes #6075 by now toggling cover popup if accessed by current playing widget (accidentally committed on master instead of branch)
>  Queue size and duration is now displayed in queue manager && Album Cover Popup fixes

- src/engines/gstenginepipeline.cpp
- src/engines/osxdevicefinder.cpp
- Fix setting device on newer MacOs where the property value is longlong.
- Some devices (ie one my USB Arcam DAC's) return an empty description, set this to "Unknown device" so it's possible to select it.
> Device fixes for MacOs

- ext/libclementine-tagreader/gmereader.cpp
This will fix compile errors on older versions of gcc.
> Resolve an ambiguous function call

- src/engines/gstenginepipeline.cpp
This fixes https://github.com/clementine-player/Clementine/issues/4189 and https://github.com/clementine-player/Clementine/issues/6062 on at least Linux systems with PulseAudio. I do not have Windows/MacOS to test on.
When switching between tracks with different sample rates, the probe queue blocks before the pipeline can emit EOS. This prevents the track change from proceeding without manual intervention. This appears to be because the queue element doesn't handle the rate change correctly (either due to buffer length, or cap negotiation). The queue2 element however does handle this properly without blocking indefinitely.
The previous workaround for these issues was to force the sample rate for the entire pipeline to a fixed value in the settings so that a rate change never occurred.
> Fix track change hang

- ext/libclementine-tagreader/gmereader.cpp
Methods QString::fromAscii and QString::toAscii have been deprecated in Qt 5 (https://doc.qt.io/qt-5/qstring-obsolete.html).
This commit replaces calls to QString::fromAscii by calls to QString::fromLatin1 and calls to QString::toAscii by calls to QString::toLatin1.
This allows successful build when merging branch master into branch qt5.
> Use QString fromLatin1 instead of fromAscii

- src/playlist/playlistview.cpp
- src/ui/mainwindow.cpp
- src/widgets/tracksliderslider.cpp
- Disabling playlist row glow by default
- Track slider popup visible by default, add hide()
to ensure not visible by default (no more repaints)
- Set kTrackSliderUpdateTimeMs to 500. IMO 40 is too low
This should partially fix issue #1079
> Reduce some CPU load by disabling/fixing some UI stuff

- src/engines/gstenginepipeline.cpp
Addressing #6125 -- This fixes an issue with SPC playback where tracks would not properly register end-of-stream (TrackEnded, specifically) notifications when a new track begins due to a SourceDrained event. This caused tracks to play twice and not update the "current playing track" status in a given playlist. 
This was fixed by adding an extra condition to the "emit_track_ended_on_time_discontinuity_" stem where we now also check if a GST Buffer type is not valid (since the return of GST_Buffer_Offset will always return maximum size, giving garbage data back.)
> SPC Playback Correction - Prevent Duplicate Playback

- src/core/song.cpp
- src/core/song.h
- src/library/libraryquery.cpp
- src/library/libraryquery.h
Addressing #338 -- This adds the ability to use numeric columns (fields) with different operators (`<`, `<=`, `=`, `>=`, `>`) in the library search queries.
In that issue there are still some features requested which are not covered yet by this pull request like `added:3d` to find songs added less than 3 days ago.
> More columns for use in library search queries

- src/core/song.cpp
- src/core/song.h
- src/library/libraryfilterwidget.cpp
- src/library/libraryfilterwidget.ui
- src/library/libraryquery.cpp
Maybe this can close #338. Adds search by date like `lastplayed:<1h` to find songs played in the last hour. Also shows usage in the tooltip.
I changed the tooltip text in `libraryfilterwidget.ui`, is this the correct way? Will this work correctly with translations?
Also, there were some other issues merged into #338 (namely #256, #2334, #2441). #2441 specifically requested the `OR` operator, but the issue was closed and merged into #338. Maybe #2441 should be reopened or I can open a similar issue.
> Date columns for use in library search queries.

- src/core/database.cpp
Original patch by Arfrever
This fixes https://github.com/clementine-player/Clementine/issues/5297
> core/database: configure fts3 tokenizer support

- src/ui/behavioursettingspage.cpp
- src/ui/behavioursettingspage.ui
* Make systray settings available only if there is a systray on the system
* Move other settings out of the startup group so they are still available
> Make systray settings available only if there is a systray on the system

- CMakeLists.txt
Explicitly set `OpenGL_GL_PREFERENCE` to `LEGACY` to silence cmake warnings for not setting
`CMP0072`.
Fixes #6156
> Set OpenGL_GL_PREFERENCE to LEGACY to silence warnings on cmake 3.11+

- src/playlist/playlist.cpp
- src/playlist/playlist.h
- src/ui/behavioursettingspage.cpp
- src/ui/behavioursettingspage.ui
This introduces new configuration options which allow you to ignore
prefixes while sorting the playlist on album, artist and titles.
Prefixes are configurable, default are "a" and "the".
Closes #6143
> Allow ignoring prefixes when sorting playlist

- src/analyzers/analyzerbase.cpp
- src/core/cachedlist.h
- src/core/song.cpp
- src/core/songloader.cpp
- src/covers/albumcoverfetchersearch.cpp
- src/covers/coversearchstatisticsdialog.cpp
- src/globalsearch/globalsearchsettingspage.cpp
- src/globalsearch/globalsearchview.cpp
- src/internet/digitally/digitallyimportedservicebase.cpp
- src/internet/lastfm/lastfmservice.cpp
- src/library/librarymodel.cpp
- src/musicbrainz/acoustidclient.cpp
- src/musicbrainz/musicbrainzclient.cpp
- src/playlist/playlist.cpp
- src/playlist/playlistview.cpp
- src/playlist/queue.cpp
- src/playlist/queuemanager.cpp
- src/playlistparsers/playlistparser.cpp
- src/ripper/ripcddialog.cpp
- src/songinfo/songinfoview.cpp
- src/transcoder/transcodedialog.cpp
- src/transcoder/transcoder.cpp
- src/ui/about.cpp
- src/ui/albumcovermanager.cpp
- src/ui/behavioursettingspage.cpp
- src/ui/mainwindow.cpp
- src/ui/networkremotesettingspage.cpp
- src/ui/organisedialog.cpp
- src/ui/organiseerrordialog.cpp
Qt5 has deprecated QtAlgorithms and recommends using the standard algorithms.
This patch converts all uses of Qt algorithms to the corresponding std:: function.
> Convert uses of QtAlgorithms to std:: algorithms

- src/playlist/playlist.cpp
- src/playlist/playlist.h
- src/playlist/playlistcontainer.cpp
- src/ui/behavioursettingspage.cpp
- src/ui/behavioursettingspage.ui
- src/ui/mainwindow.cpp
Also add a configurable option to increment the play count if song has played for a shorter duration (1 minute)
> Split last.fm scrobbling and play count calculation, closes #5771

- dist/CMakeLists.txt
According to the Appstream specifications, Appdata files must now be installed
in /usr/share/metainfo. /usr/share/appdata is a legacy path.
See: https://www.freedesktop.org/software/appstream/docs/sect-Metadata-Application.html
and: https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html
> Fix Appstream data installation target

- src/core/player.cpp
This fixes bug created by PR #5905
The stop was done in Player::NextItem(), but is never done if "Stop playback if song fails to play" is enabled.
> Add missing Player::Stop()

- src/widgets/fancytabwidget.cpp
- src/widgets/fancytabwidget.h
This fixes the following error on startup:
17:00:43.041 WARN  unknown                          Object::connect: No such signal Core::Internal::FancyTabWidget::CurrentChanged(int) 
17:00:43.041 WARN  unknown                          Object::connect:  (sender name:   'tabs') 
17:00:43.041 WARN  unknown                          Object::connect:  (receiver name: 'MainWindow')
> Fix missing signal

- src/CMakeLists.txt
- src/core/utilities.cpp
- src/core/utilities.h
- src/internet/podcasts/episodeinfowidget.cpp
- src/internet/podcasts/episodeinfowidget.h
- src/internet/podcasts/episodeinfowidget.ui
- src/internet/podcasts/podcastinfodialog.cpp
- src/internet/podcasts/podcastinfodialog.ui
- src/internet/podcasts/podcastservice.cpp
Add an EpisodeInfoWidget with title, author, duration, date, and description fields. Include this in the PodcastInfoDialog. If exactly one episode is selected, then show both the podcast and episode widgets and display the episode's URL. Otherwise, hide the episode widget and follow the existing behavior. Note that the desription field for the EpisodeInfoWidget uses the QLabel and does not currently download embedded images.
Add an always_show_hours option to the PrettyTime methods to include hours in formatting even if the field is zero. This is less ambiguious in some cases where duration is displayed.
> Display podcast episode information.

- src/core/macglobalshortcutbackend.mm
This PR fixes issue #6148 and the duplicates of those issues.
The crash seems to occur because `AXAPIEnabled()` is depreciated.
My fix tries to use `AXAPIEnabled()` which was depreciated in Mavericks `macOS 10.9` and falls back to `AXIsProcessTrustedWithOptions` if it fails.
There may be a safer way to implement this by detecting the OS version so if anyone's got any suggestions I'd appreciate it.
> Updated accessibility check logic to fix Mojave crash

- src/ui/mainwindow.cpp
- src/ui/mainwindow.h
This fixes a problem where SaveGeometry() gets called before settings like tab_mode is loaded, tab_mode gets saved as 0 and is reset before the setting is loaded.
It also fixes window positions not being saved on certain conditions.
> Fix saving geometry and fancytab settings

- src/playlist/playlistview.cpp
There is a bug on the Qt 5 branch only where it does not save the playlist columns.
Not sure how these connects got lost, but they are on the master branch.
> Fix saving playlist columns

- ext/libclementine-common/core/workerpool.h
- src/internet/spotify/spotifyservice.cpp
- src/ui/appearancesettingspage.cpp
Apparently Q_OS_MACOS does not exist in Qt 4.
> Replace Q_OS_MACOS with Q_OS_MAC

- src/core/songloader.cpp
- src/devices/cddasongloader.cpp
- src/devices/giolister.cpp
- src/devices/gpoddevice.cpp
- src/devices/gpodloader.cpp
GError messages contain non-ascii characters. This normally just produces some garbage when we use the default QString contructor that assumes ASCII for logging. However, when a message includes the right double quote, UTF-8 sequence 0xE2 0x80 0x9D, the final byte is OSC. VT100 expects a command sequence to follow and stops echoing output until it sees ST or BEL character, which may never come. Thus, the console output is halted.
This change uses QString::fromLocal8Bit instead of depending on the default constructor. About half of the sites in the codebase had already been converted.
One side effect is that log messages are quoted. There are additional options to control this, but those were only introduced in Qt 5.4.
> Fix encoding of GError messages when logging.

- 3rdparty/qocoa/CMakeLists.txt
- src/CMakeLists.txt
Commit 453270c broke building.
Because the link line does not include dbus or x11 if found.
Also, visualizations are optional and newer macOS don't have OpenGL so it shouldn't be forced to link.
> Fix Qt 5 build

- src/core/globalshortcuts.cpp
- src/core/gnomeglobalshortcutbackend.cpp
- src/core/gnomeglobalshortcutbackend.h
The GSD D-Bus backend is broken with newer versions of gnome-settings-daemon (GSD) because of this change done about a year ago.
See:
https://gitlab.gnome.org/GNOME/gnome-settings-daemon/commit/33d47e655606ac88ed7d529c1132e5be6299633b
This caused it to fallback to using X11 shortcuts using XGrabKey.
This change makes it use org.gnome.SettingsDaemon.MediaKeys instead, but will also fallback to trying
org.gnome.SettingsDaemon instead so that distros that use old packages like Debian will still work.
I've tested it on opensuse tumbleweed with Gnome 3, it uses up-to-date packages, the backend now registers, grabs shortcuts and opens the gnome shortcut settings.
Fixes #6204 , #5462 and #6191
> Fix global shortcuts using GSD D-Bus backend

- src/devices/gpoddevice.cpp
Fixes: "QThread: Destroyed while thread is still running" when unmounting a gpod device.
Also tested on the Qt 5 branch, with Qt 5 it crashed before without quitting the thread.
> Quit thread before deleting the loader

- src/devices/connecteddevice.cpp
- src/devices/connecteddevice.h
- src/devices/devicemanager.cpp
- src/devices/devicemanager.h
- src/devices/mtpdevice.cpp
- src/devices/mtpdevice.h
- src/devices/mtploader.cpp
- src/devices/mtploader.h
Currently, the failure to connect to an MTP device results in the UI displaying
an open device that appears empty. This change introduces a method
ConnectedDevice::ConnectAsync() that is expected to handle any connecting tasks
that could block asynchronously. Upon completion, this emits a ConnectFinished
signal that indicates success or failure. The row in the UI is only updated
after the successful response is received. Upon failure, DeviceManager will
clean up and the row in UI is left in the pre-connect state.
Currently, only the MtpDevice utilizes this mechanism. All other devices use a
default implementation that immediately reports success.
> Handle MTP connection failures more gracefully.

- src/CMakeLists.txt
- src/devices/connecteddevice.cpp
- src/devices/deviceinfo.cpp
- src/devices/deviceinfo.h
- src/devices/devicemanager.cpp
- src/devices/devicemanager.h
- src/devices/deviceproperties.cpp
- src/devices/deviceview.cpp
- src/devices/filesystemdevice.cpp
Devices is broken with Qt 5, songs are loaded, but does not appear in the view.
The reason is that QAbstractListModel is not suitable to use with a QTreeView, and it completely breaks with Qt 5 when used through the proxy model.
From: http://doc.qt.io/qt-5/qabstractlistmodel.html#details
_Since the model provides a more specialized interface than QAbstractItemModel, it is not suitable for use with tree views; you will need to subclass QAbstractItemModel if you want to provide a model for that purpose. If you need to use a number of list models to manage data, it may be more appropriate to subclass QAbstractTableModel instead._
This converts the model to a SimpleTreeModel (QAbstractItemModel) like the library.
I've tested the changes with both Qt 4 and Qt 5
Thanks to @paperbagcorner for …
> Convert devices manager(model) to QAbstractItemModel

- src/library/libraryfilterwidget.cpp
I suggest changing the default group by in the library to album artist, otherwise albums that use album artist will have songs spread all over the library when there are multiple artists on the album, which will confuse newcomers that don't know that they can change this behavior. It also makes more sense that songs that are on the same album appear under the same album.
> Change default group by in library to album artist

- src/devices/filesystemdevice.cpp
- src/library/library.cpp
- src/library/librarywatcher.cpp
When unmounting a device, the ConnectedDevice object is destroyed. The
FileSystemDevice destructor waits on its worker thread. If a scan is in
progress, this will block until completion.
There is an existing Stop method in the LibraryWatcher class that is intended to
stop long running operations. To fix, or at least significantly shorten this
hang, we'll call this before waiting for the thread to exit. Also add a
stop_requested check in the cover art scan.
In addition, add a call to Stop in the Library destructor, which has a similar
usage.
> Prevent UI hang during device scan.

- src/moodbar/moodbarpipeline.cpp
- src/moodbar/moodbarpipeline.h
As reported in issue 6302, playing a stream that causes gstreamer to error at
start can cause a crash. The problem occurs when the MoodbarPipeline receives a
pad-added signal after it has handled an error callback. In the error callback,
the builder_ is freed. In the pad-added handler (NewPadCallback), this object
is accessed.
This change adds a running_ flag that is set when the pipeline is started and
cleared on an error, end of stream, or object destruction. We check this flag at
the beginning of NewPadCallback. For sanity sake, we also check the builder_
pointer before dereferencing. Note that checking the state of the pipeline
wasn't an option since the pipeline is in the process of changing states during
the pad-added callback and gst_element_get_state wants to block during a state …
> Fix MoodbarPipeline crash on gstreamer error.

- src/engines/gstenginepipeline.cpp
If ReplaceDecodeBin fails from TransitionToNext, uridecodebin_ will not be
replaced with a new element. Since TransitionToNext does not check the return
value, it unknowingly deletes uridecodebin_.
> Fix potential use of streamer element after deletion.

- src/engines/gstenginepipeline.cpp
- src/engines/gstenginepipeline.h
In the case that an error occurs in ReplaceDecodeBin before the bin is added to
the pipeline, unreference the object to allow cleanup. This change also separates
CreateDecodeBinFromUrl from ReplaceDecodeBin, following the pattern of
CreateDecodeBinFromString.
> Free decoder bin if error occurs during setup.

- src/ui/playbacksettingspage.ui
QTimeLine duration must be greater than 0. If set to 0, a default of 1000ms will
be used. To avoid this, enforce a minimum of 1ms for pause and cross fade values
if those fades are enabled.
> Set non-zero minimum for fade times.

- src/core/songloader.cpp
- src/core/songloader.h
- src/playlist/songloaderinserter.cpp
Async song loading can fail without user feedback. This change adds return codes
to these async load functions. It will now produce an error dialog in simple
scenarios (test case is user selecting a file that is not readable). Other cases,
such as directories and playlists, aren't yet covered.
> Add error handling path for async song loading.

- src/main.cpp
In 2011, there was a bug that caused NVIDIA drivers to hang Clementine on shutdown. In 2012, only some drivers had the fix for this issue, but the list was becoming tedious to maintain.  Now, in 2019, we do not need to work around this bug. By reverting commit c2723008a22c5a4c4e307ba9a278fd2162ef6bdb we work around known bad drivers, but do not penalize all NVIDIA users for this ancient bug.
Merging this will close #6061 .
> Revert "Blacklist all NVidia drivers"

- src/musicbrainz/chromaprinter.cpp
Automatic tag fetching is broken as of at least gstreamer 1.5.90 and newer. With the official released gstreamer 1.6.0 this leaves the feature broken.
There is an incorrect call to gst_buffer_unref that causes an assertion in gstreamer followed by a crash.
My understanding is that gst_buffer_unref should only be done when gst_buffer_ref is called, see:
https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer/html/GstSample.html#gst-sample-get-buffer
This fix adds a missing gst_sample_unref which is enough to free the buffer too according to the documentation.
Fixes https://github.com/clementine-player/Clementine/issues/6333
> Fix gst_buffer_unref assertion with chromaprinter

- ext/libclementine-tagreader/tagreader.cpp
Some fixes to prevent the writing of zero values and also addressing the inability to clear some tag fields in the tag editor.
- Fix compilation and disc field zero-value checks
- Check year, track and statistics fields for zero-values
Fixes (or improves): #1835 #3711 #3528
> Fix a number of zero-value tag issues (New PR)

- src/widgets/osd_x11.cpp
With KDE Plasma 5.16+, all Clementine notifications sent via D-Bus are retained in the notification history applet if the user doesn't manually dismiss the notification before it times out. Plasma's notifications control module allows you to turn off notification history for specific applications (among other things), but Clementine doesn't appear as a configurable application, and manually adding Clementine to the list via config files has no effect on the notification behavior.
Comparing Clementine's D-Bus messages to Slack (which does support per-app notification settings in KDE), I discovered that Clementine is missing a [`desktop-entry`](https://developer.gnome.org/notification-spec/#hints) hint in the call to `org.freedesktop.Notifications.Notify`. Adding this hint to the messages …
> Support per-app notification settings in KDE Plasma 5.16

- src/ui/mainwindow.cpp
Fix #6111 by ignoring instead of accepting the main window's closeEvent.
This applies the fix qBittorrent used for this same issue (https://github.com/qbittorrent/qBittorrent/issues/9240) to clementine, so credit goes to those guys.
> Fix blank window when restoring from systray

- ext/libclementine-common/core/messagereply.h
The messagereply gets deleted too early, I tried different approaches to solving it including using invokeMethod with Qt::QueuedConnection on deleteLater() which had no affect, but found that simply moving the signal works.
It seem like the messagereply gets deleted in the main thread before the semaphore is released.
I've set up a small test program that does tags on files in a directory in a loop. Before this it always crashed, typically around something like 300 tagwrites. Now I'm testing 10.000 writes in a loop without any crash.
Fixes https://github.com/clementine-player/Clementine/issues/5777 and https://github.com/clementine-player/Clementine/issues/6317
> Fix crash in messagereply

- src/core/tagreaderclient.cpp
- src/ui/behavioursettingspage.cpp
- src/ui/behavioursettingspage.h
- src/ui/behavioursettingspage.ui
Previously, the number of processes spawned was always
QThread::idealThreadCount() (returning the number of logical CPU
cores). On new systems with many cores, however, this can result
in 12, 16, 24, or ... processes being spawned, which is a bit
excessive.
This establishes a new config variable,
'max_numprocs_tagclients' within the Settings group, in order
to limit the maximum number of tag client processes that get
spawned. It also adds a means of setting this via the Behavior
page in Settings. It can be set to any integer in the interval
[1, QThread::idealThreadCount()]; it defaults to the maximal value
so as to emulate the old behavior.
> Introduce limit for number of tag client processes.

- src/core/database.cpp
Credit goes to Jiri Slaby (SUSE) for pointing out the leak in Database::BackupFile()
> Fix memory leaks in database

- cmake/FindFFTW3.cmake
- data/lyrics/ultimate_providers.xml
- dist/cpplint.py
- dist/format.py
- ext/libclementine-remote/remotecontrolmessages.proto
- src/analyzers/analyzercontainer.cpp
- src/analyzers/blockanalyzer.cpp
- src/covers/albumcoverfetchersearch.cpp
- src/dbus/org.freedesktop.UDisks.Device.xml
- src/devices/udisks2lister.h
- src/engines/enginebase.h
- src/engines/gstenginepipeline.cpp
- src/internet/podcasts/podcastdownloader.cpp
- src/internet/podcasts/podcastupdater.cpp
- src/internet/seafile/seafileservice.h
- src/internet/subsonic/subsonicdynamicplaylist.cpp
- src/internet/subsonic/subsonicservice.cpp
- src/networkremote/incomingdataparser.cpp
- src/networkremote/networkremotehelper.cpp
- src/playlist/playlistmanager.cpp
- src/playlist/playlistview.cpp
- src/playlistparsers/parserbase.h
- src/songinfo/songinfobase.cpp
- src/ui/behavioursettingspage.ui
- src/ui/mainwindow.cpp
- src/widgets/osd.cpp
- tests/librarybackend_test.cpp
> Fix misc. source comment typos

- src/core/application.cpp
- src/core/application.h
- src/main.cpp
- src/playlist/playlistcontainer.cpp
- src/playlist/playlistcontainer.h
- src/playlist/playlistview.cpp
- src/playlist/playlistview.h
- src/ui/mainwindow.cpp
- src/ui/mainwindow.h
- src/widgets/fancytabwidget.cpp
- src/widgets/fancytabwidget.h
This patchset consists of two patches, representing the development timeline. The first patch introduces an efficient framework to periodically save modified settings, rather than doing so immediately. This is the convention for events that may happen many times per second (such as flipping through tabs or resizing a window) in, e.g., KDE (see `kxmlgui`'s `kmainwindow.cpp`).  Instead, the setting is marked as dirty, and a timer is set (to 1 second), and saved then. If the program is closed before then, the dirty data is also saved via an `aboutToQuit` signal connection.
By coordinating the saving, the number of write locks that are required can be reduced to a maximum of one per second, tremendously improving user experience on systems with slow locks, reducing power consumption, and …
> Periodically save settings

- src/engines/gstenginepipeline.cpp
Fixes #6320. 
Queue2 tends to hang up on pause, unable to start playing
again. Pipeline actually stays PLAYING with ASYNC state
change, so it becomes impossible to unpause the player
without stop or forward/backward seeks.
I've been testing this fix for over 3,5 months (synchronizing with origin/qt5 from time to time), and it has worked just as intended without any track hangs.
> Attempt to fix track unpause hang (revert "Attempt to fix track change hang")

- src/analyzers/analyzercontainer.cpp
- src/analyzers/analyzercontainer.h
- src/core/globalshortcuts.cpp
- src/core/globalshortcuts.h
- src/internet/icecast/icecastfilterwidget.cpp
- src/internet/icecast/icecastfilterwidget.h
- src/library/libraryfilterwidget.cpp
- src/library/libraryfilterwidget.h
- src/playlist/playlistheader.cpp
- src/playlist/playlistheader.h
- src/smartplaylists/wizard.cpp
- src/smartplaylists/wizard.h
- src/songinfo/songinfofetcher.cpp
- src/songinfo/songinfofetcher.h
- src/ui/mainwindow.cpp
- src/ui/organisedialog.cpp
- src/visualisations/visualisationcontainer.cpp
- src/visualisations/visualisationcontainer.h
- src/widgets/fancytabwidget.cpp
- src/widgets/fancytabwidget.h
- src/widgets/nowplayingwidget.cpp
- src/widgets/nowplayingwidget.h
QSignalMapper is deprecated. Since we use C++11 anyway it can be replaced with lambda expressions.
> Replace all uses of QSignalMapper with C++11 lambda expressions

- src/engines/gstenginepipeline.cpp
This fixes the track change hang as described in https://github.com/clementine-player/Clementine/pull/6103 which is the correct fix for the problem.
Additionally setting properties on the queue2 element so it does not cause pause to hang.
Default max-size-bytes for queue2 is 2097152, which is lower than 10485760 for queue. We also set it to unlimited on the main queue before the tee, which might be the main cause for the track change hang.
I also set max-size-buffers and max-size-time to unlimited since we set the limit on the queue element on the queue before the tee anyway.
I have tested to pause over night and it does not get stuck anymore.
Fixes #6408
Fixes #6358
Fixes #6320
Fixes #6289
Fixes #5556
Fixes #6062
Fixes #5501
Fixes #4748
Fixes #1679
> Switch to queue2 for probe queue and set properties

- src/library/librarymodel.cpp
This removes the album cover from pixmap cache when the song is removed from the model.
It fixes a bug where the album cover in the library is stuck to the old one when a new cover is fetched.
Also remove the entry from pending_art_ since it otherwise will contain a dangling pointer to the item.
> Remove album from pixmap cache when song is removed from library model

- src/library/librarywatcher.cpp
- src/library/librarywatcher.h
This fixes a bug where the library watcher is no longer updating the sub directory (album) after rename when the parent directory (artist) is renamed first.  Even though the new artist directory is updated to the songs, the new album directory is not.
It's because we are still watcher the old directory names.
Fixed by removing watches on the removed subdirectories of the library directory before watching the new directory names.
> Remove watch for removed subdirectories

- src/library/librarybackend.cpp
- src/library/librarybackend.h
Updating compilations does not handle cases where there are albums with the same name by different artists. If you have one album with the same effective album artist for all songs, and one album with various effective album artists, both of those albums will go into various artists when updating compilations for the compilation album.
This changes the logic to work on directory + album, instead of just album.
There is also a bug always setting sampler to true when updating the model, even though its updated correctly to the db:
https://github.com/clementine-player/Clementine/blob/master/src/library/librarybackend.cpp#L849
This fixes that too.
> Fix updating compilations

- ext/libclementine-tagreader/tagreader.cpp
Because the version is in hex, 0x051000 is not the same as Qt 5.10. So this code will never be used.
Even if it was, it won't compile because it's called birthTime() not birthtime().
Fixes #6423
> Fix setting mtime/btime in tagreader

- src/ui/edittagdialog.ui
Fixes a bug in the splitter of the edit tag dialog, when you open it, it only shows the left side of the splitter (files).
> Fix edit tag dialog

- src/CMakeLists.txt
- src/core/globalshortcuts.cpp
- src/core/globalshortcuts.h
- src/core/kglobalaccelglobalshortcutbackend.cpp
- src/core/kglobalaccelglobalshortcutbackend.h
- src/dbus/org.kde.KGlobalAccel.xml
- src/dbus/org.kde.kglobalaccel.Component.xml
This fixes #6469.
It seems to work for both a Wayland session and a X11 session on KDE Plasma 5.17.4 (on gentoo). However, the media keys behave a bit erratically probably because they are reserved by the Media Player plasmoid.
> Add KGlobalAccel global shortcuts backend

- src/core/utilities.cpp
- src/core/utilities.h
- src/library/librarymodel.cpp
- src/main.cpp
Fixes #6471 
This will honor the XDG_CONFIG_HOME and XDG_CACHE_HOME defined in XDG standard:
https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.6.html.
It uses Qt that already provided a facility to get configuration directories that support XDG:
https://doc.qt.io/qt-5/qstandardpaths.html#writableLocation
Additionally a workaround for macOS that was needed in 2011 has been removed since libimobiledevice doesn't need the workaround anymore.
> Support  for XDG_CONFIG_HOME and XDG_CACHE_HOME

- src/ui/mainwindow.cpp
- src/ui/mainwindow.h
Resuming the playback position on startup has not worked for a while. See issues like #6363 
The reason it did not work is because the song to be resumed does not have a length yet when the seek is requested. My solution is to add a slot that waits until the song has a length so that the seek will work.
> Fix resuming playback position on startup

- src/core/network.cpp
- src/core/network.h
- src/internet/podcasts/gpoddersync.cpp
- src/internet/podcasts/gpoddersync.h
Found this issue while I was playing with my own gpodder instance that wasn't behaving properly. A request that fails to return can cause GPodderSync be stuck in the flushing state.
The alternative to this would be to modify the libmygpo-qt to expose the QNetworkReply instance and use the NetworkTimeouts class in the same manner that it's used elsewhere.
> Add timeouts for gpodder requests.

- src/internet/podcasts/gpoddersync.cpp
- src/internet/podcasts/gpoddersync.h
A closure created by NewClosure that handles Qt signals is destroyed if the
signal object is destroyed, the slot object is destroyed, or the signal is
invoked. In the case where the sender is passed as a shared pointer, the
reference prevents the sender from being destroyed before the closure.
So for closures built to handle responses returned from ApiRequest in
GPodderSync, the closure object and the response object will only be destroyed
after the signal is invoked. In some cases, separate closures are built for
error signals as well. For these, only one closure will be destroyed. The other
closures and the response object will be leaked.
A simple fix for the success cases is to remove the unnecessary error case
closures and directly connect the signals to slots. This is low hanging …
> Fix gpodder sync memory leaks in success cases.

- src/internet/podcasts/gpoddersync.cpp
A sessionid cookie is stored when logging in to gpodder. After logging out, a
subsequent login with the same user name but incorrect password will succeed,
ignoring the authorization header. The incorrect password will be stored for
future use.
To fix this, reset the cookie jar for GPodderSync's network access manager at
logout.
> Reset gpodder session cookies on logout.

- src/internet/podcasts/gpoddersync.cpp
- src/internet/podcasts/gpoddersync.h
- src/internet/podcasts/podcastsettingspage.cpp
- src/internet/podcasts/podcastsettingspage.h
It's not necessary for the PodcastSettingsPage class to have knowledge of
GPodderSync's login implementation. Handling the network reply in a single
location sightly simplifies the code. It also makes the handling order
more deterministic.
> Gpodder login cleanup.

- src/playlist/playlistview.cpp
- src/playlist/playlistview.h
- src/smartplaylists/wizard.cpp
This is a fix for https://github.com/clementine-player/Clementine/issues/6434
Another option would be to use a static instance of PlaylistProxyStyle that we create the first time a PlaylistView is instanciated, but I think that makes some assumptions about lifetimes of QStyle objects that might cause pain in the future.
It's also possible that the bug sited in c83394b6b4 no longer exists.
> Fix smartplaylist crash

- src/core/macfslistener.h
- src/core/macfslistener.mm
The library watcher is broken on macOS because the QTimer doesn't start. Because it's allocated on the stack, the object isn't moved to the correct thread. Fixed by allocating on the heap.
This fixes the following errors logged:
```
__logging_message__08:33:22.414 WARN  unknown                          QObject::startTimer: Timers cannot be started from another thread
__logging_message__08:33:22.414 WARN  unknown                          QObject::killTimer: Timers cannot be stopped from another thread
__logging_message__08:33:22.414 WARN  unknown                          QObject::startTimer: Timers cannot be started from another thread
```
> Fix macOS filesystem listener (library watcher)

- src/library/librarymodel.cpp
My previous fix had a bug, it worked for removing pixmap cache itself, but not the pending art: The following line `if (i.value().first == node) {` should have been `if (i.value().first == node->parent) {`
But it's actually better to just remove it when removing the parent nodes since the album is always the parent anyway.
> Remove pixmap cache and pending art when removing parent nodes instead

- src/library/librarybackend.cpp
All songs that belong to a compilation album where a song is updated needs to be removed and readded to the model, otherwise they all still have the various artists compilation node.
This fixes a bug where the songs are stuck in various artists, even though it's correctly updated to the DB, the model isn't updated immediately.
> Fix songs stuck in various artists

- src/ui/albumcoverchoicecontroller.cpp
- src/ui/notificationssettingspage.cpp
- src/ui/settingsdialog.cpp
- src/widgets/nowplayingwidget.cpp
- src/widgets/osdpretty.cpp
- src/widgets/osdpretty.h
- src/widgets/prettyimage.cpp
QDesktopWidget is deprecated. This replaces all uses of it with QScreen.
OSDPretty will use screen name instead of display number in the settings.
> Replace all uses of QDesktopWidget with QScreen

- src/widgets/ratingwidget.cpp
QStyleOptionFrameV3 is Qt 4 specific and the same as QStyleOptionFrame in Qt 5.
> Replace use of QStyleOptionFrameV3

- src/core/utilities.cpp
- src/devices/macdevicelister.mm
- src/ui/playbacksettingspage.cpp
- src/widgets/stylehelper.cpp
QString::sprintf is obsolete and QString::asprintf is available since Qt 5.5 and should be used instead.
See https://doc.qt.io/qt-5/qstring-obsolete.html#sprintf
> Replace use of QString::sprintf with QString::asprintf

- src/smartplaylists/searchtermwidget.ui
Fixes the following:
`searchtermwidget.ui: Warning: The name 'verticalLayout_2' (QVBoxLayout) is already in use, defaulting to 'verticalLayout_21'.`
> Fix layouts with duplicate name in SmartPlaylistSearchTermWidget

- src/internet/podcasts/gpoddersync.cpp
- src/internet/podcasts/gpoddersync.h
- src/internet/podcasts/podcastsettingspage.cpp
- src/internet/podcasts/podcastsettingspage.h
- src/internet/podcasts/podcastsettingspage.ui
Add an "Advanced Settings" option to the gpodder sign in. If selected, a fully
qualified URL must be specified as the gpodder base. Upon successful login, the
URL is saved along with username and password. If advanced settings are not
selected, an empty URL is stored and the default will be used.
> Add an option to specify a gpodder server.

- src/musicbrainz/chromaprinter.cpp
Use of QTime::start - elapsed is deprecated in Qt 5.14 and QElapsedTimer does the same.
> Replace QTime with QElapsedTimer

- src/globalsearch/globalsearchmodel.cpp
- src/internet/core/internetmodel.cpp
- src/internet/podcasts/podcastservice.cpp
- src/internet/podcasts/podcastservicemodel.cpp
- src/playlist/playlistlistcontainer.cpp
QModelIndex::child() is obsolete. See: https://doc.qt.io/qt-5/qmodelindex-obsolete.html
> Replace QModelIndex::child() with QAbstractItemModel::index()

- src/ui/mainwindow.cpp
Message contains no context and appears to be a remnant of a debug session.
> Remove unhelpful debug message.

- src/core/player.cpp
- src/internet/core/scrobbler.h
- src/internet/lastfm/lastfmservice.cpp
- src/internet/lastfm/lastfmservice.h
- src/ui/mainwindow.cpp
- src/ui/mainwindow.h
Fixed lastfm workflow with "now playing" and scrobbling feature(Maybe Issue #2672). After scrobble request song was displayed on "just listened" and "listening now", that was wrong. Now listeting request sends after starting song. Scrobble works through cache. Cache send tracks on stop, next, prev, change song events. I think that it is correct algorithm for scrobbling. 
I have a couple ideas to improve working with lastfm. I'll try realize them later.
Changed logic of love track action and fix Issue #3515.
I'll be glad to find my code in my favorite player source code.
Thanks.
> Fixed lastfm scrobbling workflow.

- src/devices/mtpdevice.cpp
A commit in qt 5.7 changes a qWarning to a qFatal if a QThread is still running
when it's deleted. When we get the LoadFinished signal in MtpDevice, stop
the loader thread's event loop to avoid this situation.
See qtbase commit c8277b6e532
> Fix abort from Mtp loader thread.

- src/devices/devicemanager.cpp
- src/devices/devicemanager.h
- src/devices/deviceproperties.cpp
If connection fails when initiated from the device properties dialog, the
connected page is shown after the update formats worker thread completes.
> Properly handle connect errors when initiated from properties dialog.

- ext/libclementine-common/core/closure.cpp
- ext/libclementine-common/core/closure.h
When a closure involves an ObjectHelper, a connection is made from the
receiver's destroyed signal and the helper object's deleteLater slot. Since
the signal between the sender and the helper object isn't disconnected until
either object is actually destroyed, this leaves a hole where the helper
holds a pointer to an invalid receiver object, but is still able to receive
the signal connected to its Invoke slot.
Instead of connecting the destroyed signal to deleteLater, connect it to a new
TearDown slot that immediately disconnects the signal then calls deleteLater.
> Fix closure timing hole.

- src/library/librarymodel.cpp
- src/library/librarymodel.h
Create a thread pool for each LibraryModel object and block destruction until
all threads that are operating on this object are complete.
Note that this is not a complete solution. The async query also uses the library
backend which may still be deleted before the thread exits. This will be
addressed in a future change.
> Prevent deletion of LibraryModel object while async query is running.

- src/devices/connecteddevice.cpp
- src/devices/connecteddevice.h
- src/devices/filesystemdevice.cpp
- src/devices/gpodloader.cpp
- src/devices/gpodloader.h
- src/devices/mtploader.cpp
- src/devices/mtploader.h
- src/internet/core/cloudfileservice.cpp
- src/internet/core/cloudfileservice.h
- src/internet/jamendo/jamendoservice.cpp
- src/internet/jamendo/jamendoservice.h
- src/internet/magnatune/magnatuneservice.cpp
- src/internet/magnatune/magnatuneservice.h
- src/internet/subsonic/subsonicservice.cpp
- src/internet/subsonic/subsonicservice.h
- src/library/library.cpp
- src/library/library.h
- src/library/librarymodel.cpp
- src/library/librarymodel.h
A LibraryBackend may be deleted while an associated LibraryModel object is using
it. An example is an async query running while a connected device is removed.
To prevent this, use a share pointer for the LibraryBackend.
This fixes one case where LibraryBackend is used after deletion. However, the
raw pointer is still passed around in several other places. These should be
evaluated on a case-by-case basis to insure that circular depencencies aren't
introduced.
> Fix LibraryModel async query crash.

- src/devices/giolister.cpp
- src/devices/giolister.h
Using libmtp or libgphoto2 to access a device that gvfs has mounted causes the connection to fail. libmtp is calling libusb_claim_interface which, according to libusb documentation, will return LIBUSB_ERROR_BUSY if claimed by a different program. For mtp and gphoto2 devices discovered by the GioLister, use the file scheme and access the device through the gvfs mount.
> Broken mtp

- src/library/librarywatcher.cpp
When a device is removed during a scan, the scan is cancelled, but the task is
not set to finished.
> Fix hung progress indicator on device disconnect.

- src/library/librarywatcher.cpp
When scanning a device such as a mobile phone, it's likely that a directory
containing both image and audio files will be found. Besides the appearance of a
hung scan, it's unlikely that a relevant image will be found.
In the case where filters for relevant filenames don't yield results, set a
sanity limit on the number of images. If the list size is beyond than that
threshold, return an empty path.
> Prevent runaway cover art searches.

- src/library/librarywatcher.cpp
- src/library/librarywatcher.h
This is can be done without protecting the directory reference since the method
that removes directories from the watch list is only called on the same thread
as the scan, and never during the life of the ScanTransaction object.
> Pass a Directory reference to ScanTransaction instead of a directory id.

- src/library/librarywatcher.cpp
- src/library/librarywatcher.h
Store a boolean along with watched directories to indicate active. Use this flag
to halt scans on a per-directory basis.
> Add ability to cancel scan per directory.

- src/devices/filesystemdevice.cpp
- src/library/library.cpp
- src/library/librarywatcher.cpp
- src/library/librarywatcher.h
When a directory is removed from the library during a scan, the scan continues
until complete. This change cancels the scan immediately, unblocking the watcher
thread, then signals the watcher to remove the directory.
A second issue occurs when a previously scanned device is removed during a
scan. All remaining files will be marked as deleted. This change mitigates
this issue, but a timing hole still remains here.
> Cancel scan when directory is removed.

- src/core/songloader.cpp
- src/core/utilities.cpp
- src/core/utilities.h
- src/engines/gstengine.cpp
- src/engines/gstengine.h
- src/engines/gstenginepipeline.cpp
- src/moodbar/moodbarpipeline.cpp
The fix-up for URLs for files that that begin with // no longer works since the
QUrl class determines that these modifications are invalid, resulting in an
empty string when converted. Instead of attempting to modify the QUrl, add a
utility function that makes the correction on the encoded byte array at time of
usage.
> Fix UNC paths.

- ext/libclementine-common/core/logging.cpp
- src/engines/gstenginepipeline.cpp
Use qLogCat to put verbose GStreamer callback messages into a new
GstEnginePipelineCallbacks category. Filter that category instead of
the entire class by default.
> Enable debug logging for GstEnginePipeline by default.

- src/internet/intergalacticfm/intergalacticfmservice.cpp
At the time of this commit, the channel list from intergalactic.fm is
unavailable. To the user, this is failing silently. Add an error message for
this failure. If this issue persists, then the service should be removed or a
hardcoded station list should be used.
> Display message to user when IntergalacticFM channel list fails.

- src/internet/icecast/icecastservice.cpp
When a request fails, show an error dialog and don't attempt to parse results.
> Handle errors from icecast directory requests.

- src/internet/podcasts/itunessearchpage.cpp
Using the [] operator on a non-const QJsonObject inserts an item. The test for an error message was always positive. Use the contains method instead.
> Fix itunes search.

- ext/libclementine-common/core/logging.cpp
- src/core/network.cpp
New logging class NetworkRequests disabled by default, but can be enabled with
the command line option.
> Add a logging category to log all network requests.

- src/internet/digitally/digitallyimportedclient.cpp
- src/musicbrainz/acoustidclient.cpp
- src/songinfo/songkickconcerts.cpp
Noted previously, using the [] operator on a non-const QJsonObject causes the
creation of the key and does not work for checking existence. Convert the
remaining isUndefined call sites to use QJsonObect::contains.
> Convert remaining QJsonValue::isUndefined usage.

- src/core/player.cpp
- src/core/utilities.cpp
- src/core/utilities.h
- src/engines/gstenginepipeline.cpp
While debugging an issue, I came across a couple places where auth tokens were being logged in url query strings.
> Scrub debug urls

- src/internet/googledrive/googledriveclient.cpp
- src/internet/googledrive/googledriveclient.h
- src/internet/googledrive/googledriveservice.cpp
- src/internet/googledrive/googledriveurlhandler.cpp
This fixes GetStreamingUrlFromSongId for Google Drive. 
With this change, playback is still broken due to an API change:
https://cloud.google.com/blog/products/application-development/upcoming-changes-to-the-google-drive-api-and-google-picker-api
I'm looking at solutions for that.
> Gdrive get file

- src/playlist/queue.cpp
- src/playlist/queue.h
Removal of items from a playlist is done with a single transaction. When
Queue::SourceLayoutChanged is called after this, the items in the queue are
checked one at a time. When an item is removed, it triggers dataChanged signal
from the model, connected to the SourceDataChanged slot. There, ItemCountChanged
is emitted which calls UpdateTotalLength. This method will assert when it finds
an item that is in the queue, but not in the playlist.
To solve this, disconnect the ItemCountChanged signal at the beginning of
SourceLayoutChanged and re-enable it after cleaning the queue. The method emits
the signal before returning.
> Fix assertion when deleting multiple queued items from playlist.

- src/core/application.cpp
- src/core/application.h
- src/core/utilities.cpp
- src/main.cpp
Clementine detects a data directory in the same directory as the executable to
determine portable configuration. But there are some packages that create
/usr/bin/data, causing Clementine to run in portable mode.
Use a more unique data directory name, clementine-data, as the portable data
directory. For backwards compatibility, use the legacy data directory if the
already exists there.
This is a response to #6583. I don't see the portable mode documented in the readme or the wiki.
> Prevent accidental usage of /usr/bin/data

- src/core/qxtglobalshortcutbackend.cpp
The 3rd party qxt library assumes X11 on Linux systems. Don't register
QxtGlobalShortcutBackend when using Wayland.
> Short-term fix for shortcut crash

- src/ui/globalshortcutssettingspage.cpp
- src/ui/globalshortcutssettingspage.h
- src/ui/globalshortcutssettingspage.ui
- Group list and settings so they can be enabled/disabled together.
- Make default selection shortcut list. Previous behavior set options
for the first item, but didn't highlight selection.
- Rename ItemClicked to CurrentItemChanged to reflect correct signal.
> Shortcut settings page cleanup.

- src/playlist/playlistlistcontainer.cpp
While iterating over expandList in refreshExpanded, calls to setExpanded cause
the list to be appended. Since a QList uses and array implementation that must
resize when reserved space is exhausted, iterators are unsafe for this case.
Use indexes, which are O(1) in QLists, instead of iterators for this case.
> Fix crash when searching playlist.

- ext/libclementine-common/core/logging.cpp
- ext/libclementine-common/core/logging.h
Some functions and macros aren't used outside of logging.cpp and don't need be
declared in header. Functions can be static.
This is just a bit of cleanup ahead of a minor fix that I'm working on. Also wanted to make sure the build system didn't catch any usages that I didn't find.
> Move unneeded declarations and macros from logging header.

- src/ui/mainwindow.cpp
PlaylistRightClick() uses the wrong songs when calculating editable, streams, queue, skipped, etc when the playlist is filtered because it's missing a call to mapToSource().
> Add missing mapToSource() in MainWindow::PlaylistRightClick

- src/playlist/playlistlistcontainer.cpp
Clang 10 warns that ``s`` might be copied. Use a reference to avoid copying.
> Use reference on a const loop var to avoid copy

- src/core/player.cpp
- src/engines/enginebase.cpp
- src/engines/enginebase.h
- src/engines/gstengine.cpp
- src/engines/gstengine.h
- src/engines/gstenginepipeline.cpp
- src/engines/gstenginepipeline.h
- src/engines/playbackrequest.h
Add a class to wrap the URL in the playback engines. In the future, this will
contain authentication information for the specified URL. It can also include
the start and end time as well as other data that is currently specified along
with the URL.
This is the first commit for the #6581 RFC. I was originally going to use shared pointers, but that's an optimization that can be made later.
> Add MediaPlaybackRequest class.

- src/core/player.cpp
- src/core/urlhandler.h
- src/engines/gstenginepipeline.cpp
- src/engines/playbackrequest.h
- src/internet/googledrive/googledriveclient.cpp
- src/internet/googledrive/googledriveclient.h
- src/internet/googledrive/googledriveservice.cpp
- src/internet/googledrive/googledriveurlhandler.cpp
These are the remaining changes that pass authentication headers from the google drive client through to the gstreamer engine.
> Fix gdrive

- src/engines/gstengine.cpp
When redirecting, copy the original request, which may include extra headers.
> Preserve auth headers when redirecting.

- src/internet/spotify/spotifyblobdownloader.cpp
Use the NoLessSafeRedirectPolicy policy which will redirect as long as
it isn't from https to http.
This should fix #6569 and #6623
> Handle redirects when downloading Spotify blob.

- src/internet/spotify/spotifyblobdownloader.cpp
RedirectPolicyAttribute was introduced in Qt 5.9, but Debian Stretch is at 5.7.
This change can be reverted when the base support version moves to 5.9.
> Use legacy RedirectPolicyAttribute instead of FollowRedirectsAttribute.

- src/internet/core/cloudfileservice.cpp
- src/internet/jamendo/jamendoservice.cpp
- src/internet/magnatune/magnatuneservice.cpp
- src/internet/subsonic/subsonicservice.cpp
- src/library/librarybackend.cpp
- src/library/librarybackend.h
Most users of LibraryBackend pass empty strings for directory and subdirectory
tables, so add a second Init method that omits those.
> Add a common LibraryBackend::Init method.

- src/internet/subsonic/subsonicdynamicplaylist.cpp
This PR changes how dynamic subsonic playlists build the song URL. A similar issue (#6080) has been fixed for playing subsonic songs directly, but dynamic playlists currently don't have a song ID at all leading to a "This appears to be a text file" error when trying to play any song from a dynamic playlist.
> Fix songs in dynamic subsonic playlist

- src/internet/subsonic/subsonicdynamicplaylist.cpp
- src/internet/subsonic/subsonicdynamicplaylist.h
- src/internet/subsonic/subsonicservice.cpp
- src/internet/subsonic/subsonicservice.h
This PR adds a new dynamic playlist to subsonic that plays random songs instead of only random albums. The previous dynamic playlists have been renamed.
I had to remove the Clementine configuration to be able to see the changes to playlists, I guess there's a better way to change the dynamic playlists without deleting the entire configuration.
While this PR doesn't really depend on my other PR (#6631), this PR builds on top of that and is pretty useless without the previous PR.
> Add dynamic playlist for playing random songs from subsonic

- tests/translations_test.cpp
Hello there :-)
When packaging clementine for guix, we run the unittests. I noticed the pre-release was failing this test because of an out-dated translation so here's a fix!
Thanks,
Pierre
> Fix tranlations test.

- ext/libclementine-tagreader/tagreader.cpp
Pass taglib debug messages through qLog instead of printing directly to stderr.
> tagreader: Add debug handler for taglib

- src/visualisations/visualisationcontainer.cpp
- src/visualisations/visualisationcontainer.h
Pressing the close button on the window sends a close event, where other methods
of exiting visualization just hide the window. If shown again after close, the
window will be empty. To fix this, handle and reject the close event. Call hide
instead.
> visualisations: Fix close action

- src/ui/settingsdialog.cpp
- src/ui/settingsdialog.h
- src/ui/settingspage.cpp
- src/ui/settingspage.h
Current settings behavior calls Save for all pages, which can take several seconds. This change calls Save only on pages that have been shown.
> Settings cleanup

- src/internet/subsonic/subsonicservice.cpp
> subsonic: Use correct URL query params to fetch cover

- src/engines/gstenginepipeline.cpp
- src/engines/gstenginepipeline.h
According to the gst_element_request_pad documentation, request pads must be
released after usage. They aren't automatically released and dereferenced when
the element is destroyed.
> gstengine: Fix gtreamer request pad leak

- src/globalsearch/icecastsearchprovider.cpp
- src/globalsearch/icecastsearchprovider.h
- src/internet/icecast/icecastmodel.cpp
- src/internet/icecast/icecastmodel.h
- src/internet/icecast/icecastservice.cpp
- src/internet/icecast/icecastservice.h
Use a shared pointer since the model and search provider both hold pointers to
the backend object. Also removed unused accessor method.
> icecast: free backend on exit

- src/core/application.cpp
- src/ui/console.cpp
- src/ui/console.h
- src/ui/console.ui
- src/ui/mainwindow.cpp
- src/ui/mainwindow.h
- src/ui/mainwindow.ui
These changes re-enable the console menu option for more general debug usage. The option is only available if the environment variable CLEMENTINE_DEBUG_CONSOLE=1. A new tab in the dialog provides options to dump the application and main window objects trees.
Thoughts on future use:
- Query information on an object based on name.
- Adjust logging classes and levels.
- Dump gstreamer pipeline info.
> Debug console

- src/smartplaylists/querysearchpage.ui
- src/smartplaylists/querywizardplugin.cpp
This dialog was falling off the bottom on a smaller screen.
The user (me) could not press the buttons at the bottom.
I reduced the minimum heights so its ok for smaller screens but added expanding
so it will be larger are on big screens.
I tested by manually making the dialog bigger and smaller as a user - to make
sure it made best use of the space.
> Make first smart playlist dialog fit on smaller screen

- src/core/application.cpp
- src/core/database.cpp
- src/core/tagreaderclient.cpp
- src/covers/albumcoverloader.cpp
- src/internet/podcasts/podcastdeleter.cpp
- src/networkremote/networkremote.cpp
In Application::MoveToNewThread, name the new thread after the object being
moved. Give those objects names as well.
The thread names display in gdb with "info threads".
> Name all threads created by Application

- src/playlist/dynamicplaylistcontrols.ui
Avoids message:   
QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 200, 200, 200, 75%'
> Changed rgb() to rgba()

- src/smartplaylists/querysortpage.ui
- src/smartplaylists/wizard.cpp
- Displays the name of the smart playlist in the wizard title when you are editing
- Specified a minimum width for the number-of-songs spinner since it wasn't displaying nicely for me (Linux)
> Minor smart playlist UI improvements

- src/playlist/playlist.cpp
When editing a smart playlist "Original Year" comes before "Year" alphabetically (of course).
But the user might want Year.  So I changed the text to "Year - original" so the user
sees both kinds of year beside each other in the list and can make a better choice.
> Change text for Original Year

- src/devices/cddadevice.h
- src/devices/cddasongloader.cpp
- src/engines/gstenginepipeline.cpp
- src/engines/gstenginepipeline.h
This is a follow-on to change 335bc89. That changed fixed cdda URLs without paths but broke the schemes on URLs with paths.
> Fix cd playback

- data/schema/jamendo.sql
A previous change added ftsyear to all songs_fts tables, but the base jamendo
schema, which is used when recreating the database, was not updated. This
resulted in thousands of sql errors when reloading the catalog.
> database: Add ftsyear to jamendo.songs_fts

- src/core/organise.cpp
This addresses #6715. However, there's still a still an issue with incorrect filenames displayed in the dialog that needs a bigger fix.
> organise: Refresh filename after transcode

- src/core/organiseformat.cpp
- src/core/organiseformat.h
- src/ui/organisedialog.cpp
- src/ui/organisedialog.h
This is a follow-up to the previous change. In the case that a user has chosen a transcode format, it will display the file extensions properly. If the files are transcoded for other reasons, the dialog doesn't have any way of knowing. There could be a tighter coupling between the two classes to correct this.
> Organize dialog filenames

- src/CMakeLists.txt
- src/internet/jamendo/jamendoplaylistitem.cpp
- src/internet/jamendo/jamendoplaylistitem.h
- src/internet/magnatune/magnatuneplaylistitem.cpp
- src/internet/magnatune/magnatuneplaylistitem.h
- src/library/libraryplaylistitem.cpp
- src/playlist/dbplaylistitem.cpp
- src/playlist/dbplaylistitem.h
These changes remove LibraryPlaylistItem as a base class of Jamendo and Magnatune items. Removing the inherited implementation of IsLocalLibraryItem prevents song ratings from being set for local library items with the same database IDs.
> Library playlist baseclass

- src/playlist/playlistcontainer.cpp
When the current playlist is changed, PlaylistContainer::SetViewModel is called
to set the new list. This calls PlaylistView::SetItemDelegates, which allocates
several objects that are never freed. Instead, move the call to SetItemDelegates
to PlaylistContainer::SetApplication, which is only called once.
> Fix playlist memory leak

- src/playlist/playlistcontainer.cpp
The manager's library backend may not be set when this is called.
> Get backend from application in PlaylistContainer::SetApplication

- src/analyzers/analyzerbase.cpp
I'm not sure what the original intention was here, but it was always accessing one element past the end of the scope array.
> Fix access past end of vector in getPsychedelicColor

- src/playlist/playlist.cpp
When there is album artist information available for a track, the user would
probably expect that "Repeat Album" should cycle through all songs with the same
album artist and album title, not only all songs with the same artist and album
title.
> Use effective album artist for Repeat Album logic

- src/devices/udisks2lister.cpp
The extends two functions:
- Recognize iPods as iPods, check for them in MakeDeviceUrls
- Give them a nice Icon in DeviceIcons (code taken from devicekitlister)
Before this commit, the iPod is recognized as normal device like an USB stick etc. when udisks is used for device mounting.
I haven't searched for related bugs, maybe this closes one or more of them.
> udisks2lister: enable ipod recognition

- src/internet/podcasts/podcastparser.cpp
The opml parsing code handles cases where there are extra levels in the xml file
by copying the child to the main container. This corrupts the source instance
during the copy, which leads to corruption in the destination, and ultimately a
crash when it is later used.
To fix, do the copy in two steps, copying the child container to a temporary
location before copying to the destination.
This is a fix for #6802
> Fix opml import crash

- src/ui/mainwindow.cpp
- src/ui/mainwindow.h
In 2bac3626 I removed `SetHiddenInTray` from closeEvent because it would have been a double hide when calling the default handler. This caused a regression in that the window at startup no longer remembered if it was hidden only if the window was closed via the window manager to hide it last.
This cleans up the state tracking of showing and hiding the main window by changing the config setting on all show and hide events so it gets set regardless of event spontaneity. It also fixes having to click the tray icon twice to raise the window with focus if you had another active focus window already.
> Fix window visibility state & active show from tray

- src/core/commandlineoptions.cpp
- src/core/commandlineoptions.h
- src/core/player.cpp
- src/core/player.h
- src/ui/mainwindow.cpp
Adding a command line option to start playing the playlist given as argument.
I reused the command line argument playlist_name_ from the create_playlist option - I had to add it to the [De]Serialize functions to make it work, meaning -unless I missed something- that the create playlist could not be working before.
And this "create playlist" is still not working for me, but I did not dig further.
> add CLI play-playlist option, to play given playlist name.

- src/core/player.cpp
This PR is to fix a bug introduced with PR https://github.com/clementine-player/Clementine/pull/6809
I used ` SetActiveToCurrent` instead of `SetCurrentPlaylist` to select the new playlist as current .
> PlayPlaylist: set current and not active playlist to selection

- src/devices/giolister.cpp
- src/devices/giolister.h
GioLister::UnmountDevice calls g_object_unref on the GVolume object held by a
DeviceInfo. This appears to be left over from a time before DeviceInfo held
onto the volume.
Also added _ suffix to some DeviceInfo members to avoid confusion with method args.
> Remove extra object unref

- src/devices/giolister.cpp
- src/devices/giolister.h
Read the G_FILE_ATTRIBUTE_UNIX_IS_MOUNTPOINT attribute (unix::is-mountpoint) to
determine if a volume is a mount that udisks2 has detected. Ignoring these
prevents network mounts from showing up as devices.
> giolister: Ignore mountpoints

- src/devices/giolister.cpp
If the gvfs mountpoint property for a volume is empty, we add an empty URL to
the devices URL list. This causes errors in duplicate entry detection.
> giolister: Don't include invalid mountpoint url

- .github/workflows/all.yml
Ubuntu Eoan (19.10) is EOL and the repositories are no longer accessible. Bump
the image used for the source tarball build to LTS ubuntu:focal.
> build: Remove eoan usage

- src/internet/core/internetmodel.cpp
- src/internet/core/internetmodel.h
When opening a context menu on an internet item, the selected items are stored
in the InternetModel instance. In cases when the items are removed, certain menu
options can cause a crash. A specific case is downloading a podcast when the
user has chosen to limit the number of visible episodes. The subtree for the
podcast is rebuilt after the download completes, so if a context menu was opened
during the download time, selecting the append to playlist option will attempt
to operate on bad indexes.
This fix uses the rowsAboutToBeRemoved signal to remove these stored indexes.
There are likely another rare cases where the indexes can become invalid. For
example, sibling items within a subtree may be removed, causing the stored
indexes to become incorrect or out of range.
This is a fix for …
> Clear cached indexes in InternetModel when rows are removed

- dist/clementine.spec.in
In fedora 31, the gstreamer1-plugins-ugly package was removed. A
gstreamer1-plugins-ugly-free package was added in fedora 27 and
gstreamer1-plugins-ugly had depended on that before removal.
Note that there is still a gstreamer1-plugins-ugly package available
in rpmfusion.
> build: Remove dependency on obsolete gstreamer1-plugins-ugly

- ext/clementine-spotifyblob/CMakeLists.txt
- ext/clementine-tagreader/CMakeLists.txt
- src/CMakeLists.txt
- tests/CMakeLists.txt
This was causing compilation failures, static assertion failed, with GCC 11.
Fix #6865
Signed-off-by: Robert-André Mauchin <zebob.m@gmail.com>
> Drop -std=c++0x and -U__STRICT_ANSI__

- 3rdparty/libprojectm/MilkdropPresetFactory/InitCond.cpp
- 3rdparty/libprojectm/MilkdropPresetFactory/Parser.cpp
When using rpmbuild on Fedora 33, the build fails with:
error: ‘__builtin_strncpy’ specified bound depends on the length of the source argument [-Werror=stringop-overflow=]
This was fixed as part of projectm change d4d74f6d. This change takes the
relevant parts of that commit.
Note that the projectm commit contains several other warning fixes that might
affect Clementine builds in the future.
> Fix rpmbuild error in librojectm

- src/core/mergedproxymodel.cpp
- src/core/mergedproxymodel.h
An old hack was notifying MergedProxyModel users that max int rows had been
removed when a submodel was reset. This caused the code that invalidates
selected items to spin for a very long time. A modelAboutToBeReset signal,
introduced in Qt 4.6, allows notification before the submodel information is
lost.
Note: there is one other case, in RemoveSubModel, where this hack is used.
This is only called when a device is removed and doesn't trigger this
condition, but it should probably be addressed in the future.
> Fix hang during internet model reset

- src/engines/gstengine.cpp
- src/engines/gstenginepipeline.cpp
GstEngine::CreateElement unrefs the supplied bin if an error
occurs. In all current cases, that bin is referenced by a
pipeline.
> gstengine: Remove extra unref on element creation failure

- src/engines/gstengine.cpp
- src/engines/gstenginepipeline.cpp
- src/engines/gstenginepipeline.h
GstEnginePipeline::InitFromString was attempting to link the decoder and audio
bins twice and returning the result of the failed second attempt as it's own
status. The return value was also being ignored by the caller.
> gstengine: Fix InitFromString return value

- src/ui/mainwindow.cpp
- src/ui/mainwindow.h
Each time the debug console is launched, a new instance is created, but never
deleted. To fix, create one instance, if the option is enabled, and show that
one each time the menu option is selected.
> Fix debug console instance leak

- src/CMakeLists.txt
- src/core/application.h
- src/core/player.cpp
- src/engines/gstengine.cpp
- src/engines/gstengine.h
- src/engines/gstenginedebug.cpp
- src/engines/gstenginedebug.h
- src/engines/gstenginedebug.ui
- src/engines/gstenginepipeline.cpp
- src/engines/gstenginepipeline.h
- src/ui/console.cpp
- src/ui/console.h
- src/ui/mainwindow.cpp
- src/ui/mainwindow.h
Added a mechanism to add new pages to the debug console.
Added a method in GstEnginePipeline to dump a graph of the pipeline.
Added a GstEngine page in the console with a button to dump dump the graph.
This should help debug issues like #6861
> Add a GstEngine page on the debug console

- src/internet/somafm/somafmservice.cpp
Prefer the high quality 128 kbit/s AAC stream over the 'fast' 128 kbit/s mp3 stream.
> internet/soma.fm: use high quality AAC stream

- src/engines/gstenginepipeline.cpp
- src/engines/gstenginepipeline.h
These changes add a capsfilter in the pipeline before the tee. We check the decoder source pad when it's added and, if is going to push S16LE, we set the caps of the new filter to F32LE.
Future considerations:
- This does not address cases where there is already a source pad when the decoder bin is created.
- Maybe use F32LE only if the source format is > 16 bit depth.
- Might want to probe the output device to make sure it can also support F32LE.
Fix for #6861
> Fix output sample depth

- src/CMakeLists.txt
- src/engines/gstenginepipeline.cpp
- src/engines/gstenginepipeline.h
- src/engines/gstpipelinebase.cpp
- src/engines/gstpipelinebase.h
- src/transcoder/transcoder.cpp
- src/transcoder/transcoder.h
This allows the use of the DumpGraph method in transcoding pipelines. Note that this does not currently provide a UI to do dump. The call can be added to Transcoder::StartJob for debugging.
If we extend the use of the base class to all other pipelines, we could enumerate the list in the debug console and provide a common set of debug tools.
> Add a base pipeline class to share debug methods with the transcoder pipeline

- src/playlist/playlistmanager.cpp
Use %Lx to localize number formatting.
Reference: https://doc.qt.io/qt-5/qtquick-internationalization.html#5-use-lx-so-numbers-are-localized
Fix for #6886
> Localize song count in playlist

- src/CMakeLists.txt
- src/transcoder/transcoderoptionsflac.cpp
- src/transcoder/transcoderoptionsflac.h
- src/transcoder/transcoderoptionsflac.ui
The gstreamer flacenc element defines a set of quality levels that is different
from the standard flac library. Its highest level, labeled "insane", uses
settings that are outside of the streamable subset. Set the streamable-subset
property to false for this level.
Reference: https://xiph.org/flac/format.html#subset
Fixes #6876
> transcoder: Fix flacenc "insane" level encoding

- src/engines/gstenginepipeline.cpp
- src/engines/gstenginepipeline.h
- src/engines/gstpipelinebase.cpp
- src/engines/gstpipelinebase.h
- src/transcoder/transcoder.cpp
- src/transcoder/transcoder.h
Currently, all pipelines are named "pipeline". Use a type string in combination
with the unique stream id to give each pipeline a unique name.
> Give pipelines unique names

- src/engines/enginebase.cpp
- src/engines/enginebase.h
- src/engines/gstengine.cpp
New ids were being created for background stream mapping, but streams already
have unique IDs that can be used for this.
> gstengine: Use existing stream id to track background streams

- src/core/player.cpp
- src/core/player.h
- src/ui/mainwindow.cpp
- src/ui/mainwindow.h
- src/ui/mainwindow.ui
I've written a small change to clementine to allow the user to skip to the next album in a playlist. Similar functionality to that used to play the next track, but it will continue to skip forward until the album title changes.
> Adding a "play next album" function, in addition to "play next track". Closes #2505.

- src/core/application.cpp
- src/core/application.h
- src/ui/mainwindow.cpp
- src/ui/mainwindow.h
Move check for debug console to Application and use environment variable CLEMENTINE_DEBUG instead of CLEMENTINE_DEBUG_CONSOLE.
I doubt anybody else is currently using the debug console. And if they are, they're probably reading commit messages as well.
> Generalize debug feature check

- src/transcoder/transcodedialog.cpp
- src/transcoder/transcoder.cpp
- src/transcoder/transcoder.h
Previously, pressing the "Start transcoding" button with zero files selected would show the progress group with the progress bar in the busy state.
Also removed slots annotation from Transcoder::Start() and Transcoder::Cancel() since they are always called directly.
> Don't show progress when nothing is selected

- src/ripper/ripcddialog.cpp
- src/transcoder/transcodedialog.cpp
- src/transcoder/transcoderoptionsdialog.cpp
- src/transcoder/transcoderoptionsdialog.h
- src/transcoder/transcoderoptionsdialog.ui
- src/ui/networkremotesettingspage.cpp
Remove condition that allows no dialog to be displayed when user selects
options for transcoding. Display the dialog with an error message
instead. This also applies to the transcode options dialog in the
ripping and network remote settings.
This should not occur in current scenarios, but it's groundwork another fix.
> Provide user feedback in options error condition 

- src/core/utilities.cpp
- src/core/utilities.h
- src/internet/podcasts/podcastparser.cpp
Move code from PodcastParser::ParseItem for reuse.
Example:
Calling Utilities::MakeBugReportUrl("New bug") returns:
https://github.com/clementine-player/Clementine/issues/new?title=New%20bug
> utilities: Add common method for bug report URL generation

- src/transcoder/transcoder.cpp
- src/transcoder/transcoder.h
- src/transcoder/transcoderoptionsdialog.cpp
- src/transcoder/transcoderoptionsdialog.ui
In transcode audio format options, determine which gstreamer encoder element will be used to encode the chosen audio format. Show an error message if the element isn't know to the settings dialog.
Current behavior shows settings for faac when MP4 is selected, but that is not available in base Fedora and Debian/Ubuntu distros. A follow-up change will add options pages for the fdkaacenc and voaacenc.
> Show encode options for correct element

- src/CMakeLists.txt
- src/transcoder/transcoderoptionsdialog.cpp
- src/transcoder/transcoderoptionsdialog.h
- src/transcoder/transcoderoptionsdialog.ui
- src/transcoder/transcoderoptionserror.cpp
- src/transcoder/transcoderoptionserror.h
- src/transcoder/transcoderoptionserror.ui
Create a TranscoderOptionsError class and ui that inherits from
TranscoderOptionsInterface. Use this to display options errors. Move
widget creation into a static method. These changes will allow use of
the same mechanism in the transcoder settings page.
> transcoder: Move option error into its own widget

- src/CMakeLists.txt
- src/transcoder/transcoderoptionsdialog.cpp
- src/transcoder/transcoderoptionsfdkaac.cpp
- src/transcoder/transcoderoptionsfdkaac.h
- src/transcoder/transcoderoptionsfdkaac.ui
- src/transcoder/transcoderoptionsvoaac.cpp
- src/transcoder/transcoderoptionsvoaac.h
- src/transcoder/transcoderoptionsvoaac.ui
These are the aac encoder elements available in vanilla Fedora and Debian/Ubuntu distros.
https://gstreamer.freedesktop.org/documentation/fdkaac/fdkaacenc.html
https://gstreamer.freedesktop.org/documentation/voaacenc/index.html
Base class options aren't included in these or any of the other options widgets. If those are deemed necessary at any point, a new widget could be added and embedded in the other options pages.
> Add transcoder options widgets for fdkaacenc and voaacenc

- src/internet/core/oauthenticator.cpp
Query params were not added to redirect url prior to inclusion in oauth request. This change fixes OneDrive authentication.
Regression introduced in 8b226c2171
> oauth: Fix redirect

- src/CMakeLists.txt
- src/core/application.cpp
- src/core/application.h
- src/main.cpp
- src/ui/splash.cpp
- src/ui/splash.h
Since initialization on first startup or during a database schema update can take several seconds, show a splash screen. In the initial implementation, this is just a small Clementine logo.
The benefit of instantiating the splash in the Application class rather than in main is that it could eventually show status messages during startup. However, this implementation does not use the QSplashScreen::finish mechanism that would synchronize the hiding of the splash screen with the showing of the main window.
> Add splash

- src/widgets/errordialog.cpp
Don't clear the message dialog if a hide event is sent from the window
manager. These spontaneous events are sent when a window is minimized,
moved to a different screen, etc.
> errordialog: Don't clear messages on sponaneous events.

- src/internet/subsonic/subsonicservice.cpp
Background: Funkwhale is a music streaming server which implements the Subsonic API. It can be used as a source in Clementine by adding it as a Subsonic server.
When using a Subsonic as a source, Clementine will pull album art from the Subsonic server using the API. With standard Subsonic servers, this works fine. With Funkwhale, it does not work. See this comment on steps I went through to debug the issue: https://github.com/clementine-player/Clementine/issues/6565#issuecomment-786139065 and the cause/solution of the issue.
Subsonic's API supports looking up cover arts on the `getCoverArt` endpoint using the song ID, but it also provides an explicit cover art ID which can also be used to look up the song. This cover art ID is provided in the `coverArt` attribute from the `getAlbum`, …
> Fix cover art query for Subsonic-based Funkwhale servers

- ext/libclementine-tagreader/cloudstream.cpp
- src/internet/core/oauthenticator.cpp
- src/internet/core/oauthenticator.h
- src/internet/skydrive/skydriveservice.cpp
- src/internet/skydrive/skydriveservice.h
- src/internet/skydrive/skydriveurlhandler.cpp
- src/internet/skydrive/skydriveurlhandler.h
The live API was deprecated in 2018. This change implements basic
onedrive access using the MS graph API.
The URL scheme was also changed from skydrive to onedrive. This is based
on the assumption that existing playlists won't have compatible item
ids.
Known issues:
- Directories with over 200 items will be truncated.
- No mechanism for discovering changes at runtime.
- No mechanism for removing deleted items or rescanning.
Reference: https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/migrating-from-live-sdk?view=odsp-graph-online
> Fix onedrive

- gst/moodbar/CMakeLists.txt
Append CMAKE_CXX_FLAGS and CMAKE_C_FLAGS instead of setting. Setting the
variables causes breakage in cross-compiled systems where sysroots and
machine types are set.
> build: Don't reset cflags in moodbar cmake

- src/main.cpp
Wayland is a new protocol used under Linux used as an alternative to the old X11.
Windowing systems under Wayland won't use the window icons defined inside the application, instead they require the application to define an associated "desktop file" and load the icon defined in that file.
This is quite easy under Qt using [QGuiApplication::setDesktopFileName()](https://doc.qt.io/qt-5/qguiapplication.html#desktopFileName-prop)
This PR adds the needed method call.
Before:
After:
> Add window icon under Linux/Wayland

- src/core/player.cpp
- src/core/player.h
- src/engines/enginebase.h
- src/engines/gstengine.cpp
- src/engines/playbackrequest.h
Use the request URL rather than the media URL when emitting the SongChangeRequestProcessed signal. The request URL is the URL that the PlaylistManager, which is the only consumer of this signal, knows about. However, in the current cases, the url is only checked by the playlist when the URLs should be the same.
> Use correct URL in SongChangeRequestProcessed

- src/internet/core/internetmodel.cpp
- src/internet/core/internetmodel.h
- src/internet/core/internetservice.h
- src/internet/spotify/spotifyservice.cpp
- src/internet/spotify/spotifyservice.h
ItemDoubleClicked became noop in 70429217c.
Usage of PlayBehaviour_DoubleClickAction was removed in b08172138.
> internet/core: Remove unused ItemDoubleClicked

- src/library/librarysettingspage.cpp
- src/library/librarysettingspage.ui
- src/library/librarywatcher.cpp
- src/library/librarywatcher.h
Add a new skip option in library settings that takes a comma separated list of file extensions. Skip files with the specified extensions when scanning the library.
Work-around for #6945
> library: Add option to ignore files by extension

- CMakeLists.txt
- ext/clementine-tagreader/tagreaderworker.h
- ext/libclementine-common/core/workerpool.h
- ext/libclementine-tagreader/tagreader.h
- include/clementine-config.h.in
- src/CMakeLists.txt
- src/config.h
workerpool.h utilizes the MAC-specific USE_BUNDLE option, but the file didn't directly include the config header file. Cleanup change 341dc73 reordered some headers, so it was no longer included as a side-effect either.
This also moves /src/config.h to /include/clementine-config.h to remove dependencies of /ext on /src.
> Mac: Fix exec search path 

- src/internet/core/cloudfileservice.cpp
- src/internet/core/cloudfileservice.h
- src/internet/core/internetservice.cpp
- src/internet/core/internetservice.h
- src/internet/digitally/digitallyimportedservicebase.h
- src/internet/icecast/icecastservice.cpp
- src/internet/icecast/icecastservice.h
- src/internet/intergalacticfm/intergalacticfmservice.cpp
- src/internet/intergalacticfm/intergalacticfmservice.h
- src/internet/internetradio/savedradio.cpp
- src/internet/internetradio/savedradio.h
- src/internet/jamendo/jamendoservice.cpp
- src/internet/jamendo/jamendoservice.h
- src/internet/magnatune/magnatuneservice.cpp
- src/internet/magnatune/magnatuneservice.h
- src/internet/podcasts/podcastservice.cpp
- src/internet/podcasts/podcastservice.h
- src/internet/radiobrowser/radiobrowserservice.cpp
- src/internet/radiobrowser/radiobrowserservice.h
- src/internet/somafm/somafmservice.cpp
- src/internet/somafm/somafmservice.h
- src/internet/spotify/spotifyservice.cpp
- src/internet/spotify/spotifyservice.h
- src/internet/subsonic/subsonicservice.cpp
- src/internet/subsonic/subsonicservice.h
Every internet service has a context_menu_ member, so move it to the base InternetService class. Move the common ShowContextMenu method from CloudFileService as well. Other services can adopt this pattern gradually. When all services are migrated, we'll have the option to move to a Lazy pointer implementation.
> Move context_menu_ to InternetService

- src/ui/settingsdialog.cpp
Move the background streams settings page to the general category.
General seemed like a better place for this since only 1 of the 3 is a cloud stream.
> settings: Recategorize background stream settings

- src/internet/core/internetshowsettingspage.h
- src/internet/radiobrowser/radiobrowsersettingspage.h
- src/internet/seafile/seafilesettingspage.h
- src/ui/mainwindow.cpp
- src/ui/notificationssettingspage.h
- src/ui/settingsdialog.cpp
- src/ui/settingspage.h
- src/wiimotedev/shortcuts.cpp
Wii and notifications signals are currently connected for every settings page. Move the signals from the base SettingsPage class into the derived classes and connect the signals for only those objects.
> settings: Don't connect service-specific signals to every page

- src/CMakeLists.txt
- src/ui/settingscategory.cpp
- src/ui/settingscategory.h
- src/ui/settingsdialog.cpp
- src/ui/settingsdialog.h
- src/widgets/groupediconview.cpp
- src/widgets/groupediconview.h
Make the "Internet services" tab the internet providers category header instead of a tab under "User Interface".
> settings: Make the internet header selectable

- src/widgets/ratingwidget.cpp
- src/widgets/ratingwidget.h
RatingPainter::RatingForPos should return a value in 0-1. But if the
passed position was outside of the widget's draw rectangle, a value
outside of that range could be returned.
This is a fix for #6969
> Properly bind the ratings values

- src/smartplaylists/searchterm.cpp
- Cast filename to TEXT in queries
In some versions/builds of sqlite, the LIKE function doesn't match blobs.
- Escape pattern characters in search term
When using the LIKE function, use \ as an escape character and prepend that to occurrences of the pattern characters _ and % in the search term.
Fix for #6958
> Fix smart playlist search terms

- src/library/directory.h
- src/library/librarywatcher.cpp
If a root library directory is deleted and recreated, it is not detected since inotify would need to watch the parent directory. On rescan, if the subdirectory list for a directory is empty, re-add the library's root directory.
Also added accessor methods for Directory and Subdirectory members, but currently only using them in new code for this change.
This issue was reported on the mailing list. Unsure if this problem exists on Windows or Mac.
> Fix rescan in case where library directory was recreated 

- src/engines/gstengine.cpp
- src/engines/gstengine.h
- src/engines/gstenginepipeline.cpp
- src/engines/gstenginepipeline.h
- src/ui/playbacksettingspage.cpp
- src/ui/playbacksettingspage.ui
Add an output format option in playback settings. The options are
Detect, S16LE, and F32LE. Selecting Detect will use the existing
behavior and detect the native format when the pipeline starts. The
other options will set the format when the pipeline is built.
> gstengine: Make output format configurable

- src/CMakeLists.txt
- src/internet/core/internetsettingscategory.cpp
- src/internet/core/internetsettingscategory.h
- src/ui/settingsdialog.cpp
Create a InternetSettingsCategory class and create all internet provider settings pages here.This consolidates most of the knowledge of internet settings pages in the internet subdirectory. The exception is the master page enumeration in the settings dialog.
> Add InternetSettingsCategory class

- src/internet/radiobrowser/radiobrowserservice.cpp
- src/internet/radiobrowser/radiobrowserservice.h
- src/internet/radiobrowser/radiobrowserurlhandler.cpp
- src/internet/radiobrowser/radiobrowserurlhandler.h
Radio-browser.info stations can be added to the "saved radio" list.
Right now, when playing a station from the "saved radio", no metadata about the radio station is available and only the "radiostation:<uuid>" is shown ad the station name in the playlist.
With this change, the radiobrowser service will emit a signal to update the stream metadata when a station using the "radiobrowser:" protocol gets played.
Unfortunately this required an additional network call to retrieve the station art.
While implementing this, i found out that saved radios have an "url_logo" property that is currently useless: even if you set it, the image url won't be passed to any method and won't be shown nowhere.
If i get it correctly the same seems to apply to the "name" field: even if it's set to the …
> Radiobrowser url handler: emit metadata for radio stations

- src/visualisations/projectmvisualisation.cpp
- src/visualisations/projectmvisualisation.h
In version 5.6, Qt introduced an automatic scaling feature for high DPI
displays. Since projectM is not part of the Qt framework, it's necessary
to convert coordinates when specifying view size.
Reference: https://doc.qt.io/qt-5/highdpi.html
Fixes #6957 and #6651
> visualisations: Properly scale projectM view

- src/playlist/queuemanager.ui
This reverts commit 566708b778ee0bd3a99df525251a819cd2ef382c.
Escape sequences are not legal key sequences.
Reference: https://doc.qt.io/qt-5/qkeysequence.html#details
> Revert "↑↓ for "Up" and "Down" (#5841)"

- src/playlist/playlistdelegates.cpp
- src/playlist/playlistdelegates.h
QueuedItemDelegate::DrawBox leaves the painter in a state that can cause
artifacts. Specifically, there are cases where the item text is not
visible. To fix this, push the painter state before making changes and
pop it after drawing.
This appears to be a very old issue: #2207
> playlist: Fix queued item painting

- src/ui/playbacksettingspage.cpp
When populating output options, don't attempt to load an icon if that
field is empty. This cuts some log noise.
> playbacksettings: Don't try to load empty icons

- CMakeLists.txt
- cmake/Summary.cmake
- src/CMakeLists.txt
Remove CMP0011 OLD policy. This policy allowed included files and modules to affect policy in the parent scope. Besides the top level, 3rdparty/libprojectm is the only place where old policy is set.
Remove CMP0012 NEW policy. This policy is already enabled by default. This may have originally been a typo since it was added in the same commit where CMP0011 was set to OLD in the top-level cmake file (b63d1cf).
Reference: https://cmake.org/cmake/help/latest/policy/CMP0011.html
> Remove unneeded policies

- ext/libclementine-common/core/logging.cpp
QString::SplitBehavior is deprecated in 5.14. Use Qt::SplitBehavior after this version.
> core/logging: Fix QString::split deprecation

- ext/clementine-tagreader/main.cpp
- ext/libclementine-common/core/closure.cpp
- ext/libclementine-common/core/workerpool.h
- src/core/crashreporting.cpp
- src/core/utilities.cpp
- src/globalsearch/librarysearchprovider.cpp
- src/globalsearch/simplesearchprovider.cpp
- src/main.cpp
- src/playlist/playlist.cpp
- src/ui/networkremotesettingspage.cpp
- src/visualisations/projectmvisualisation.cpp
QRandomGenerator was introduced in 5.10 and qrand has since been
deprecated. QRandomGenerator::global() returns a global instance that
has been securely seeded. QRandomGenerator provides methods that
generate values within ranges, so taking a modulus of the result isn't
necessary.
> Replace qrand usage with QRandomGenerator

- src/dbus/org.freedesktop.DBus.ObjectManager.xml
- src/dbus/org.freedesktop.UDisks2.Drive.xml
- src/dbus/org.freedesktop.UDisks2.Filesystem.xml
The com.trolltech was renamed to org.qtproject. The code generation tool
still handles the old name, but prints a deprecation error.
Reference: https://bugreports.qt.io/browse/QTBUG-23274
> dbus: Fix annotation deprecation warnings

- src/dbus/org.freedesktop.DBus.ObjectManager.xml
- src/dbus/org.mpris.MediaPlayer2.Playlists.xml
- src/dbus/org.mpris.MediaPlayer2.TrackList.xml
Add direction attributes to args where qdbusxml2cpp was looking for the incorrect annotation.
> dbus: Fix qdbusxml2cpp unknown type warnings.

- ext/libclementine-common/core/workerpool.h
QRandomGenerator::generate() returns an unbounded int32, while the legacy
qrand method always returned a positive number. When generating a tag
reader ID with QRandomGenerator, cast the random value to an unsigned so
that it is formatted as a positive number in the name.
Note that most usages of QRandomGenrator in the codebase use bounded()
instead of generate(), and should work as expected.
> libclementine-common: Use positive numbers for worker ids.

- ext/clementine-tagreader/main.cpp
QSslSocket::addDefaultCaCertificates is deprecated in 5.15. Use QSslConfiguration default configuration instead.
> clementine-tagreader: Fix addDefaultCaCertificates deprecation

- src/dbus/org.freedesktop.DBus.ObjectManager.xml
- src/dbus/org.mpris.MediaPlayer2.Playlists.xml
- src/dbus/org.mpris.MediaPlayer2.TrackList.xml
An earlier change attempted to fix qdbusxml2cpp parsing errors by adding
directions to arguments. However, signal arguments are always out and it
was the annotations that were incorrect.
Fixes: f17b79a10 (dbus: Fix qdbusxml2cpp unknown type warnings., 2021-04-19)
Reference: https://dbus.freedesktop.org/doc/dbus-specification.html
> dbus: Fix signal arg annotations

- src/devices/devicelister.cpp
- src/devices/devicelister.h
- src/devices/giolister.h
In the initial implementation, DeviceLister::DeviceIcons returned a
string list and some listers would concatenate other lists to form that
list. When DeviceIcons was changed to return a variant list, that
logic wasn't changed in many places, so instead of appending, string
list variants are being added icon list.
> devices: Fix guessed icons in DeviceIcons

- ext/libclementine-common/core/logging.cpp
If the __PRETTY_FUNCTION__ macro yields {anonymous} as the class name, use the method name as the tag.
> logging: Fix {anonymous} class name.

- src/networkremote/avahi.cpp
In avahi, don't log empty errors.
> networkremote: Fix some log noise.

- src/ripper/ripper.cpp
Fixes #7017 .
As `Transcoder::Start()` is no longer a slot, I removed the `connect` that invokes it once `Ripper` emits the `RippingComplete` signal and instead call `Transcoder::Start` directly. The alternative would be to reinstate `Transcoder::Start()` as a slot, which I decided against because it would be inconsistent with `Transcoder::Cancel()` which is never (and never was, apparently) used as a slot as well.
> Fix: Transcoding for CD rips not starting.

- ext/libclementine-tagreader/tagreader.cpp
- src/CMakeLists.txt
- src/core/songpathparser.cpp
- src/core/songpathparser.h
- src/core/tagreaderclient.cpp
- src/core/tagreaderclient.h
Move the code that attempts to fill missing song metadata out of the
tagreader worker. In the main process, it will be controllable using
settings and calling context.
The methods were moved into a new SongPathParser class that checks new
settings to determine if action should be taken. Settings UI will be added in an upcoming pull request.
> tagreader: Relocate artist/album/title guessing code

- src/devices/cddasongloader.cpp
- src/musicbrainz/musicbrainzclient.cpp
- src/ripper/ripcddialog.cpp
- src/ripper/ripcddialog.h
closes #7019 and closes #7020:
- For #7019: I increased the timeout for reading CD tags in `CddaSongLoader` and also made sure that waiting for messages stops after reading a TOC and a TAG message each, to ensure that no waiting until timeout happens after receiving messages.
- For #7020: If a MusicBrainz metadata requests returns an XML with several media with identical discid, MusicBrainzClient stops after parsing tracks from the first contained medium.
- Additional for #7020: As an additional safeguard, RipCDDialog will ignore a metadata update if the number of tracks contained does not match the number of tracks on the disc.
The solution for parsing the MusicBrainz metadata is not ideal: It implicitly assumes that the first medium contained in the API response is the correct one. The …
> Improved CD metadata loading

- src/musicbrainz/musicbrainzclient.cpp
Simple change to at least log misbehaving musicbrainz replies so they don't fly entirely under the radar, see #7027
> MusicBrainzClient: Log message for malformed XML in reply

- src/CMakeLists.txt
- src/core/tagreaderclient.cpp
- src/core/tagreaderclient.h
- src/ui/behavioursettingspage.cpp
- src/ui/behavioursettingspage.ui
- src/ui/settingsdialog.cpp
- src/ui/settingsdialog.h
- src/ui/songmetadatasettingspage.cpp
- src/ui/songmetadatasettingspage.h
- src/ui/songmetadatasettingspage.ui
Created a new Song Metadata settings page and move the and moved the tagreader settings here. Added the new "Try to guess missing metadata" setting here to control the setting added in 1309c76be.
I created the new settings page because the behavior page is really crowded and I think more settings can be added for the metadata guessing features, but I'm open to suggestions if "Song Metadata" doesn't feel right. I also used the song info icon for the new page. Maybe somebody who is better at GIMP than I am can come up with something new.
Partial fix for #6952
> Add setting to disable guessing metadata based on filename.

- src/internet/radiobrowser/radiobrowserservice.cpp
Some radio stations on radiobrowser.info contain a playlist address in the "url" field.
The radiobrowser API is so kind to provide also a url_resolved field containing the resolved url of the audio stream.
This PR switches from the "url" to the "url_resolved" field to fix playback of those stations.
Fix #6988
> Radiobrowser.info: use the url_resolved field for radio stations

- src/core/globalshortcuts.cpp
- src/core/globalshortcuts.h
- src/ui/mainwindow.cpp
It was not possible to bind a global shortcut for skipping to the next album. This is easily fixed with some Qt signal plumbing.
> Add a shortcut to go to next album

- src/playlist/playlistmanager.cpp
- src/playlistparsers/cueparser.cpp
- src/playlistparsers/parserbase.h
- src/playlistparsers/playlistparser.cpp
- src/playlistparsers/playlistparser.h
Add an Error signal to PlayListParser and connect that to the PlayListManager::Error signal. This is eventually connected to the
Application::AddError. Add error messages in some cases where PlayListParser can fail silently.
Add a new Error signal to parser implementations as well. Display an error when user tries to use the unimplemented CueParser::Save.
> Add error message mechanism to playlist parsers

- .github/workflows/all.yml
- 3rdparty/libgpod/patches/0001-Look-for-libplist-2.0.patch
Store patch file in repository rather than relying on strawberry's file server.
Reference: https://github.com/strawberrymusicplayer/strawberry-libgpod/commit/27955cc4415c39f520f3674c9d1989d28e9b8670
> build: Add patch for libgpod mac build.

- src/playlistparsers/cueparser.cpp
Most specs have mm:ss:ff as the index time format, but cue files have
been found with single digit minutes. e.g. 0:00:00 instead of 00:00:00
Reference: https://www.gnu.org/software/ccd2cue/manual/html_node/CUE-sheet-format.html
This is a fix for #7042
> cueparser: Be more lenient when parsing indexes.

- src/core/player.cpp
- src/core/player.h
- src/core/urlhandler.h
- src/internet/digitally/digitallyimportedurlhandler.cpp
- src/internet/googledrive/googledriveurlhandler.cpp
- src/internet/intergalacticfm/intergalacticfmurlhandler.cpp
- src/internet/radiobrowser/radiobrowserurlhandler.cpp
- src/internet/somafm/somafmurlhandler.cpp
- src/internet/subsonic/subsonicurlhandler.cpp
In a case where a playlist is composed entirely of unresolvable
internet service URLs and the playlist is set to repeat, playing an
item will result in an infinite (until crash) recursive condition.
HandleLoadResult is called with a NoMoreTracks result. It then calls
NextItem, which calls PlayAt for the next item, which, again, calls
HandleLoadResult.
This can be reproduced by logging into a subsonic server, adding items
to an empty playlist, then signing out.
To solve this, separate the error condition from the NoMoreTracks
result. Handle URL resolution errors the same way that media playback
errors are handled, where an error count is incremented and the player
stops if a limit is reached. The common code also notifies the playlist
of the error and provides user feedback by graying out …
> player: Fix crash on UrlHandler error.

- src/CMakeLists.txt
- src/transcoder/transcoderoptionsavaac.cpp
- src/transcoder/transcoderoptionsavaac.h
- src/transcoder/transcoderoptionsavaac.ui
- src/transcoder/transcoderoptionsdialog.cpp
Initially adding encoder and bitrate settings, but the gstreamer
element exposes a lot of ffmpeg options that can be added as needed.
Reference: https://gstreamer.freedesktop.org/documentation/libav/avenc_aac.html
Fix for #7049
> transcoder: Add options avenc_aac element.

- src/devices/cddadevice.h
- src/devices/gpoddevice.h
- src/devices/mtpdevice.h
- src/internet/core/cloudfileservice.h
- src/internet/googledrive/googledriveservice.h
- src/internet/skydrive/skydriveservice.h
The existing master cannot be built by clang, because it enforces all overrided virtual functions are specified with the "override" keyword.
The problem is now fixed after adding all those missing keywords
> Allow developer to use clang for the compilation

- src/globalsearch/digitallyimportedsearchprovider.cpp
- src/internet/core/cloudfilesearchprovider.cpp
- src/internet/core/cloudfileservice.cpp
- src/internet/core/cloudfileservice.h
- src/internet/digitally/digitallyimportedservicebase.cpp
- src/internet/digitally/digitallyimportedservicebase.h
- src/internet/dropbox/dropboxservice.cpp
- src/internet/googledrive/googledriveservice.cpp
- src/internet/seafile/seafileservice.cpp
- src/internet/skydrive/skydriveservice.cpp
InternetService::ShowConfig() and ShowSettingsPage() in various classes
were all used to show the settings page for a service. Consolidate these
to override the ShowConfig method in the base class.
> internet: Consolidate ShowConfig methods.

- src/core/deletefiles.cpp
- src/core/organise.cpp
TaskManager::SetTaskBlocksLibraryScans() takes the ID of the task.
> Fix setting task blocking library scans

- ext/libclementine-common/core/closure.h
- src/musicbrainz/tagfetcher.cpp
- tests/concurrentrun_test.cpp
To avoid a race condition, it is important to call setFuture() after doing the connections.
See: https://doc.qt.io/qt-6/qfuturewatcher.html
> Fix incorrect use of QFutureWatcher

- src/internet/subsonic/subsonicservice.h
- src/library/librarymodel.h
Q_ENUMS is obsolete. See: https://doc.qt.io/qt-5/qobject-obsolete.html
The replacement is Q_ENUM which was introduced in Qt 5.5, and Clementine
requires Qt 5.6.
> Replace Q_ENUMS with Q_ENUM

- src/internet/podcasts/podcastservice.cpp
- src/internet/podcasts/podcastservice.h
When a podcast is updated and the number of visible items is set in the
podcast settings, child items that disappear from the view, and are
deleted, are still referenced by the database id map.
Move the removal code from SubscriptionRemoved to a common method and
use that for this case.
> internet/podcasts: Fix crash when updating podcasts.

- src/CMakeLists.txt
- src/core/organiseformat.cpp
- src/core/organiseformat.h
- src/ripper/ripcddialog.cpp
- src/ripper/ripcddialog.h
- src/ripper/ripcddialog.ui
- src/ripper/ripper.cpp
- src/ripper/ripper.h
- src/transcoder/transcoder.cpp
- src/transcoder/transcoder.h
- src/ui/organisedialog.cpp
- src/ui/organisedialog.h
- src/ui/organisedialog.ui
- src/widgets/filenameformatwidget.cpp
- src/widgets/filenameformatwidget.h
- src/widgets/filenameformatwidget.ui
Previously we had very different UI and inconsistent logic for file name formatting in the CD ripping dialog compared to the organise files dialog window. This change set unifies the UI by moving the file formatting UI elements of the organise files dialog into a distinct widget that is then re-used in the CD ripping dalog.
Further changes:
- filename preview in CD ripping dialog
- Transcoder now creates folders along the output paths if they don't already exist
- Transcoder::AddJob now accepts an optional flag to overwrite existing files (defaults to `false`)
- CD ripping dialog was not correctly loading (and not at all storing) the chosen transcoder preset
> File formatting options in CD ripping dialog now consistent with organise files dialog

- ext/libclementine-common/CMakeLists.txt
- ext/libclementine-common/core/conf_backtrace.h.in
- ext/libclementine-common/core/logging.cpp
The Q_OS_UNIX macro is inappropriate for detection because many UNIX-like
platforms may lack backtrace support in the libc. E.g.: Darwin / Mac OS X,
Musl libc, OpenBSD, OpenIndiana.
> Enable to build on systems lacking execinfo.h

- src/musicbrainz/musicbrainzclient.cpp
- src/ripper/ripcddialog.cpp
- src/ripper/ripcddialog.h
This amends/fixes PR #7078 : Editing the values in the album metadata edits previously did affect the tags of the transcoded files, but was not reflected in file names/paths and the file name prefix. This is now fixed.
As an additional small fix: MusicBrainzClient was producing an IO error when the connection timed out (while trying to read an error response, which in this case did not exist).
> Cd ripper file formatting fixes

- src/widgets/tracksliderslider.cpp
This fixes [this bug I reported to the Debian bug tracker](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=981225) where the tooltip when hovering over the seekbar isn't *quite* right. I thought it was exactly one pixel off, but once I fixed that, there was also a rounding error that went away when I moved the `/ kMsecPerSec` to outside the call to `QStyle::sliderValueFromPosition`.
The code says it's based on [QSliderPrivate::pixelPosToRangeValue](https://github.com/qt/qtbase/blob/9db7cc79a26ced4997277b5c206ca15949133240/src/widgets/widgets/qslider.cpp#L100), so I looked at that code and [its callsite used to process a mouse click](https://github.com/qt/qtbase/blob/9db7cc79a26ced4997277b5c206ca15949133240/src/widgets/widgets/qslider.cpp#L377) to adjust the code to match that logic more …
> Correct time computation for seekbar tooltip.

- src/playlistparsers/xspfparser.cpp
Is there something wrong with using the content of the `image` element as a manually set artwork location?
I've tested it with Tidal cover art and it worksforme™.
> Use XSPF image elements as manually set artwork

- .github/workflows/all.yml
- .github/workflows/translations.yml
transifex-client indirectly requires Unidecode>=0.04.16. As of version
1.3.2, Unidecode no longer supports Python 2. Its setup shebang points
to /usr/bin/python, which it assumes is python3. To correct the issue,
install pip3 instead of pip, avoiding the installation of Python 2.
If running transifex-client with python3 is undesirable, manually installing Unidecode==1.2.0 should also be a workable solution.
> build: Fix translations

- src/core/songloader.cpp
- src/core/songloader.h
- src/devices/cddadevice.cpp
- src/devices/cddadevice.h
- src/devices/cddasongloader.cpp
- src/devices/cddasongloader.h
- src/ripper/ripcddialog.cpp
- src/ripper/ripcddialog.h
In `CddaSongLoader::LoadSongsFromCdda`: I changed the gstreamer source element to `cdiocddasrc` (from uri source), which includes metadata from CD-Text in the tag message for each track and seek through all the tracks. On a high level `LoadSongsFromCdda` now works as follows:
1. read the number of tracks, emit `SongsLoaded` (unchanged)
2. handle TOC message, update song durations, emit `SongDurationLoaded` (unchanged)
3. seek through tracks, fetch CD-Text metadata, emit `SongMetadataLoaded` (new)
4. emit `MusicBrainzDiscIdLoaded`
5. fetch metadata from musicbrainz and emit `SongMetadataLoaded` (as reaction to `MusicBrainzDiscIdLoaded`)
The benefits are that, if CD-Text is present on the disc, at least some metadata are still available even if the user does not have Internet connectivity …
> CddaSongLoader now reads tags from CD-Text

- src/engines/gstenginepipeline.cpp
@jonaski reported in PR #7101 of getting an error for removal of the bus callback there (see the [direct link](https://github.com/clementine-player/Clementine/pull/7101#issuecomment-950403314) to that post for details ).
The cause was the following: Since the callback as it was implemented returned false, it was removed from the bus after its first invocation (cf. "The watch can be removed using gst_bus_remove_watch or by returning FALSE from func.", [Gstreamer docs](https://gstreamer.freedesktop.org/documentation/gstreamer/gstbus.html?gi-language=c#gst_bus_add_watch)), which is not what we want there.
Fixed in this PR by making the callback return true instead.
> Fix: GstEnginePipeline BusCallback erroneously returned false.

- src/engines/gstenginepipeline.cpp
Reverts clementine-player/Clementine#7112
See https://github.com/clementine-player/Clementine/issues/7115
> Revert "Fix: GstEnginePipeline BusCallback erroneously returned false."

- src/transcoder/transcodedialog.cpp
- src/transcoder/transcodedialog.ui
This behavior is enabled via a new checkbox in the transcoder dialog.
When enabled, transcoding will replace original files if the transcoded file would end up with the same path name (same format/extension and destination "alongside the originals"). In all other cases, the original files will simply be deleted after successful transcoding.
If transcoding of a file fails for any reason, the original will not be deleted/replaced.
Requested in #7110 .
> Added option to remove/replace originals in transcoder dialog.

- src/transcoder/transcodedialog.cpp
- src/transcoder/transcodedialog.ui
This is a squashed and fixed version of previous commits
6b6547095ac60b6e4c9113fffdfa9b5e945bb9b0
dd1393ea3ab5ae58aff8f8cc444aee3c8e4830fb
from previously merged PR #7118 which failed to build due to incompatible changes made to master between opening and merging the PR. Sorry for that @hatstand
> Added option to remove/replace originals in transcoder dialog (fixed).

- src/analyzers/analyzerbase.cpp
- src/analyzers/blockanalyzer.cpp
- src/analyzers/blockanalyzer.h
The block analyzer was doing lots of repeated, out-of-order blits to the
widget's canvas. To improve performance and reduce CPU usage, this has
been rewritten to generate the canvas contents using only a single buffer.
Cache thrashing has been greatly reduced by writing to memory only
sequentially and in one single write pass. Further, the raw format is
now guaranteed to be in a format efficient for Qt.
The results are visually identical to what they were previously, but
result in a CPU usage reduction between 2 and 6 percent depending on refresh
rate and Psychadelic Mode value. In particular, there used to be a ~3 percent
overhead for Psychadelic Mode, and this has been eliminated.
The specific details of the block analyzer and explanations for how it works
(and used to work) have been …
> Rewrite the Block Analyzer to improve performance.

- src/internet/digitally/digitallyimportedservicebase.cpp
These two audio addict feeds do support premium -- Perhaps they didn't previously. This changes fixes the playlist not loading for me on a local build.
This was changed in https://github.com/clementine-player/Clementine/issues/4582
> Fix ClassicalRadio.com and ROCKRADIO.com #5616

- src/ui/mainwindow.cpp
I believe that skipping through playlists to find a song unfairly increments a song's skip counter and negatively impacts the score. This feature would help eliminate this issue.
> Count song skips if song listened to for >5 seconds

- CMakeLists.txt
- src/core/organiseformat.h
- src/internet/digitally/digitallyimportedservicebase.h
- src/internet/icecast/icecastservice.h
- src/internet/intergalacticfm/intergalacticfmservice.h
- src/internet/internetradio/savedradio.h
- src/internet/jamendo/jamendoservice.h
- src/internet/magnatune/magnatuneservice.h
- src/internet/podcasts/podcastservice.h
- src/internet/radiobrowser/radiobrowserservice.h
- src/internet/somafm/somafmservice.h
- src/internet/subsonic/subsonicservice.h
- src/library/librarybackend.cpp
- src/moodbar/moodbarbuilder.cpp
- src/playlist/playlist.cpp
- src/ripper/ripper.cpp
I had to disable `-Werror` in the default compiler settings for `-DCMAKE_BUILD_TYPE=RelWithDebInfo` to build with clang16, and I disliked that. So, I fixed all the showstoppers. None of them were critical, but overall, they increase readability, reduce probability of future bugs. The struct vs class fwd declaration *might* be problematic on MSVC, anyways, fixed that, no reason not to.
Also, moved the CMake version check in front of the project definition.
- CMake: Check for minimum version before setting the project name
- core/organisefmt: use same visibility for fwd decl as in def
- internet services: consistently use 'override'
- library: use boolean, not bitwise, operator on bools
- src: remove unused variable
> Fix Compile Warnings

- .github/workflows/all.yml
- CMakeLists.txt
- dist/clementine.spec.in
This seem to have gone broken over time.
As far as I can tell, upstream QtSingleApplication works fine!
Signed-off-by: Marcus Müller <marcus_clementine@baseband.digital>
> CMake: Re-enable usability of system QtSingleApplication

- src/internet/subsonic/subsonicservice.cpp
Subsonic API supports multi-genre and multi-artist tags for an album.
These tags are currently not expected by Clementine Subsonic service parser and will cause abort of the library scan if present.
This patch simply skips them, allowing the scan to continue.
> Skip subsonic multi-genre tags

- README.md
uses `nproc` instead of assuming 8 cores
> Update Compile Instructions

- CMakeLists.txt
Do not hardcode C++ runtime regardless of compiler being used: only Clangs use `libc++` by default, not GCC.
> CMakeLists: use --stdlib=libc++ on macOS only with clang

- .github/workflows/all.yml
As of writing, Clementine has a build-time requirement in the GitHub Action to sha2-devel (but only for Fedora), but there is no source code in Clementine (anymore?) that actually includes `sha2.h` provided by sha2-devel.
I'm suggesting the same change downstream: https://src.fedoraproject.org/rpms/clementine/pull-request/4
> Remove unused build-time requirement to sha2-devel

- ext/libclementine-tagreader/cloudstream.cpp
- ext/libclementine-tagreader/cloudstream.h
- ext/libclementine-tagreader/tagreader.cpp
Simply the combination of both patches from #7314 for easy merge
> Support both taglib-1 and taglib-2

- ext/libclementine-tagreader/cloudstream.cpp
> Fix build failure on 32-bit with taglib 2

- src/library/libraryquery.cpp
- src/library/libraryquery.h
> Filter tracks by length with tokens similar to lastplayed etc.
