clementine-player/Clementine

- Changelog
I made a draft of the changelog after the release 1.2.3 to help users to see what modifications were made and to help authors when they'll want to release a new version of Clementine.
My english is not perfect, I certainly missed some things and maybe some other features should be in major feature (or the opposite) so feel free to correct it :)
Note: I didn't include commits for the Clementine remote application.
> Update the changelog (commits after release 1.2.3)

- ext/libclementine-tagreader/tagreader.cpp
> Add performer tag support for mpeg files

- src/core/player.h
- src/core/utilities.cpp
- tests/utilities_test.cpp
I couldn't stand the regexp hell, so I have removing it altogether.
Some minor style changes
> Add ability to parse more of "innovative" datetime formats. close #4760

- README.md
Fixed some typos/mistakes and improved sentence structure/readability in "Report a bug" paragraph
> Update "Report a bug" in README.md

- src/ui/about.cpp
- src/ui/about.ui
Am I worthy? I know it's only been a year, but it would mean a lot to me.
I completely understand otherwise.
I also bumped the height up a tad so that no text gets cut off due to the extra line.
> I just remembered we have an about box

- src/internet/subsonic/subsonicservice.cpp
- src/internet/subsonic/subsonicservice.h
I think it's better if the songs  are removed when the user changes the subsonic server or disconnects
> Fix crash when Clementine lists albums of Ampache et remove subsonic songs when the user disconnects

- src/core/player.cpp
- src/networkremote/outgoingdatacreator.cpp
- src/playlist/playlist.cpp
- src/playlist/playlistsequence.cpp
- src/playlist/playlistsequence.h
- src/widgets/osd.cpp
It's very useful to have such mode for concerts or performances when you have ordered list of tracks and starts them as performance go.
> Add stop after each song repeat mode

- src/core/player.cpp
- src/networkremote/outgoingdatacreator.cpp
- src/playlist/playlist.cpp
- src/playlist/playlistsequence.cpp
- src/playlist/playlistsequence.h
- src/widgets/osd.cpp
Reverts clementine-player/Clementine#4850
> Revert "Add stop after each song repeat mode"

- ext/libclementine-remote/remotecontrolmessages.proto
- src/core/player.cpp
- src/networkremote/outgoingdatacreator.cpp
- src/playlist/playlist.cpp
- src/playlist/playlistsequence.cpp
- src/playlist/playlistsequence.h
- src/playlist/playlistsequence.ui
- src/widgets/osd.cpp
I've fixed build failures. Sorry for inconvenience.
Some changes was made by make format in areas of code which I haven't modified.
> Stop after each track

- src/library/groupbydialog.ui
Closes https://github.com/clementine-player/Clementine/issues/4812 https://github.com/clementine-player/Clementine/issues/3225
> Add ability for sort by group and performer in the library view

- ext/libclementine-remote/remotecontrolmessages.proto
- src/core/player.cpp
- src/core/player.h
- src/engines/engine_fwd.h
- src/engines/gstengine.cpp
- src/networkremote/outgoingdatacreator.cpp
- src/playlist/playlist.cpp
- src/playlist/playlistsequence.cpp
- src/playlist/playlistsequence.h
- src/playlist/playlistsequence.ui
- src/ui/mainwindow.cpp
- src/ui/mainwindow.h
- src/widgets/osd.cpp
This repeat mode plays the beginning of each track, good for quickly getting a feel for a new album for example. An inferior music player I used to use had this and I found it quite useful.
> Add track intro mode

- ext/libclementine-remote/remotecontrolmessages.proto
- src/core/player.cpp
- src/core/player.h
- src/engines/engine_fwd.h
- src/engines/gstengine.cpp
- src/networkremote/outgoingdatacreator.cpp
- src/playlist/playlist.cpp
- src/playlist/playlistsequence.cpp
- src/playlist/playlistsequence.h
- src/playlist/playlistsequence.ui
- src/ui/mainwindow.cpp
- src/ui/mainwindow.h
- src/widgets/osd.cpp
Reverts clementine-player/Clementine#4903
> Revert "Add track intro mode"

- src/smartplaylists/searchtermwidget.cpp
If no we can't add new fields without the mouse, which could cause some problems to blind people for example.
> Add ability to add a search term with tab and space in the smart playlist window

- src/core/globalshortcuts.cpp
- src/core/globalshortcuts.h
- src/internet/lastfm/lastfmservice.cpp
- src/ui/mainwindow.cpp
> Add love/ban (lastfm) global shortcuts

- src/core/song.cpp
Reverts clementine-player/Clementine#4934
> Revert "Send album artist to Last.fm"

- ext/libclementine-tagreader/tagreader.cpp
Softened the metadata-editor behavior to not deliberately delete additional, valid frames which are stored in mp3-files.
This fixes also a few bug reports because the Clementine metadata-editor could actually lead to losing valid data from an mp3-file(!) STILL the metadata-editor does not show further frames or allows to edit them but at least it also does not remove them anymore.
Stashed commit of the following:
01c71c4c67be44dd6889498abc323a6d2d20dd99
Added description "Clementine editor" to new created lyrics frames.
70dfa0d1f177523ff897985ae022979cd052a6ed
Updated the SetTextFrame method as well:
Existing frames are cached and only the first frame (which is actually shown in the metadata editor) will be updated.
Prevents the cruel deletion of all other existing frames in a well …
> Cache and restore further mp3-file metadata-frames instead of cruel deletion

- src/widgets/trackslider.cpp
> Fix track slider twitching

- src/internet/vk/vkservice.cpp
- src/internet/vk/vkservice.h
> Fix vk.com search

- src/internet/digitally/digitallyimportedurlhandler.cpp
> Fix Di.fm stations stuck when try them to play without internet.

- src/widgets/nowplayingwidget.cpp
Needs to show on the monitor Clementine is currently on.
> Bask in his glory on multiple monitors

- src/core/player.cpp
- src/core/urlhandler.h
- src/internet/subsonic/subsonicurlhandler.cpp
- src/internet/vk/vkservice.cpp
- src/internet/vk/vkurlhandler.cpp
> Fixed checking of the original url in Player::HandleLoadResult()

- src/core/utilities.cpp
> Workaround for malfunctioning "Show in file browser" feature in Linux

- src/internet/vk/vkservice.cpp
> Fix inability to disable vk autocaching

- data/lyrics/ultimate_providers.xml
Tekstowo.pl offers lyric in original language of song and polish translation. I just added polish translation option as another provider based on tekstowo.pl
> Polish translations provider 

- src/globalsearch/globalsearchview.cpp
> change help_text QPalette to WindowText

- src/library/libraryview.cpp
@ArnaudBienner could you please check if the alpha level is ok ? or should i tweak the value ?
> make library view sort line themable

- src/ui/behavioursettingspage.cpp
- src/ui/behavioursettingspage.ui
- src/ui/mainwindow.cpp
- src/ui/mainwindow.h
see https://github.com/clementine-player/Clementine/pull/4991#issuecomment-140082879
> consolidated the options for double clicking a playlist

- Changelog
- src/internet/seafile/seafileservice.cpp
- src/internet/seafile/seafilesettingspage.cpp
See https://github.com/haiwen/seahub/issues/677
> Fix byte range requests with seafile (server >= 4.4.1)

- src/playlistparsers/cueparser.cpp
- src/playlistparsers/cueparser.h
> Makes Clementine read "REM DISCNUMBER" from CUE.

- src/playlist/playlistheader.cpp
- src/playlist/playlistheader.h
- src/playlist/playlistview.cpp
- src/playlist/playlistview.h
> Lock/Unlock Ratings edit status

- src/playlist/playlistheader.cpp
- src/playlist/playlistheader.h
- src/playlist/playlistview.cpp
- src/playlist/playlistview.h
Reverts clementine-player/Clementine#5077
> Revert "Lock/Unlock Ratings edit status"

- src/ui/mainwindow.cpp
I was trying to solve #286 but found that was not related to clementine. This patch remembers the normal window state geometry 
issue:
1. open clementine 
2. re-size clementine to the users liking
3. maximize window
4. quit
5. reopen clementine(will open as maximized window)
6. re-size to normal mode
result:
clementine don't remember previous normal window state geometry..
> remember normal window state when user closes clementine in maximized state

- src/widgets/tracksliderslider.cpp
- src/widgets/tracksliderslider.h
> Mouse wheel track slider Seeking

- data/lyrics/ultimate_providers.xml
- tools/ultimate_lyrics_parser/sites.js
> Add bollywoodlyrics.com & hindilyrics.net as lyrics providers for bollywood songs

- src/analyzers/analyzerbase.cpp
- src/analyzers/analyzerbase.h
- src/analyzers/baranalyzer.cpp
- src/analyzers/boomanalyzer.cpp
- src/analyzers/sonogram.h
- src/analyzers/turbine.cpp
1) Fix boom analyzer, terbine flickering when paused
2) Freeze bar analyzer when paused
> Fix boom analyzer, terbine & bar analyzer behaviour when paused

- src/library/libraryview.cpp
- src/widgets/groupediconview.cpp
> Make a slight modification to library view line & preferences header line

- src/internet/vk/vkservice.cpp
> Fix duplicate items under vk.com after login.

- src/CMakeLists.txt
- src/library/libraryfilterwidget.cpp
- src/library/libraryfilterwidget.h
- src/library/libraryfilterwidget.ui
- src/library/librarymodel.cpp
- src/library/librarymodel.h
- src/library/savedgroupingmanager.cpp
- src/library/savedgroupingmanager.h
- src/library/savedgroupingmanager.ui
This obviously depends on PR #5152
> Add dialog for managing saved files

- src/internet/digitally/digitallyimportedservicebase.cpp
As suggested in https://github.com/clementine-player/Clementine/pull/5193
> show settings dialog for difm when populate streams without a premium account

- src/widgets/sliderwidget.cpp
> use normal text color for volume

- src/playlist/playlistcontainer.cpp
- src/playlist/playlistcontainer.ui
> Remove unwanted lines from playlistcontainer

- src/covers/currentartloader.cpp
- src/globalsearch/globalsearchmodel.cpp
- src/internet/spotify/spotifyservice.cpp
- src/library/librarymodel.cpp
- src/library/libraryview.cpp
- src/playlist/playlistcontainer.cpp
- src/playlist/playlistview.cpp
- src/ui/albumcovermanager.cpp
- src/ui/edittagdialog.cpp
- src/ui/iconloader.cpp
- src/ui/iconloader.h
- src/ui/notificationssettingspage.cpp
- src/ui/systemtrayicon.cpp
- src/widgets/favoritewidget.cpp
- src/widgets/ratingwidget.cpp
> Use icon loader for remaining icons

- ext/clementine-tagreader/CMakeLists.txt
- src/CMakeLists.txt
2792bce fix for:
http://pastebin.com/XJQbK21W
b2db55e fix for:
http://pastebin.com/pZKzdcX1
> Fix mxe linking

- src/engines/gstenginepipeline.cpp
Assuming there is a bug in GStreamer's implementation of the first and last bands of the equalizer, we now set up two dummy bands, cutting to 20Hz and from 20KHz, and with a bandwidth of 0 (what makes them dummies). That forces all actual bands to be implemented with band-pass filters, avoiding GStreamer's possibly-buggy shelve-filters implementation and preventing #695.
> Add dummy bands to avoid #695

- src/covers/albumcoverloader.cpp
- src/covers/albumcoverloader.h
- src/internet/subsonic/subsonicservice.cpp
- src/internet/subsonic/subsonicservice.h
Hey, just rebased and fixed some stuff, hope you guys are able to merge this.
Thanks for your work!
> Adding support for subsonic cover art download

- src/covers/albumcoverloader.cpp
- src/covers/albumcoverloader.h
- src/internet/subsonic/subsonicservice.cpp
- src/internet/subsonic/subsonicservice.h
Reverts clementine-player/Clementine#5270
> Revert "Adding support for subsonic cover art download"

- ext/clementine-spotifyblob/main.cpp
- src/main.cpp
If we compile spotify blob ourselves.
> [Qt5] Fix spotify blob config path

- src/engines/gstenginepipeline.cpp
Fixes #1747
The pipeline currently has the caps for the analyzer override the autonegotiation of the audio pipeline caps. This results in the audio output being limited to 16 bit regardless of the input file bit depth.
This change also cleans up the mono/sample rate caps as well.
> Fix caps on audio pipeline

- src/core/signalchecker.cpp
- src/core/signalchecker.h
- src/devices/giolister.cpp
- src/devices/giolister.h
> disconnect GVolumeMonitor signals from GioLister before destroying it

- CMakeLists.txt
- src/CMakeLists.txt
- src/config.h.in
- src/core/metatypes.cpp
- src/dbus/metatypes.h
- src/dbus/org.freedesktop.DBus.ObjectManager.xml
- src/dbus/org.freedesktop.UDisks2.Block.xml
- src/dbus/org.freedesktop.UDisks2.Drive.xml
- src/dbus/org.freedesktop.UDisks2.Filesystem.xml
- src/dbus/org.freedesktop.UDisks2.Job.xml
- src/devices/devicemanager.cpp
- src/devices/udisks2lister.cpp
- src/devices/udisks2lister.h
> Udisks2 support

- ext/libclementine-tagreader/tagreader.cpp
TagLib::Ogg::XiphComment now handles METADATA_BLOCK_PICTURE separately from other fields. Thus, we have to use XiphComment::pictureList() in order to get cover art.
> Fix fetching cover art for taglib >= 1.11

- src/smartplaylists/searchterm.cpp
> Encode file paths in smart playlists

- src/core/commandlineoptions.cpp
- src/core/commandlineoptions.h
- src/ui/mainwindow.cpp
Hi!
I've prepared a patch for #5373, but I'm not sure in new option naming.
So, if there are suggestions I will be glad to hear them.
> Add new command line option for creating a new one playlist #5373

- src/ui/mainwindow.cpp
- src/ui/mainwindow.ui
Add a checkable button (*Playlist->Show sidebar*) that allows the playlist container to use the complete width of the window.
> Add option to show/hide sidebar

- src/musicbrainz/chromaprinter.cpp
See https://github.com/acoustid/chromaprint/blob/master/NEWS.txt#L7
I did not find a more elegant solution, I'm open to suggestions.
> Fix compilation with chromaprint >= 1.4

- src/playlist/playlist.cpp
- src/playlist/playlist.h
A sample output would be:
- /Music/a.mp3
- /Music/c.mp3
- /Music/Brooklyn/b.mp3
- /Music/Brooklyn/z.mp3
- /Music/Charlie/a.mp3
- /Music/Charlie/e.mp3
- /Music/Brooklyn/X/l.mp3
>  Consider depth levels in path sorting (#5445)

- 3rdparty/qtwin/CMakeLists.txt
log: https://gist.github.com/pavelvat/8eb1392605ae47a1a37a7210bc07b29d
> fix build (Qt5) qtwin

- 3rdparty/qsqlite/CMakeLists.txt
log: https://gist.github.com/pavelvat/ecea3bffce610cc9da8cefa6bbe75114
> fix linking qsqlite

- src/ui/windows7thumbbar.cpp
- src/widgets/osdpretty.cpp
http://jpnurmi.kapsi.fi/blog/2012/11/13/qpixmaptowinhicon-in-qt5/
logs:
https://gist.github.com/pavelvat/54c99441a5971e7663034d185428e3ae 
https://gist.github.com/pavelvat/b76eff38b43863a18e6dd92cefa67e48
> Fix windows7thumbbar.cpp and osdpretty.cpp

- src/core/songloader.cpp
- src/core/songloader.h
- src/core/utilities.cpp
- src/core/utilities.h
- src/playlistparsers/playlistparser.cpp
- src/playlistparsers/playlistparser.h
- src/playlistparsers/plsparser.h
As reported in #4977, #5659, #5399 and many others, the loading of remote playlists was broken.
These changes seek to fix that.
> Fix remote-playlist load

- src/ui/iconloader.cpp
This fixes a bug when clementine uses an icon from the system, even though it exists in it the *data* folder.
For example: the icons at the top of *playlistlistview.ui*, and at the top of *fileview.ui*
> Simpler iconloader::Load() logic

- src/playlist/playlistview.cpp
> fix up key in playlist

- src/widgets/osd_x11.cpp
This should fix #5756 and #3211.
> Add 'transient' hint to OSD_X11

- src/ui/appearancesettingspage.cpp
It looks like there is a problem with build of src/ui/appearancesettingspage.cpp
It might fix it.
Don't have a way to test it, still setting up my win32 build environment.
> [win32] Fix build in src/ui/

- src/internet/lastfm/lastfmsettingspage.cpp
> Spelling: Log in, Last.fm

- src/internet/lastfm/lastfmservice.cpp
As per https://en.wikipedia.org/wiki/URL  (Uniform Resource Locator)
> Spelling: URL

- src/core/song.cpp
As per https://xiph.org/flac/ (Free Lossless Audio Codec)
> Spelling: FLAC

- src/transcoder/transcoder.cpp
As per https://xiph.org/flac/ (Free Lossless Audio Codec)
> Spelling: FLAC elsewhere

- README.md
https://en.wikipedia.org/wiki/MacOS
> Rename Mac OS X to macOS in README.md

- src/internet/subsonic/subsonicdynamicplaylist.cpp
- src/internet/subsonic/subsonicservice.cpp
Add cover art support for music played from subsonic servers
> Subsonic: download cover art

- src/internet/lastfm/lastfmservice.cpp
Fixes https://github.com/clementine-player/Clementine/issues/5993#issuecomment-366507718
> Fix "Invalid key" error in lastfm auth

- src/widgets/tracksliderpopup.cpp
- src/widgets/tracksliderpopup.h
- src/widgets/tracksliderslider.cpp
- src/widgets/tracksliderslider.h
Reverts clementine-player/Clementine#6000
> Revert "Hide TrackSliderPopup on exit from popup instead of from TrackSliderSlider"

- ext/libclementine-remote/remotecontrolmessages.proto
- ext/libclementine-tagreader/tagreader.cpp
- ext/libclementine-tagreader/tagreadermessages.proto
- src/core/song.cpp
- src/core/song.h
This fixes issue #3003 and #2526
> Fix WavPack playback

- data/lyrics/ultimate_providers.xml
> add genius.com as lyrics provider

- src/devices/cddasongloader.cpp
- src/devices/cddasongloader.h
- src/ripper/ripcddialog.cpp
- src/ripper/ripcddialog.h
- src/ripper/ripper.cpp
- src/ripper/ripper.h
> Add musicbrainz integration to the cd ripper

- src/playlist/playlistview.cpp
- src/ui/mainwindow.cpp
- src/widgets/trackslider.cpp
- src/widgets/trackslider.h
- src/widgets/tracksliderslider.cpp
- src/widgets/tracksliderslider.h
Added mouse forward and backward button handling to playlistview and trackslider to jump to previous and next track.
> Added mouse forward and back button actions.

- src/core/mpris2.cpp
See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=898998#29 for more
information.
> Emit notifications when CanPlay/CanPause change

- src/ui/mainwindow.cpp
- src/ui/systemtrayicon.cpp
- src/widgets/osd.cpp
This should fix issue #6041 among others
> Only use system tray if it's available on the system

- src/analyzers/analyzerbase.cpp
> Fix crash in analyzer

- 3rdparty/taglib/CMakeLists.txt
- 3rdparty/taglib/audioproperties.cpp
- 3rdparty/taglib/dsdiff/dsdiffdiintag.cpp
- 3rdparty/taglib/dsdiff/dsdiffdiintag.h
- 3rdparty/taglib/dsdiff/dsdifffile.cpp
- 3rdparty/taglib/dsdiff/dsdifffile.h
- 3rdparty/taglib/dsdiff/dsdiffproperties.cpp
- 3rdparty/taglib/dsdiff/dsdiffproperties.h
- 3rdparty/taglib/dsf/dsffile.cpp
- 3rdparty/taglib/dsf/dsffile.h
- 3rdparty/taglib/dsf/dsfproperties.cpp
- 3rdparty/taglib/dsf/dsfproperties.h
- 3rdparty/taglib/fileref.cpp
- 3rdparty/taglib/mpeg/id3v2/frames/tableofcontentsframe.cpp
- 3rdparty/taglib/mpeg/id3v2/frames/textidentificationframe.cpp
- 3rdparty/taglib/ogg/flac/oggflacfile.cpp
- 3rdparty/taglib/toolkit/tfile.cpp
- 3rdparty/taglib/toolkit/tfilestream.cpp
- 3rdparty/taglib/toolkit/tfilestream.h
The current master of taglib will most likely be the next release of taglib, see
https://github.com/taglib/taglib/issues/837
> Bump taglib

- src/library/libraryquery.cpp
This fixes a regression introduced in 8818ba340a.
> Fix library search queries on fts columns

- CMakeLists.txt
- ext/libclementine-common/core/workerpool.h
- src/CMakeLists.txt
- src/analyzers/analyzerbase.h
- src/analyzers/rainbowanalyzer.cpp
- src/analyzers/rainbowanalyzer.h
- src/config.h.in
- src/core/globalshortcuts.cpp
- src/core/gnomeglobalshortcutbackend.cpp
- src/core/metatypes.cpp
- src/covers/albumcoverloader.cpp
- src/covers/albumcoverloader.h
- src/engines/gstenginepipeline.cpp
- src/internet/core/internetmodel.cpp
- src/internet/spotify/spotifyservice.cpp
- src/main.cpp
- src/ui/mainwindow.cpp
- src/ui/mainwindow.h
- src/ui/settingsdialog.cpp
- src/widgets/osd.cpp
- src/widgets/osd.h
This adapts similar changes already done on the Qt 5 branch and also makes OpenGL optional.
I'm also removing QtWebKit, if it is needed for some reason, let me know and I'll add it back.
> Improvements to makefiles and make components optional

- snap/snapcraft.yaml
This snap has been published for some time. It's working well, though pretty ugly on non-KDE systems. Perhaps upstream can work on it/fix it. 
Let me know how I can help with the project.
> PR for Clementine snap

- data/lyrics/ultimate_providers.xml
* Fix "not found" detection.
* Also exclude footer.
> Update lyrics.com lyrics provider

- 3rdparty/qxt/qxtglobalshortcut_x11.cpp
Replace previous pull request with simpler version as suggested
> Compil fix for qxt third party

- ext/libclementine-tagreader/tagreader.cpp
- ext/libclementine-tagreader/tagreadermessages.proto
- src/core/song.h
Parse and write additional APEv2 fields.
> Improved support for APEv2 tags.

- src/engines/gstenginepipeline.cpp
There are a number of cases where gst_pipeline_get_bus,
gst_element_get_static_pad, and g_object_get are called without releasing
references. In addition to memory usage, some of these elements hold file
descriptors. In normal operation, two file descriptors are leaked for each
played track. The default fd ulimit for many linux distros is 1024. This
is likely the cause of the crash reported in issue 6309.
This change fixes the obvious and consistent leaks, but it's probably not a
complete solution. There are many error and corner conditions that need to be
examined.
> Fix several gstreamer object leaks.

- ext/libclementine-remote/remotecontrolmessages.proto
- src/core/mpris2.cpp
- src/core/song.cpp
- src/library/libraryquery.cpp
I *think* this is now all that was needed for APE files.
> More bits for APE files (Finish APE file support)

- src/playlist/playlistview.cpp
This makes the first column in the playlist viewer draggable.
> setFirstSectionMovable() in playlistview.cpp

- src/musicbrainz/chromaprinter.cpp
I cherry-picked a commit from master to fix the "Complete Tags Automatically" option.
More information about this issue can be [found here](https://github.com/clementine-player/Clementine/pull/6338).
> Fixed Complete Tags Automatically

- ext/libclementine-tagreader/tagreader.cpp
As of Qt 5.10 the badly named created() which would fall back to POSIX
ctime if birthtime wasn't supported (as was the case on basically every
Unix filesystem up to some decades ago) is deprecated and replaced by
the better named birthTime or metadataChangeTime (yay!).
As of some years now, created() returns birthtime under FreeBSD, but
either due to the protocol or lack of implementation, this returns -1
under FreeBSD mounting a ZFS pool from a FreeBSD server with NFSv3.
This would render Clementine completely useless. Local filesystems are
not affected though. The fix is to catch the -1 birthtime and use mtime
instead, which is a more meaningful value anyway.
This closes issue #6423.
> Fix Clementine on FreeBSD/NFS files, where birthtime is always -1

- snap/snapcraft.yaml
- Upgrade to core18
- Update dependencies to Qt 5
- Add proper alsa support
- Fix launch icon
- Fix missing plugs ie.: network-manager-observe
- Add plugs for clementine-tagreader
- Remove useless comments
> Fix and update snap

- 3rdparty/libmygpo-qt5/CMakeLists.txt
- 3rdparty/libmygpo-qt5/Mygpo-qtConfig.cmake.in
- 3rdparty/libmygpo-qt5/README
- 3rdparty/libmygpo-qt5/src/Podcast.cpp
- 3rdparty/libmygpo-qt5/src/UrlBuilder.cpp
- 3rdparty/libmygpo-qt5/src/UrlBuilder.h
- 3rdparty/libmygpo-qt5/src/qjsonwrapper/Json.cpp
The updates include:
- The ability to specify a custom gpodder service.
- Use https instead of http for gpodder.net.
- A fix that prevents encoded URLs from being re-encoded.
> Update to libmygpo-qt 1.1.0.

- CMakeLists.txt
> Add project to CMakeLists

- src/globalsearch/globalsearchmodel.cpp
- src/library/librarymodel.cpp
Fixes compiler warnings with extra flags. We already got these elsewhere.
> Add fallthrough comment where fallthrough is intended

- src/internet/seafile/seafileservice.h
- src/internet/seafile/seafiletree.cpp
- src/internet/seafile/seafiletree.h
Fixes a compile warning with -Wextra
> Initialize QObject in constructor and add explicit

- src/globalsearch/spotifysearchprovider.cpp
- src/internet/podcasts/gpoddersync.cpp
- src/library/librarybackend.cpp
- src/musicbrainz/musicbrainzclient.cpp
- src/playlist/playlist.cpp
- src/playlist/playlistmanager.cpp
QSet::toList() is deprecated, QSet::values() does the same.
See: https://doc.qt.io/qt-5/qset.html
> Replace QSet::toList() with QSet::values()

- src/internet/podcasts/gpoddersync.cpp
- src/internet/podcasts/gpoddersync.h
- src/internet/podcasts/podcastsettingspage.cpp
- src/internet/podcasts/podcastsettingspage.h
- src/internet/podcasts/podcastsettingspage.ui
Reverts clementine-player/Clementine#6497
Breaks mac build: https://circleci.com/gh/clementine-player/Clementine/2603
> Revert "Add an option to specify a gpodder server."

- src/library/librarybackend.cpp
- src/library/librarybackend.h
- src/library/librarydirectorymodel.cpp
- src/library/librarydirectorymodel.h
- src/library/librarywatcher.cpp
- src/library/librarywatcher.h
Eliminate need to create temporary Directory object when removing a directory.
> Remove directory by id.

- src/core/application.cpp
- src/core/application.h
- src/devices/deviceview.cpp
- src/internet/podcasts/podcastdownloader.cpp
- src/library/library.cpp
- src/library/library.h
- src/library/librarydirectorymodel.cpp
- src/library/librarydirectorymodel.h
- src/library/librarymodel.cpp
- src/library/librarymodel.h
- src/library/libraryview.cpp
- src/ui/mainwindow.cpp
- src/ui/settingsdialog.cpp
These changes remove several unused instances of LibraryDirectoryModel.
> Move directory model

- src/core/song.cpp
- src/core/utilities.cpp
- src/core/utilities.h
- src/library/librarybackend.cpp
- src/library/librarydirectorymodel.cpp
Fix loading songs on portable setup.
Not sure if there's still a use case for this setup.
> Fix portable setup

- src/main.cpp
Nvidia force close from 2011. Last driver version affected was 304.37, 304.83 is the last in the series and is from 2013.
macOS Soundcloud certificate - CA exists in the system bundle.
macOS font issue from 2013
Gnome volume control with Glib older than 2.36 - Debian Jessie, oldoldstable repo has 2.42
> Remove obsolete workarounds

- src/main.cpp
> use Qt's High DPI attribute

- ext/libclementine-common/core/logging.cpp
These changes remove the recursive calls to the registered handler, which Qt doesn't allow. Ultimately, it's a lot of words to get rid of the `__logging_message__` in the logs.
> Don't log magic header

- src/widgets/osdpretty.cpp
- src/widgets/osdpretty.h
> Fix osd crash

- ext/libclementine-tagreader/tagreader.cpp
Translation table in mp4tag.cpp for reference.
Fix for #6633
> Handle lyrics tag for mp4

- src/internet/subsonic/subsonicdynamicplaylist.cpp
- src/internet/subsonic/subsonicdynamicplaylist.h
- src/internet/subsonic/subsonicservice.cpp
- src/internet/subsonic/subsonicservice.h
These changes consolidate the duplicate song reading code.
> Subsonic cleanup

- ext/libclementine-common/core/lazy.h
- src/core/application.cpp
These changes fix the `Timers cannot be stopped from another thread` errors on exit.
> Timer error

- src/engines/gstengine.cpp
- src/engines/gstenginepipeline.cpp
Free buffer references in a couple error cases.
> Gst cleanup

- src/songinfo/ultimatelyricsprovider.cpp
- src/songinfo/ultimatelyricsprovider.h
Some clean-up and error logging in UltimateLyricsProvider. Added a 30s timeout to requests to prevent them from hanging.
> Ultimate lyrics cleanup

- src/widgets/freespacebar.cpp
- src/widgets/osdpretty.cpp
- src/widgets/sliderwidget.cpp
Adds #include <QPainterPath> to osdpretty.cpp, freespacebar.cpp, & sliderwidget.cpp to resolve issue https://github.com/clementine-player/Clementine/issues/6701
> Adds missing QPainterPath include

- src/devices/devicemanager.cpp
Since the SimpleTreeItem constructor variant used from LoadAllDevices adds the
object to the parent's children list, use the parent's Delete method to destroy
it.
> Properly delete ignored DeviceInfo object

- src/globalsearch/globalsearchsettingspage.cpp
- src/ui/notificationssettingspage.cpp
> Call SettingsPage::showEvent from child class implementations

- src/CMakeLists.txt
- src/ui/lovedialog.cpp
- src/ui/lovedialog.h
- src/ui/lovedialog.ui
- src/ui/mainwindow.cpp
- src/ui/mainwindow.h
Previously the Love button only worked for Lastfm play.
I modified it to work for local files too.
When the user clicks, they get a small dialog with the name of the playing track and a rating control.
Clicking on the rating (eg 4 stars of out 5) will:
- Save it in the mp3 file 
- Update the display in the current playlist (if has rating column)
- Close the dialog
> Share the love

- src/ui/mainwindow.cpp
Closes #6401
Never heard anyone on Win / OSX having a problem with this so might as well merge it finally.
> Fix logout cancelling

- src/engines/gstpipelinebase.cpp
- src/engines/gstpipelinebase.h
- src/transcoder/transcodedialog.cpp
- src/transcoder/transcodedialog.h
- src/transcoder/transcodelogdialog.ui
- src/transcoder/transcoder.cpp
- src/transcoder/transcoder.h
List current running transcode pipelines. This will be allow the addition of cancel and debug options. Specifically, I plan to add an option to dump the graph of a pipeline in an upcoming change.
> Add a pipeline list to the transcoder details dialog

- src/CMakeLists.txt
- src/engines/gstpipelinebase.cpp
- src/engines/gstpipelinebase.h
- src/engines/pipelineview.cpp
- src/engines/pipelineview.h
- src/transcoder/transcodedialog.cpp
- src/transcoder/transcodedialog.h
- src/transcoder/transcodelogdialog.ui
- src/transcoder/transcoder.cpp
- src/transcoder/transcoder.h
Add ListView derivative class for displaying GstPipelineModel data. A GetSelectedIds method provides the list of selected pipelie IDs. Add a "Dump Graph" menu option to the pipeline view if CLEMENTINE_DEBUG is enabled.
> Transcode pipeline dump

- .github/workflows/all.yml
https://wiki.ubuntu.com/GroovyGorilla
> build: Add Ubuntu 20.10 build

- .github/workflows/all.yml
> build: Add Mac Mojave build

- src/internet/core/cloudfileservice.cpp
- src/internet/core/cloudfileservice.h
- src/internet/googledrive/googledriveservice.cpp
- src/internet/googledrive/googledriveservice.h
- src/internet/skydrive/skydriveservice.cpp
- src/internet/skydrive/skydriveservice.h
Move some of Google Drive's rescan code to the base class and add a OneDrive rescan context menu item.
> Add onedrive rescan

- src/ui/settingscategory.cpp
- src/ui/settingscategory.h
- src/ui/settingsdialog.cpp
- src/ui/settingsdialog.h
This will allow future subclasses of SettingsCategory to populate their own pages.
Also removed an used enum value from SettingsDialog::Page.
> Move AddPage to SettingsCategory 

- src/engines/gstenginepipeline.cpp
When the decoder bin's src pad is added, only set caps to use the native bit depth if the the pipeline is not already running.
Fix for #6966
I plan on following this up with a settings option that allows the user to configure the depth.
> gstengine: Don't modify caps when pipeline is running

- ext/libclementine-tagreader/tagreader.cpp
Direct use of MP4::itemListMap() was deprecated in favor of using item() and
setItem(). XiphComment::removeField was replaced by removeFields.
> Discontinue use of deprecated taglib methods.

- src/core/songloader.cpp
- src/core/songloader.h
This is my first pull request ever, so forgive me if I did something wrong.
> Optimization to avoid save+delete of remote playlists to temporary file

- src/playlistparsers/m3uparser.cpp
Rather than assume UTF-8, use QTextStream to read data. This checks the byte order mark of the file to determine encoding.
As an optimization, since the playlist already needs to be searched for \r characters, just create a string list and work from that.
> playlistparsers: Handle m3u UTF-16 playlists.

- .github/workflows/all.yml
Reference: https://wiki.ubuntu.com/Releases
> build: Add Ubuntu Hirsute to workflows.

- src/translations/ca.po
- src/translations/eo.po
- src/translations/es.po
Trivial change to fix Transifex’s mess.
> De-duplicate my translator credit

- src/internet/core/cloudfileservice.cpp
- src/internet/core/cloudfileservice.h
- src/internet/core/internetservice.h
- src/internet/digitally/digitallyimportedservicebase.cpp
- src/internet/digitally/digitallyimportedservicebase.h
- src/internet/spotify/spotifyservice.h
- src/internet/subsonic/subsonicservice.cpp
- src/internet/subsonic/subsonicservice.h
This will allow some common handling of unconfigured services.
> internet: Add common InternetService::ConfigRequired() method.

- CMakeLists.txt
Generate compile_commands.json, a file which is read by clangd and many other IDE
> Generate compile_commands.json

- src/core/songloader.cpp
See: https://developer.gnome.org/gstreamer/stable/GstPipeline.html#gst-pipeline-get-bus
> Unref bus in SongLoader::LoadRemote()

- src/core/globalshortcuts.cpp
- src/devices/devicemanager.cpp
- src/devices/udisks2lister.cpp
- src/internet/digitally/digitallyimportedurlhandler.cpp
- src/library/libraryview.cpp
- src/playlist/queue.cpp
- src/ripper/ripper.cpp
- src/transcoder/transcoder.cpp
Adds missing emits.
QTreeView::collapse and QTreeView::expand are slots, not signals. So
remove emit.
> Fix use of emit

- ext/clementine-spotifyblob/CMakeLists.txt
- src/CMakeLists.txt
- src/globalsearch/spotifywebapisearchprovider.cpp
- src/globalsearch/spotifywebapisearchprovider.h
- src/internet/core/internetmodel.cpp
- src/internet/spotifywebapi/spotifywebapiservice.cpp
- src/internet/spotifywebapi/spotifywebapiservice.h
The old Spotify search is broken for a long long time. This new search provider tries to use the new Spotify API for the searching.
I will consider this is a version one. Any idea is totally welcome.
This is the first time ever I use the QT framework, Please let me know if I made any mistakes.
> Search with new spotify web api

- .github/workflows/all.yml
Reference: https://www.debian.org/releases/bullseye/
> build: Add Debian Bullseye.

- src/transcoder/transcodedialog.cpp
- src/transcoder/transcodedialog.ui
Reverts clementine-player/Clementine#7118
> Revert "Added option to remove/replace originals in transcoder dialog."

- src/ripper/ripcddialog.cpp
- src/ripper/ripcddialog.h
- src/ripper/ripper.cpp
- src/ripper/ripper.h
Previously the progress bar of the CD ripping dialog would only update
after a track completed, now it gets updated continuously during the
ripping process.
> Regular progress bar updates for CD ripping.

- dist/macdeploy.py
Removed from upstream gstreamer
> Remove mms plugin from mac build

- 3rdparty/qtiocompressor/CMakeLists.txt
- CMakeLists.txt
- src/CMakeLists.txt
Ref https://bugs.gentoo.org/887105
> Fix build: add zlib to deps where it's used 
